package com.shbestwin.followupmanager.model;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.text.TextUtils;

import com.shbestwin.followupmanager.common.util.DateUtils;
import com.shbestwin.followupmanager.model.device.IDCardInfo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ARCHIVE_INFO.
 */
public class ArchiveInfo {

	/** Not-null value. */
	private String idcard;
	/** Not-null value. */
	private String name;
	private String picturePath;
	/** Not-null value. */
	private String archiveNo;
	private String cardNo;
	private String gender;
	/** Not-null value. */
	private String birthday;
	private String relationship;
	/** Not-null value. */
	private String workUnit;
	/** Not-null value. */
	private String telephone;
	private String ethnic;
	private String contactName;
	private String contactPhone;
	private String education;
	private String bloodType;
	private String accountProperty;
	private String marriage;
	private String RHNegative;
	private String job;
	private String nationality;
	private String assistType;
	private String email;
	private String postcode;
	/** Not-null value. */
	private String familyAddress;
	private String residentType;
	private String residentAddress;
	private String certificateType;
	private String negativeEvent;
	private String managerUnit;
	private String createDate;
	private String categoryName;
	private String categoryNum;
	private String insuranceNo;
	private String signUpDate;
	private String exposureHistories;
	private String allergyHistories;
	private String famliyHistories;
	private String pastHistories;
	private String syntrophusHistories;
	private String bearHistories;
	private String mensesHistories;
	private String disabilityies;
	private String familyInfo;
	private String familyMermber;
	private String familyProblem;
	private String environment;

	// KEEP FIELDS - put your custom fields here
	// KEEP FIELDS END

	public ArchiveInfo() {
	}

	public ArchiveInfo(String idcard) {
		this.idcard = idcard;
	}

	public ArchiveInfo(String idcard, String name, String picturePath, String archiveNo, String cardNo, String gender, String birthday, String relationship, String workUnit, String telephone, String ethnic, String contactName,
			String contactPhone, String education, String bloodType, String accountProperty, String marriage, String RHNegative, String job, String nationality, String assistType, String email, String postcode, String familyAddress,
			String residentType, String residentAddress, String certificateType, String negativeEvent, String managerUnit, String createDate, String categoryName, String categoryNum, String insuranceNo, String signUpDate,
			String exposureHistories, String allergyHistories, String famliyHistories, String pastHistories, String syntrophusHistories, String bearHistories, String mensesHistories, String disabilityies, String familyInfo,
			String familyMermber, String familyProblem, String environment) {
		this.idcard = idcard;
		this.name = name;
		this.picturePath = picturePath;
		this.archiveNo = archiveNo;
		this.cardNo = cardNo;
		this.gender = gender;
		this.birthday = birthday;
		this.relationship = relationship;
		this.workUnit = workUnit;
		this.telephone = telephone;
		this.ethnic = ethnic;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.education = education;
		this.bloodType = bloodType;
		this.accountProperty = accountProperty;
		this.marriage = marriage;
		this.RHNegative = RHNegative;
		this.job = job;
		this.nationality = nationality;
		this.assistType = assistType;
		this.email = email;
		this.postcode = postcode;
		this.familyAddress = familyAddress;
		this.residentType = residentType;
		this.residentAddress = residentAddress;
		this.certificateType = certificateType;
		this.negativeEvent = negativeEvent;
		this.managerUnit = managerUnit;
		this.createDate = createDate;
		this.categoryName = categoryName;
		this.categoryNum = categoryNum;
		this.insuranceNo = insuranceNo;
		this.signUpDate = signUpDate;
		this.exposureHistories = exposureHistories;
		this.allergyHistories = allergyHistories;
		this.famliyHistories = famliyHistories;
		this.pastHistories = pastHistories;
		this.syntrophusHistories = syntrophusHistories;
		this.bearHistories = bearHistories;
		this.mensesHistories = mensesHistories;
		this.disabilityies = disabilityies;
		this.familyInfo = familyInfo;
		this.familyMermber = familyMermber;
		this.familyProblem = familyProblem;
		this.environment = environment;
	}

	public void render(IDCardInfo idCardInfo) {
		this.idcard = idCardInfo.getIdcard();
		this.name = idCardInfo.getName();
		this.picturePath = idCardInfo.getPicturePath();
		this.gender = idCardInfo.getGender();
		this.birthday = idCardInfo.getBirthday();
		if (!TextUtils.isEmpty(this.birthday)) {
			this.birthday = DateUtils.formatDate(DateUtils.parseDate(this.birthday, "yyyyMMdd"), "yyyy-MM-dd");
		}
		this.ethnic = idCardInfo.getEthnic();
		this.residentAddress = idCardInfo.getAddress();
	}

	public Bitmap getPicture() {
		if (TextUtils.isEmpty(picturePath)) {
			return null;
		}
		File file = new File(picturePath);
		if (!file.exists()) {
			return null;
		}

		FileInputStream fis = null;
		try {
			fis = new FileInputStream(picturePath);
			Bitmap bmp = BitmapFactory.decodeStream(fis);
			return bmp;
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} finally {
			if (fis != null) {
				try {
					fis.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
		return null;
	}

	/** Not-null value. */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/** Not-null value. */
	public String getName() {
		return name;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setName(String name) {
		this.name = name;
	}

	public String getPicturePath() {
		return picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	/** Not-null value. */
	public String getArchiveNo() {
		return archiveNo;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setArchiveNo(String archiveNo) {
		this.archiveNo = archiveNo;
	}

	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	/** Not-null value. */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getRelationship() {
		return relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	/** Not-null value. */
	public String getWorkUnit() {
		return workUnit;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit;
	}

	/** Not-null value. */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEthnic() {
		return ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPhone() {
		return contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getBloodType() {
		return bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getAccountProperty() {
		return accountProperty;
	}

	public void setAccountProperty(String accountProperty) {
		this.accountProperty = accountProperty;
	}

	public String getMarriage() {
		return marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	public String getRHNegative() {
		return RHNegative;
	}

	public void setRHNegative(String RHNegative) {
		this.RHNegative = RHNegative;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getAssistType() {
		return assistType;
	}

	public void setAssistType(String assistType) {
		this.assistType = assistType;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	/** Not-null value. */
	public String getFamilyAddress() {
		return familyAddress;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setFamilyAddress(String familyAddress) {
		this.familyAddress = familyAddress;
	}

	public String getResidentType() {
		return residentType;
	}

	public void setResidentType(String residentType) {
		this.residentType = residentType;
	}

	public String getResidentAddress() {
		return residentAddress;
	}

	public void setResidentAddress(String residentAddress) {
		this.residentAddress = residentAddress;
	}

	public String getCertificateType() {
		return certificateType;
	}

	public void setCertificateType(String certificateType) {
		this.certificateType = certificateType;
	}

	public String getNegativeEvent() {
		return negativeEvent;
	}

	public void setNegativeEvent(String negativeEvent) {
		this.negativeEvent = negativeEvent;
	}

	public String getManagerUnit() {
		return managerUnit;
	}

	public void setManagerUnit(String managerUnit) {
		this.managerUnit = managerUnit;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryNum() {
		return categoryNum;
	}

	public void setCategoryNum(String categoryNum) {
		this.categoryNum = categoryNum;
	}

	public String getInsuranceNo() {
		return insuranceNo;
	}

	public void setInsuranceNo(String insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	public String getSignUpDate() {
		return signUpDate;
	}

	public void setSignUpDate(String signUpDate) {
		this.signUpDate = signUpDate;
	}

	public String getExposureHistories() {
		return exposureHistories;
	}

	public void setExposureHistories(String exposureHistories) {
		this.exposureHistories = exposureHistories;
	}

	public String getAllergyHistories() {
		return allergyHistories;
	}

	public void setAllergyHistories(String allergyHistories) {
		this.allergyHistories = allergyHistories;
	}

	public String getFamliyHistories() {
		return famliyHistories;
	}

	public void setFamliyHistories(String famliyHistories) {
		this.famliyHistories = famliyHistories;
	}

	public String getPastHistories() {
		return pastHistories;
	}

	public void setPastHistories(String pastHistories) {
		this.pastHistories = pastHistories;
	}

	public String getSyntrophusHistories() {
		return syntrophusHistories;
	}

	public void setSyntrophusHistories(String syntrophusHistories) {
		this.syntrophusHistories = syntrophusHistories;
	}

	public String getBearHistories() {
		return bearHistories;
	}

	public void setBearHistories(String bearHistories) {
		this.bearHistories = bearHistories;
	}

	public String getMensesHistories() {
		return mensesHistories;
	}

	public void setMensesHistories(String mensesHistories) {
		this.mensesHistories = mensesHistories;
	}

	public String getDisabilityies() {
		return disabilityies;
	}

	public void setDisabilityies(String disabilityies) {
		this.disabilityies = disabilityies;
	}

	public String getFamilyInfo() {
		return familyInfo;
	}

	public void setFamilyInfo(String familyInfo) {
		this.familyInfo = familyInfo;
	}

	public String getFamilyMermber() {
		return familyMermber;
	}

	public void setFamilyMermber(String familyMermber) {
		this.familyMermber = familyMermber;
	}

	public String getFamilyProblem() {
		return familyProblem;
	}

	public void setFamilyProblem(String familyProblem) {
		this.familyProblem = familyProblem;
	}

	public String getEnvironment() {
		return environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
