package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_TWO_TO_FIVE_PREGNANCY.
 */
public class FollowUpTwoToFivePregnancy {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_fsrq;
    private String grxx_yz;
    private String grxx_cqfscs;
    private String grxx_zs;
    private String tz_tz;
    private String tz_xy;
    private String tz_xhdb;
    private String tz_ndb;
    private String cqjc_gdgd;
    private String cqjc_fw;
    private String cqjc_txl;
    private Boolean qtjc_sfbc;
    private String qtjc_sfbcms;
    private Boolean qtjc_sfxtsc;
    private String qtjc_sfxtscms;
    private String zd_name;
    private Boolean zz_sfygzz;
    private String zz_yy;
    private String zz_jgjks;
    private String zz_xcsfrq;
    private String ztpg_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpTwoToFivePregnancy() {
    }

    public FollowUpTwoToFivePregnancy(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpTwoToFivePregnancy(String followUpNo, String idcard, String grxx_fsrq, String grxx_yz, String grxx_cqfscs, String grxx_zs, String tz_tz, String tz_xy, String tz_xhdb, String tz_ndb, String cqjc_gdgd, String cqjc_fw, String cqjc_txl, Boolean qtjc_sfbc, String qtjc_sfbcms, Boolean qtjc_sfxtsc, String qtjc_sfxtscms, String zd_name, Boolean zz_sfygzz, String zz_yy, String zz_jgjks, String zz_xcsfrq, String ztpg_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_fsrq = grxx_fsrq;
        this.grxx_yz = grxx_yz;
        this.grxx_cqfscs = grxx_cqfscs;
        this.grxx_zs = grxx_zs;
        this.tz_tz = tz_tz;
        this.tz_xy = tz_xy;
        this.tz_xhdb = tz_xhdb;
        this.tz_ndb = tz_ndb;
        this.cqjc_gdgd = cqjc_gdgd;
        this.cqjc_fw = cqjc_fw;
        this.cqjc_txl = cqjc_txl;
        this.qtjc_sfbc = qtjc_sfbc;
        this.qtjc_sfbcms = qtjc_sfbcms;
        this.qtjc_sfxtsc = qtjc_sfxtsc;
        this.qtjc_sfxtscms = qtjc_sfxtscms;
        this.zd_name = zd_name;
        this.zz_sfygzz = zz_sfygzz;
        this.zz_yy = zz_yy;
        this.zz_jgjks = zz_jgjks;
        this.zz_xcsfrq = zz_xcsfrq;
        this.ztpg_sfysqm = ztpg_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_fsrq() {
        return grxx_fsrq;
    }

    public void setGrxx_fsrq(String grxx_fsrq) {
        this.grxx_fsrq = grxx_fsrq;
    }

    public String getGrxx_yz() {
        return grxx_yz;
    }

    public void setGrxx_yz(String grxx_yz) {
        this.grxx_yz = grxx_yz;
    }

    public String getGrxx_cqfscs() {
        return grxx_cqfscs;
    }

    public void setGrxx_cqfscs(String grxx_cqfscs) {
        this.grxx_cqfscs = grxx_cqfscs;
    }

    public String getGrxx_zs() {
        return grxx_zs;
    }

    public void setGrxx_zs(String grxx_zs) {
        this.grxx_zs = grxx_zs;
    }

    public String getTz_tz() {
        return tz_tz;
    }

    public void setTz_tz(String tz_tz) {
        this.tz_tz = tz_tz;
    }

    public String getTz_xy() {
        return tz_xy;
    }

    public void setTz_xy(String tz_xy) {
        this.tz_xy = tz_xy;
    }

    public String getTz_xhdb() {
        return tz_xhdb;
    }

    public void setTz_xhdb(String tz_xhdb) {
        this.tz_xhdb = tz_xhdb;
    }

    public String getTz_ndb() {
        return tz_ndb;
    }

    public void setTz_ndb(String tz_ndb) {
        this.tz_ndb = tz_ndb;
    }

    public String getCqjc_gdgd() {
        return cqjc_gdgd;
    }

    public void setCqjc_gdgd(String cqjc_gdgd) {
        this.cqjc_gdgd = cqjc_gdgd;
    }

    public String getCqjc_fw() {
        return cqjc_fw;
    }

    public void setCqjc_fw(String cqjc_fw) {
        this.cqjc_fw = cqjc_fw;
    }

    public String getCqjc_txl() {
        return cqjc_txl;
    }

    public void setCqjc_txl(String cqjc_txl) {
        this.cqjc_txl = cqjc_txl;
    }

    public Boolean getQtjc_sfbc() {
        return qtjc_sfbc;
    }

    public void setQtjc_sfbc(Boolean qtjc_sfbc) {
        this.qtjc_sfbc = qtjc_sfbc;
    }

    public String getQtjc_sfbcms() {
        return qtjc_sfbcms;
    }

    public void setQtjc_sfbcms(String qtjc_sfbcms) {
        this.qtjc_sfbcms = qtjc_sfbcms;
    }

    public Boolean getQtjc_sfxtsc() {
        return qtjc_sfxtsc;
    }

    public void setQtjc_sfxtsc(Boolean qtjc_sfxtsc) {
        this.qtjc_sfxtsc = qtjc_sfxtsc;
    }

    public String getQtjc_sfxtscms() {
        return qtjc_sfxtscms;
    }

    public void setQtjc_sfxtscms(String qtjc_sfxtscms) {
        this.qtjc_sfxtscms = qtjc_sfxtscms;
    }

    public String getZd_name() {
        return zd_name;
    }

    public void setZd_name(String zd_name) {
        this.zd_name = zd_name;
    }

    public Boolean getZz_sfygzz() {
        return zz_sfygzz;
    }

    public void setZz_sfygzz(Boolean zz_sfygzz) {
        this.zz_sfygzz = zz_sfygzz;
    }

    public String getZz_yy() {
        return zz_yy;
    }

    public void setZz_yy(String zz_yy) {
        this.zz_yy = zz_yy;
    }

    public String getZz_jgjks() {
        return zz_jgjks;
    }

    public void setZz_jgjks(String zz_jgjks) {
        this.zz_jgjks = zz_jgjks;
    }

    public String getZz_xcsfrq() {
        return zz_xcsfrq;
    }

    public void setZz_xcsfrq(String zz_xcsfrq) {
        this.zz_xcsfrq = zz_xcsfrq;
    }

    public String getZtpg_sfysqm() {
        return ztpg_sfysqm;
    }

    public void setZtpg_sfysqm(String ztpg_sfysqm) {
        this.ztpg_sfysqm = ztpg_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
