package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_AGED.
 */
public class FollowUpAged {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_zrys;
    private String grxx_sfrq;
    private String grxx_sfzqjy;
    private String grxx_sffs;
    private String grxx_sfxz;
    private String grxx_xlzt;
    private String zz;
    private String tz_xy;
    private String tz_xl;
    private String tz_yw;
    private String tz_sg;
    private String tz_tz;
    private String tz_tzzs;
    private String tz_xzdgc;
    private String tz_gmddb;
    private String tz_xgysz;
    private String tz_dmddb;
    private String tz_kfxt;
    private String tz_qt;
    private Boolean shfszd_sfxy;
    private String shfszd_sfxyms;
    private Boolean shfszd_sfyj;
    private String shfszd_sfyjms;
    private Boolean shfszd_sfyd;
    private String shfszd_sfydms;
    private String shfszd_ydxm;
    private String shfszd_syqk;
    private String shfszd_xltz;
    private String shfszd_zyxw;
    private String shfszd_mqqk;
    private String shfszd_sffwnr;
    private String shfszd_sfpg;
    private String shfszd_xcsfrq;
    private String shfszd_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpAged() {
    }

    public FollowUpAged(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpAged(String followUpNo, String idcard, String grxx_zrys, String grxx_sfrq, String grxx_sfzqjy, String grxx_sffs, String grxx_sfxz, String grxx_xlzt, String zz, String tz_xy, String tz_xl, String tz_yw, String tz_sg, String tz_tz, String tz_tzzs, String tz_xzdgc, String tz_gmddb, String tz_xgysz, String tz_dmddb, String tz_kfxt, String tz_qt, Boolean shfszd_sfxy, String shfszd_sfxyms, Boolean shfszd_sfyj, String shfszd_sfyjms, Boolean shfszd_sfyd, String shfszd_sfydms, String shfszd_ydxm, String shfszd_syqk, String shfszd_xltz, String shfszd_zyxw, String shfszd_mqqk, String shfszd_sffwnr, String shfszd_sfpg, String shfszd_xcsfrq, String shfszd_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_zrys = grxx_zrys;
        this.grxx_sfrq = grxx_sfrq;
        this.grxx_sfzqjy = grxx_sfzqjy;
        this.grxx_sffs = grxx_sffs;
        this.grxx_sfxz = grxx_sfxz;
        this.grxx_xlzt = grxx_xlzt;
        this.zz = zz;
        this.tz_xy = tz_xy;
        this.tz_xl = tz_xl;
        this.tz_yw = tz_yw;
        this.tz_sg = tz_sg;
        this.tz_tz = tz_tz;
        this.tz_tzzs = tz_tzzs;
        this.tz_xzdgc = tz_xzdgc;
        this.tz_gmddb = tz_gmddb;
        this.tz_xgysz = tz_xgysz;
        this.tz_dmddb = tz_dmddb;
        this.tz_kfxt = tz_kfxt;
        this.tz_qt = tz_qt;
        this.shfszd_sfxy = shfszd_sfxy;
        this.shfszd_sfxyms = shfszd_sfxyms;
        this.shfszd_sfyj = shfszd_sfyj;
        this.shfszd_sfyjms = shfszd_sfyjms;
        this.shfszd_sfyd = shfszd_sfyd;
        this.shfszd_sfydms = shfszd_sfydms;
        this.shfszd_ydxm = shfszd_ydxm;
        this.shfszd_syqk = shfszd_syqk;
        this.shfszd_xltz = shfszd_xltz;
        this.shfszd_zyxw = shfszd_zyxw;
        this.shfszd_mqqk = shfszd_mqqk;
        this.shfszd_sffwnr = shfszd_sffwnr;
        this.shfszd_sfpg = shfszd_sfpg;
        this.shfszd_xcsfrq = shfszd_xcsfrq;
        this.shfszd_sfysqm = shfszd_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getGrxx_sfrq() {
        return grxx_sfrq;
    }

    public void setGrxx_sfrq(String grxx_sfrq) {
        this.grxx_sfrq = grxx_sfrq;
    }

    public String getGrxx_sfzqjy() {
        return grxx_sfzqjy;
    }

    public void setGrxx_sfzqjy(String grxx_sfzqjy) {
        this.grxx_sfzqjy = grxx_sfzqjy;
    }

    public String getGrxx_sffs() {
        return grxx_sffs;
    }

    public void setGrxx_sffs(String grxx_sffs) {
        this.grxx_sffs = grxx_sffs;
    }

    public String getGrxx_sfxz() {
        return grxx_sfxz;
    }

    public void setGrxx_sfxz(String grxx_sfxz) {
        this.grxx_sfxz = grxx_sfxz;
    }

    public String getGrxx_xlzt() {
        return grxx_xlzt;
    }

    public void setGrxx_xlzt(String grxx_xlzt) {
        this.grxx_xlzt = grxx_xlzt;
    }

    public String getZz() {
        return zz;
    }

    public void setZz(String zz) {
        this.zz = zz;
    }

    public String getTz_xy() {
        return tz_xy;
    }

    public void setTz_xy(String tz_xy) {
        this.tz_xy = tz_xy;
    }

    public String getTz_xl() {
        return tz_xl;
    }

    public void setTz_xl(String tz_xl) {
        this.tz_xl = tz_xl;
    }

    public String getTz_yw() {
        return tz_yw;
    }

    public void setTz_yw(String tz_yw) {
        this.tz_yw = tz_yw;
    }

    public String getTz_sg() {
        return tz_sg;
    }

    public void setTz_sg(String tz_sg) {
        this.tz_sg = tz_sg;
    }

    public String getTz_tz() {
        return tz_tz;
    }

    public void setTz_tz(String tz_tz) {
        this.tz_tz = tz_tz;
    }

    public String getTz_tzzs() {
        return tz_tzzs;
    }

    public void setTz_tzzs(String tz_tzzs) {
        this.tz_tzzs = tz_tzzs;
    }

    public String getTz_xzdgc() {
        return tz_xzdgc;
    }

    public void setTz_xzdgc(String tz_xzdgc) {
        this.tz_xzdgc = tz_xzdgc;
    }

    public String getTz_gmddb() {
        return tz_gmddb;
    }

    public void setTz_gmddb(String tz_gmddb) {
        this.tz_gmddb = tz_gmddb;
    }

    public String getTz_xgysz() {
        return tz_xgysz;
    }

    public void setTz_xgysz(String tz_xgysz) {
        this.tz_xgysz = tz_xgysz;
    }

    public String getTz_dmddb() {
        return tz_dmddb;
    }

    public void setTz_dmddb(String tz_dmddb) {
        this.tz_dmddb = tz_dmddb;
    }

    public String getTz_kfxt() {
        return tz_kfxt;
    }

    public void setTz_kfxt(String tz_kfxt) {
        this.tz_kfxt = tz_kfxt;
    }

    public String getTz_qt() {
        return tz_qt;
    }

    public void setTz_qt(String tz_qt) {
        this.tz_qt = tz_qt;
    }

    public Boolean getShfszd_sfxy() {
        return shfszd_sfxy;
    }

    public void setShfszd_sfxy(Boolean shfszd_sfxy) {
        this.shfszd_sfxy = shfszd_sfxy;
    }

    public String getShfszd_sfxyms() {
        return shfszd_sfxyms;
    }

    public void setShfszd_sfxyms(String shfszd_sfxyms) {
        this.shfszd_sfxyms = shfszd_sfxyms;
    }

    public Boolean getShfszd_sfyj() {
        return shfszd_sfyj;
    }

    public void setShfszd_sfyj(Boolean shfszd_sfyj) {
        this.shfszd_sfyj = shfszd_sfyj;
    }

    public String getShfszd_sfyjms() {
        return shfszd_sfyjms;
    }

    public void setShfszd_sfyjms(String shfszd_sfyjms) {
        this.shfszd_sfyjms = shfszd_sfyjms;
    }

    public Boolean getShfszd_sfyd() {
        return shfszd_sfyd;
    }

    public void setShfszd_sfyd(Boolean shfszd_sfyd) {
        this.shfszd_sfyd = shfszd_sfyd;
    }

    public String getShfszd_sfydms() {
        return shfszd_sfydms;
    }

    public void setShfszd_sfydms(String shfszd_sfydms) {
        this.shfszd_sfydms = shfszd_sfydms;
    }

    public String getShfszd_ydxm() {
        return shfszd_ydxm;
    }

    public void setShfszd_ydxm(String shfszd_ydxm) {
        this.shfszd_ydxm = shfszd_ydxm;
    }

    public String getShfszd_syqk() {
        return shfszd_syqk;
    }

    public void setShfszd_syqk(String shfszd_syqk) {
        this.shfszd_syqk = shfszd_syqk;
    }

    public String getShfszd_xltz() {
        return shfszd_xltz;
    }

    public void setShfszd_xltz(String shfszd_xltz) {
        this.shfszd_xltz = shfszd_xltz;
    }

    public String getShfszd_zyxw() {
        return shfszd_zyxw;
    }

    public void setShfszd_zyxw(String shfszd_zyxw) {
        this.shfszd_zyxw = shfszd_zyxw;
    }

    public String getShfszd_mqqk() {
        return shfszd_mqqk;
    }

    public void setShfszd_mqqk(String shfszd_mqqk) {
        this.shfszd_mqqk = shfszd_mqqk;
    }

    public String getShfszd_sffwnr() {
        return shfszd_sffwnr;
    }

    public void setShfszd_sffwnr(String shfszd_sffwnr) {
        this.shfszd_sffwnr = shfszd_sffwnr;
    }

    public String getShfszd_sfpg() {
        return shfszd_sfpg;
    }

    public void setShfszd_sfpg(String shfszd_sfpg) {
        this.shfszd_sfpg = shfszd_sfpg;
    }

    public String getShfszd_xcsfrq() {
        return shfszd_xcsfrq;
    }

    public void setShfszd_xcsfrq(String shfszd_xcsfrq) {
        this.shfszd_xcsfrq = shfszd_xcsfrq;
    }

    public String getShfszd_sfysqm() {
        return shfszd_sfysqm;
    }

    public void setShfszd_sfysqm(String shfszd_sfysqm) {
        this.shfszd_sfysqm = shfszd_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
