package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_MENTAL_DISEASE.
 */
public class FollowUpMentalDisease {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_zrys;
    private String grxx_sfrq;
    private String wxx;
    private String zz_zzmc;
    private String zz_zzl;
    private String zz_smqk;
    private String zz_ysqk;
    private String shgnqk_grshll;
    private String shgnqk_jwhd;
    private String shgnqk_xxnl;
    private String shgnqk_shldjgz;
    private String shgnqk_shrjjw;
    private String hzdjtshdyx_qdzs;
    private String hzdjtshdyx_zhaos;
    private String hzdjtshdyx_zs;
    private String hzdjtshdyx_zsws;
    private String hzdjtshdyx_gsqk;
    private String hzdjtshdyx_mccysj;
    private String hzdjtshdyx_zyqk;
    private String sysfzjc_jcx;
    private String sysfzjc_fyycx;
    private Boolean shxggb_sfywblfy;
    private String shxggb_sfywblfyms;
    private String shxggb_zlxg;
    private Boolean shxggb_sfzz;
    private String shxggb_sfzzms;
    private String shxggb_jgqks;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpMentalDisease() {
    }

    public FollowUpMentalDisease(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpMentalDisease(String followUpNo, String idcard, String grxx_zrys, String grxx_sfrq, String wxx, String zz_zzmc, String zz_zzl, String zz_smqk, String zz_ysqk, String shgnqk_grshll, String shgnqk_jwhd, String shgnqk_xxnl, String shgnqk_shldjgz, String shgnqk_shrjjw, String hzdjtshdyx_qdzs, String hzdjtshdyx_zhaos, String hzdjtshdyx_zs, String hzdjtshdyx_zsws, String hzdjtshdyx_gsqk, String hzdjtshdyx_mccysj, String hzdjtshdyx_zyqk, String sysfzjc_jcx, String sysfzjc_fyycx, Boolean shxggb_sfywblfy, String shxggb_sfywblfyms, String shxggb_zlxg, Boolean shxggb_sfzz, String shxggb_sfzzms, String shxggb_jgqks, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_zrys = grxx_zrys;
        this.grxx_sfrq = grxx_sfrq;
        this.wxx = wxx;
        this.zz_zzmc = zz_zzmc;
        this.zz_zzl = zz_zzl;
        this.zz_smqk = zz_smqk;
        this.zz_ysqk = zz_ysqk;
        this.shgnqk_grshll = shgnqk_grshll;
        this.shgnqk_jwhd = shgnqk_jwhd;
        this.shgnqk_xxnl = shgnqk_xxnl;
        this.shgnqk_shldjgz = shgnqk_shldjgz;
        this.shgnqk_shrjjw = shgnqk_shrjjw;
        this.hzdjtshdyx_qdzs = hzdjtshdyx_qdzs;
        this.hzdjtshdyx_zhaos = hzdjtshdyx_zhaos;
        this.hzdjtshdyx_zs = hzdjtshdyx_zs;
        this.hzdjtshdyx_zsws = hzdjtshdyx_zsws;
        this.hzdjtshdyx_gsqk = hzdjtshdyx_gsqk;
        this.hzdjtshdyx_mccysj = hzdjtshdyx_mccysj;
        this.hzdjtshdyx_zyqk = hzdjtshdyx_zyqk;
        this.sysfzjc_jcx = sysfzjc_jcx;
        this.sysfzjc_fyycx = sysfzjc_fyycx;
        this.shxggb_sfywblfy = shxggb_sfywblfy;
        this.shxggb_sfywblfyms = shxggb_sfywblfyms;
        this.shxggb_zlxg = shxggb_zlxg;
        this.shxggb_sfzz = shxggb_sfzz;
        this.shxggb_sfzzms = shxggb_sfzzms;
        this.shxggb_jgqks = shxggb_jgqks;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getGrxx_sfrq() {
        return grxx_sfrq;
    }

    public void setGrxx_sfrq(String grxx_sfrq) {
        this.grxx_sfrq = grxx_sfrq;
    }

    public String getWxx() {
        return wxx;
    }

    public void setWxx(String wxx) {
        this.wxx = wxx;
    }

    public String getZz_zzmc() {
        return zz_zzmc;
    }

    public void setZz_zzmc(String zz_zzmc) {
        this.zz_zzmc = zz_zzmc;
    }

    public String getZz_zzl() {
        return zz_zzl;
    }

    public void setZz_zzl(String zz_zzl) {
        this.zz_zzl = zz_zzl;
    }

    public String getZz_smqk() {
        return zz_smqk;
    }

    public void setZz_smqk(String zz_smqk) {
        this.zz_smqk = zz_smqk;
    }

    public String getZz_ysqk() {
        return zz_ysqk;
    }

    public void setZz_ysqk(String zz_ysqk) {
        this.zz_ysqk = zz_ysqk;
    }

    public String getShgnqk_grshll() {
        return shgnqk_grshll;
    }

    public void setShgnqk_grshll(String shgnqk_grshll) {
        this.shgnqk_grshll = shgnqk_grshll;
    }

    public String getShgnqk_jwhd() {
        return shgnqk_jwhd;
    }

    public void setShgnqk_jwhd(String shgnqk_jwhd) {
        this.shgnqk_jwhd = shgnqk_jwhd;
    }

    public String getShgnqk_xxnl() {
        return shgnqk_xxnl;
    }

    public void setShgnqk_xxnl(String shgnqk_xxnl) {
        this.shgnqk_xxnl = shgnqk_xxnl;
    }

    public String getShgnqk_shldjgz() {
        return shgnqk_shldjgz;
    }

    public void setShgnqk_shldjgz(String shgnqk_shldjgz) {
        this.shgnqk_shldjgz = shgnqk_shldjgz;
    }

    public String getShgnqk_shrjjw() {
        return shgnqk_shrjjw;
    }

    public void setShgnqk_shrjjw(String shgnqk_shrjjw) {
        this.shgnqk_shrjjw = shgnqk_shrjjw;
    }

    public String getHzdjtshdyx_qdzs() {
        return hzdjtshdyx_qdzs;
    }

    public void setHzdjtshdyx_qdzs(String hzdjtshdyx_qdzs) {
        this.hzdjtshdyx_qdzs = hzdjtshdyx_qdzs;
    }

    public String getHzdjtshdyx_zhaos() {
        return hzdjtshdyx_zhaos;
    }

    public void setHzdjtshdyx_zhaos(String hzdjtshdyx_zhaos) {
        this.hzdjtshdyx_zhaos = hzdjtshdyx_zhaos;
    }

    public String getHzdjtshdyx_zs() {
        return hzdjtshdyx_zs;
    }

    public void setHzdjtshdyx_zs(String hzdjtshdyx_zs) {
        this.hzdjtshdyx_zs = hzdjtshdyx_zs;
    }

    public String getHzdjtshdyx_zsws() {
        return hzdjtshdyx_zsws;
    }

    public void setHzdjtshdyx_zsws(String hzdjtshdyx_zsws) {
        this.hzdjtshdyx_zsws = hzdjtshdyx_zsws;
    }

    public String getHzdjtshdyx_gsqk() {
        return hzdjtshdyx_gsqk;
    }

    public void setHzdjtshdyx_gsqk(String hzdjtshdyx_gsqk) {
        this.hzdjtshdyx_gsqk = hzdjtshdyx_gsqk;
    }

    public String getHzdjtshdyx_mccysj() {
        return hzdjtshdyx_mccysj;
    }

    public void setHzdjtshdyx_mccysj(String hzdjtshdyx_mccysj) {
        this.hzdjtshdyx_mccysj = hzdjtshdyx_mccysj;
    }

    public String getHzdjtshdyx_zyqk() {
        return hzdjtshdyx_zyqk;
    }

    public void setHzdjtshdyx_zyqk(String hzdjtshdyx_zyqk) {
        this.hzdjtshdyx_zyqk = hzdjtshdyx_zyqk;
    }

    public String getSysfzjc_jcx() {
        return sysfzjc_jcx;
    }

    public void setSysfzjc_jcx(String sysfzjc_jcx) {
        this.sysfzjc_jcx = sysfzjc_jcx;
    }

    public String getSysfzjc_fyycx() {
        return sysfzjc_fyycx;
    }

    public void setSysfzjc_fyycx(String sysfzjc_fyycx) {
        this.sysfzjc_fyycx = sysfzjc_fyycx;
    }

    public Boolean getShxggb_sfywblfy() {
        return shxggb_sfywblfy;
    }

    public void setShxggb_sfywblfy(Boolean shxggb_sfywblfy) {
        this.shxggb_sfywblfy = shxggb_sfywblfy;
    }

    public String getShxggb_sfywblfyms() {
        return shxggb_sfywblfyms;
    }

    public void setShxggb_sfywblfyms(String shxggb_sfywblfyms) {
        this.shxggb_sfywblfyms = shxggb_sfywblfyms;
    }

    public String getShxggb_zlxg() {
        return shxggb_zlxg;
    }

    public void setShxggb_zlxg(String shxggb_zlxg) {
        this.shxggb_zlxg = shxggb_zlxg;
    }

    public Boolean getShxggb_sfzz() {
        return shxggb_sfzz;
    }

    public void setShxggb_sfzz(Boolean shxggb_sfzz) {
        this.shxggb_sfzz = shxggb_sfzz;
    }

    public String getShxggb_sfzzms() {
        return shxggb_sfzzms;
    }

    public void setShxggb_sfzzms(String shxggb_sfzzms) {
        this.shxggb_sfzzms = shxggb_sfzzms;
    }

    public String getShxggb_jgqks() {
        return shxggb_jgqks;
    }

    public void setShxggb_jgqks(String shxggb_jgqks) {
        this.shxggb_jgqks = shxggb_jgqks;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
