package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_ONE_NEWBORN.
 */
public class FollowUpOneNewborn {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_fsrq;
    private String grxx_yl;
    private String grxx_zrys;
    private String wyqk_wyfs;
    private String wyqk_wmrcs;
    private String wyqk_nf;
    private String wyqk_mfhz;
    private String wyqk_cngn;
    private String wyqk_dhhgn;
    private String wyqk_tjfs;
    private String wyqk_cs;
    private String wyqk_sy;
    private String wyqk_fywssd;
    private String tgjcqk_tz;
    private String tgjcqk_sc;
    private String tgjcqk_bmi;
    private String tgjcqk_yw;
    private String tgjcqk_yypj;
    private String tgjcqk_ms;
    private Boolean tgjcqk_sfqxbh;
    private String tgjcqk_sfqxbhms;
    private Boolean tgjcqk_sfjbbk;
    private String tgjcqk_sfjbbkms;
    private Boolean tgjcqk_sfpfyc;
    private String tgjcqk_sfpfycms;
    private Boolean tgjcqk_sfywgyc;
    private String tgjcqk_sfywgycms;
    private Boolean tgjcqk_sfewgyc;
    private String tgjcqk_sfewgycms;
    private Boolean tgjcqk_sfbyc;
    private String tgjcqk_sfbycms;
    private Boolean tgjcqk_sfkqyc;
    private String tgjcqk_sfkqycms;
    private Boolean tgjcqk_sftlyc;
    private String tgjcqk_sftlycms;
    private Boolean tgjcqk_sfxftzyc;
    private String tgjcqk_sfxftzycms;
    private Boolean tgjcqk_sffbczyc;
    private String tgjcqk_sffbczycms;
    private Boolean tgjcqk_sfszhddyc;
    private String tgjcqk_sfszhddycms;
    private String tgjcqk_qb;
    private String tgjcqk_glbzz;
    private String tgjcqk_glbtz;
    private Boolean tgjcqk_sfwszqyc;
    private String tgjcqk_sfwszqycms;
    private Boolean tgjcqk_sfgmyc;
    private String tgjcqk_sfgmycms;
    private String tgjcqk_kgjhd;
    private Boolean fysc_sffwtt;
    private Boolean fysc_sfdyshwx;
    private Boolean fysc_sfjbsnzjkzt;
    private Boolean fysc_sfszk;
    private Boolean fysc_sfxcs;
    private Boolean fysc_sfsszwj;
    private Boolean fysc_sfhfs;
    private Boolean fysc_sfzjzsdzjwx;
    private Boolean fysc_sfrs;
    private Boolean fysc_sfyszcz;
    private String xhdbz;
    private String sysjc;
    private String fzjc;
    private String hwhd;
    private Boolean fypg_sftg;
    private Boolean hbqk_sfhb;
    private String hbqk_sfhbms;
    private String jbzd;
    private Boolean yyxjbgl_sfyyxjb;
    private Boolean yyxjbgl_sfgwe;
    private Boolean zz_sfzz;
    private String zz_yy;
    private String zz_jgjks;
    private String zd_zd;
    private String zd_yzhjy;
    private String zd_xcsfrq;
    private String zd_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpOneNewborn() {
    }

    public FollowUpOneNewborn(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpOneNewborn(String followUpNo, String idcard, String grxx_fsrq, String grxx_yl, String grxx_zrys, String wyqk_wyfs, String wyqk_wmrcs, String wyqk_nf, String wyqk_mfhz, String wyqk_cngn, String wyqk_dhhgn, String wyqk_tjfs, String wyqk_cs, String wyqk_sy, String wyqk_fywssd, String tgjcqk_tz, String tgjcqk_sc, String tgjcqk_bmi, String tgjcqk_yw, String tgjcqk_yypj, String tgjcqk_ms, Boolean tgjcqk_sfqxbh, String tgjcqk_sfqxbhms, Boolean tgjcqk_sfjbbk, String tgjcqk_sfjbbkms, Boolean tgjcqk_sfpfyc, String tgjcqk_sfpfycms, Boolean tgjcqk_sfywgyc, String tgjcqk_sfywgycms, Boolean tgjcqk_sfewgyc, String tgjcqk_sfewgycms, Boolean tgjcqk_sfbyc, String tgjcqk_sfbycms, Boolean tgjcqk_sfkqyc, String tgjcqk_sfkqycms, Boolean tgjcqk_sftlyc, String tgjcqk_sftlycms, Boolean tgjcqk_sfxftzyc, String tgjcqk_sfxftzycms, Boolean tgjcqk_sffbczyc, String tgjcqk_sffbczycms, Boolean tgjcqk_sfszhddyc, String tgjcqk_sfszhddycms, String tgjcqk_qb, String tgjcqk_glbzz, String tgjcqk_glbtz, Boolean tgjcqk_sfwszqyc, String tgjcqk_sfwszqycms, Boolean tgjcqk_sfgmyc, String tgjcqk_sfgmycms, String tgjcqk_kgjhd, Boolean fysc_sffwtt, Boolean fysc_sfdyshwx, Boolean fysc_sfjbsnzjkzt, Boolean fysc_sfszk, Boolean fysc_sfxcs, Boolean fysc_sfsszwj, Boolean fysc_sfhfs, Boolean fysc_sfzjzsdzjwx, Boolean fysc_sfrs, Boolean fysc_sfyszcz, String xhdbz, String sysjc, String fzjc, String hwhd, Boolean fypg_sftg, Boolean hbqk_sfhb, String hbqk_sfhbms, String jbzd, Boolean yyxjbgl_sfyyxjb, Boolean yyxjbgl_sfgwe, Boolean zz_sfzz, String zz_yy, String zz_jgjks, String zd_zd, String zd_yzhjy, String zd_xcsfrq, String zd_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_fsrq = grxx_fsrq;
        this.grxx_yl = grxx_yl;
        this.grxx_zrys = grxx_zrys;
        this.wyqk_wyfs = wyqk_wyfs;
        this.wyqk_wmrcs = wyqk_wmrcs;
        this.wyqk_nf = wyqk_nf;
        this.wyqk_mfhz = wyqk_mfhz;
        this.wyqk_cngn = wyqk_cngn;
        this.wyqk_dhhgn = wyqk_dhhgn;
        this.wyqk_tjfs = wyqk_tjfs;
        this.wyqk_cs = wyqk_cs;
        this.wyqk_sy = wyqk_sy;
        this.wyqk_fywssd = wyqk_fywssd;
        this.tgjcqk_tz = tgjcqk_tz;
        this.tgjcqk_sc = tgjcqk_sc;
        this.tgjcqk_bmi = tgjcqk_bmi;
        this.tgjcqk_yw = tgjcqk_yw;
        this.tgjcqk_yypj = tgjcqk_yypj;
        this.tgjcqk_ms = tgjcqk_ms;
        this.tgjcqk_sfqxbh = tgjcqk_sfqxbh;
        this.tgjcqk_sfqxbhms = tgjcqk_sfqxbhms;
        this.tgjcqk_sfjbbk = tgjcqk_sfjbbk;
        this.tgjcqk_sfjbbkms = tgjcqk_sfjbbkms;
        this.tgjcqk_sfpfyc = tgjcqk_sfpfyc;
        this.tgjcqk_sfpfycms = tgjcqk_sfpfycms;
        this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
        this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
        this.tgjcqk_sfewgyc = tgjcqk_sfewgyc;
        this.tgjcqk_sfewgycms = tgjcqk_sfewgycms;
        this.tgjcqk_sfbyc = tgjcqk_sfbyc;
        this.tgjcqk_sfbycms = tgjcqk_sfbycms;
        this.tgjcqk_sfkqyc = tgjcqk_sfkqyc;
        this.tgjcqk_sfkqycms = tgjcqk_sfkqycms;
        this.tgjcqk_sftlyc = tgjcqk_sftlyc;
        this.tgjcqk_sftlycms = tgjcqk_sftlycms;
        this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
        this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
        this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
        this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
        this.tgjcqk_sfszhddyc = tgjcqk_sfszhddyc;
        this.tgjcqk_sfszhddycms = tgjcqk_sfszhddycms;
        this.tgjcqk_qb = tgjcqk_qb;
        this.tgjcqk_glbzz = tgjcqk_glbzz;
        this.tgjcqk_glbtz = tgjcqk_glbtz;
        this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
        this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
        this.tgjcqk_sfgmyc = tgjcqk_sfgmyc;
        this.tgjcqk_sfgmycms = tgjcqk_sfgmycms;
        this.tgjcqk_kgjhd = tgjcqk_kgjhd;
        this.fysc_sffwtt = fysc_sffwtt;
        this.fysc_sfdyshwx = fysc_sfdyshwx;
        this.fysc_sfjbsnzjkzt = fysc_sfjbsnzjkzt;
        this.fysc_sfszk = fysc_sfszk;
        this.fysc_sfxcs = fysc_sfxcs;
        this.fysc_sfsszwj = fysc_sfsszwj;
        this.fysc_sfhfs = fysc_sfhfs;
        this.fysc_sfzjzsdzjwx = fysc_sfzjzsdzjwx;
        this.fysc_sfrs = fysc_sfrs;
        this.fysc_sfyszcz = fysc_sfyszcz;
        this.xhdbz = xhdbz;
        this.sysjc = sysjc;
        this.fzjc = fzjc;
        this.hwhd = hwhd;
        this.fypg_sftg = fypg_sftg;
        this.hbqk_sfhb = hbqk_sfhb;
        this.hbqk_sfhbms = hbqk_sfhbms;
        this.jbzd = jbzd;
        this.yyxjbgl_sfyyxjb = yyxjbgl_sfyyxjb;
        this.yyxjbgl_sfgwe = yyxjbgl_sfgwe;
        this.zz_sfzz = zz_sfzz;
        this.zz_yy = zz_yy;
        this.zz_jgjks = zz_jgjks;
        this.zd_zd = zd_zd;
        this.zd_yzhjy = zd_yzhjy;
        this.zd_xcsfrq = zd_xcsfrq;
        this.zd_sfysqm = zd_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_fsrq() {
        return grxx_fsrq;
    }

    public void setGrxx_fsrq(String grxx_fsrq) {
        this.grxx_fsrq = grxx_fsrq;
    }

    public String getGrxx_yl() {
        return grxx_yl;
    }

    public void setGrxx_yl(String grxx_yl) {
        this.grxx_yl = grxx_yl;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getWyqk_wyfs() {
        return wyqk_wyfs;
    }

    public void setWyqk_wyfs(String wyqk_wyfs) {
        this.wyqk_wyfs = wyqk_wyfs;
    }

    public String getWyqk_wmrcs() {
        return wyqk_wmrcs;
    }

    public void setWyqk_wmrcs(String wyqk_wmrcs) {
        this.wyqk_wmrcs = wyqk_wmrcs;
    }

    public String getWyqk_nf() {
        return wyqk_nf;
    }

    public void setWyqk_nf(String wyqk_nf) {
        this.wyqk_nf = wyqk_nf;
    }

    public String getWyqk_mfhz() {
        return wyqk_mfhz;
    }

    public void setWyqk_mfhz(String wyqk_mfhz) {
        this.wyqk_mfhz = wyqk_mfhz;
    }

    public String getWyqk_cngn() {
        return wyqk_cngn;
    }

    public void setWyqk_cngn(String wyqk_cngn) {
        this.wyqk_cngn = wyqk_cngn;
    }

    public String getWyqk_dhhgn() {
        return wyqk_dhhgn;
    }

    public void setWyqk_dhhgn(String wyqk_dhhgn) {
        this.wyqk_dhhgn = wyqk_dhhgn;
    }

    public String getWyqk_tjfs() {
        return wyqk_tjfs;
    }

    public void setWyqk_tjfs(String wyqk_tjfs) {
        this.wyqk_tjfs = wyqk_tjfs;
    }

    public String getWyqk_cs() {
        return wyqk_cs;
    }

    public void setWyqk_cs(String wyqk_cs) {
        this.wyqk_cs = wyqk_cs;
    }

    public String getWyqk_sy() {
        return wyqk_sy;
    }

    public void setWyqk_sy(String wyqk_sy) {
        this.wyqk_sy = wyqk_sy;
    }

    public String getWyqk_fywssd() {
        return wyqk_fywssd;
    }

    public void setWyqk_fywssd(String wyqk_fywssd) {
        this.wyqk_fywssd = wyqk_fywssd;
    }

    public String getTgjcqk_tz() {
        return tgjcqk_tz;
    }

    public void setTgjcqk_tz(String tgjcqk_tz) {
        this.tgjcqk_tz = tgjcqk_tz;
    }

    public String getTgjcqk_sc() {
        return tgjcqk_sc;
    }

    public void setTgjcqk_sc(String tgjcqk_sc) {
        this.tgjcqk_sc = tgjcqk_sc;
    }

    public String getTgjcqk_bmi() {
        return tgjcqk_bmi;
    }

    public void setTgjcqk_bmi(String tgjcqk_bmi) {
        this.tgjcqk_bmi = tgjcqk_bmi;
    }

    public String getTgjcqk_yw() {
        return tgjcqk_yw;
    }

    public void setTgjcqk_yw(String tgjcqk_yw) {
        this.tgjcqk_yw = tgjcqk_yw;
    }

    public String getTgjcqk_yypj() {
        return tgjcqk_yypj;
    }

    public void setTgjcqk_yypj(String tgjcqk_yypj) {
        this.tgjcqk_yypj = tgjcqk_yypj;
    }

    public String getTgjcqk_ms() {
        return tgjcqk_ms;
    }

    public void setTgjcqk_ms(String tgjcqk_ms) {
        this.tgjcqk_ms = tgjcqk_ms;
    }

    public Boolean getTgjcqk_sfqxbh() {
        return tgjcqk_sfqxbh;
    }

    public void setTgjcqk_sfqxbh(Boolean tgjcqk_sfqxbh) {
        this.tgjcqk_sfqxbh = tgjcqk_sfqxbh;
    }

    public String getTgjcqk_sfqxbhms() {
        return tgjcqk_sfqxbhms;
    }

    public void setTgjcqk_sfqxbhms(String tgjcqk_sfqxbhms) {
        this.tgjcqk_sfqxbhms = tgjcqk_sfqxbhms;
    }

    public Boolean getTgjcqk_sfjbbk() {
        return tgjcqk_sfjbbk;
    }

    public void setTgjcqk_sfjbbk(Boolean tgjcqk_sfjbbk) {
        this.tgjcqk_sfjbbk = tgjcqk_sfjbbk;
    }

    public String getTgjcqk_sfjbbkms() {
        return tgjcqk_sfjbbkms;
    }

    public void setTgjcqk_sfjbbkms(String tgjcqk_sfjbbkms) {
        this.tgjcqk_sfjbbkms = tgjcqk_sfjbbkms;
    }

    public Boolean getTgjcqk_sfpfyc() {
        return tgjcqk_sfpfyc;
    }

    public void setTgjcqk_sfpfyc(Boolean tgjcqk_sfpfyc) {
        this.tgjcqk_sfpfyc = tgjcqk_sfpfyc;
    }

    public String getTgjcqk_sfpfycms() {
        return tgjcqk_sfpfycms;
    }

    public void setTgjcqk_sfpfycms(String tgjcqk_sfpfycms) {
        this.tgjcqk_sfpfycms = tgjcqk_sfpfycms;
    }

    public Boolean getTgjcqk_sfywgyc() {
        return tgjcqk_sfywgyc;
    }

    public void setTgjcqk_sfywgyc(Boolean tgjcqk_sfywgyc) {
        this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
    }

    public String getTgjcqk_sfywgycms() {
        return tgjcqk_sfywgycms;
    }

    public void setTgjcqk_sfywgycms(String tgjcqk_sfywgycms) {
        this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
    }

    public Boolean getTgjcqk_sfewgyc() {
        return tgjcqk_sfewgyc;
    }

    public void setTgjcqk_sfewgyc(Boolean tgjcqk_sfewgyc) {
        this.tgjcqk_sfewgyc = tgjcqk_sfewgyc;
    }

    public String getTgjcqk_sfewgycms() {
        return tgjcqk_sfewgycms;
    }

    public void setTgjcqk_sfewgycms(String tgjcqk_sfewgycms) {
        this.tgjcqk_sfewgycms = tgjcqk_sfewgycms;
    }

    public Boolean getTgjcqk_sfbyc() {
        return tgjcqk_sfbyc;
    }

    public void setTgjcqk_sfbyc(Boolean tgjcqk_sfbyc) {
        this.tgjcqk_sfbyc = tgjcqk_sfbyc;
    }

    public String getTgjcqk_sfbycms() {
        return tgjcqk_sfbycms;
    }

    public void setTgjcqk_sfbycms(String tgjcqk_sfbycms) {
        this.tgjcqk_sfbycms = tgjcqk_sfbycms;
    }

    public Boolean getTgjcqk_sfkqyc() {
        return tgjcqk_sfkqyc;
    }

    public void setTgjcqk_sfkqyc(Boolean tgjcqk_sfkqyc) {
        this.tgjcqk_sfkqyc = tgjcqk_sfkqyc;
    }

    public String getTgjcqk_sfkqycms() {
        return tgjcqk_sfkqycms;
    }

    public void setTgjcqk_sfkqycms(String tgjcqk_sfkqycms) {
        this.tgjcqk_sfkqycms = tgjcqk_sfkqycms;
    }

    public Boolean getTgjcqk_sftlyc() {
        return tgjcqk_sftlyc;
    }

    public void setTgjcqk_sftlyc(Boolean tgjcqk_sftlyc) {
        this.tgjcqk_sftlyc = tgjcqk_sftlyc;
    }

    public String getTgjcqk_sftlycms() {
        return tgjcqk_sftlycms;
    }

    public void setTgjcqk_sftlycms(String tgjcqk_sftlycms) {
        this.tgjcqk_sftlycms = tgjcqk_sftlycms;
    }

    public Boolean getTgjcqk_sfxftzyc() {
        return tgjcqk_sfxftzyc;
    }

    public void setTgjcqk_sfxftzyc(Boolean tgjcqk_sfxftzyc) {
        this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
    }

    public String getTgjcqk_sfxftzycms() {
        return tgjcqk_sfxftzycms;
    }

    public void setTgjcqk_sfxftzycms(String tgjcqk_sfxftzycms) {
        this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
    }

    public Boolean getTgjcqk_sffbczyc() {
        return tgjcqk_sffbczyc;
    }

    public void setTgjcqk_sffbczyc(Boolean tgjcqk_sffbczyc) {
        this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
    }

    public String getTgjcqk_sffbczycms() {
        return tgjcqk_sffbczycms;
    }

    public void setTgjcqk_sffbczycms(String tgjcqk_sffbczycms) {
        this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
    }

    public Boolean getTgjcqk_sfszhddyc() {
        return tgjcqk_sfszhddyc;
    }

    public void setTgjcqk_sfszhddyc(Boolean tgjcqk_sfszhddyc) {
        this.tgjcqk_sfszhddyc = tgjcqk_sfszhddyc;
    }

    public String getTgjcqk_sfszhddycms() {
        return tgjcqk_sfszhddycms;
    }

    public void setTgjcqk_sfszhddycms(String tgjcqk_sfszhddycms) {
        this.tgjcqk_sfszhddycms = tgjcqk_sfszhddycms;
    }

    public String getTgjcqk_qb() {
        return tgjcqk_qb;
    }

    public void setTgjcqk_qb(String tgjcqk_qb) {
        this.tgjcqk_qb = tgjcqk_qb;
    }

    public String getTgjcqk_glbzz() {
        return tgjcqk_glbzz;
    }

    public void setTgjcqk_glbzz(String tgjcqk_glbzz) {
        this.tgjcqk_glbzz = tgjcqk_glbzz;
    }

    public String getTgjcqk_glbtz() {
        return tgjcqk_glbtz;
    }

    public void setTgjcqk_glbtz(String tgjcqk_glbtz) {
        this.tgjcqk_glbtz = tgjcqk_glbtz;
    }

    public Boolean getTgjcqk_sfwszqyc() {
        return tgjcqk_sfwszqyc;
    }

    public void setTgjcqk_sfwszqyc(Boolean tgjcqk_sfwszqyc) {
        this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
    }

    public String getTgjcqk_sfwszqycms() {
        return tgjcqk_sfwszqycms;
    }

    public void setTgjcqk_sfwszqycms(String tgjcqk_sfwszqycms) {
        this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
    }

    public Boolean getTgjcqk_sfgmyc() {
        return tgjcqk_sfgmyc;
    }

    public void setTgjcqk_sfgmyc(Boolean tgjcqk_sfgmyc) {
        this.tgjcqk_sfgmyc = tgjcqk_sfgmyc;
    }

    public String getTgjcqk_sfgmycms() {
        return tgjcqk_sfgmycms;
    }

    public void setTgjcqk_sfgmycms(String tgjcqk_sfgmycms) {
        this.tgjcqk_sfgmycms = tgjcqk_sfgmycms;
    }

    public String getTgjcqk_kgjhd() {
        return tgjcqk_kgjhd;
    }

    public void setTgjcqk_kgjhd(String tgjcqk_kgjhd) {
        this.tgjcqk_kgjhd = tgjcqk_kgjhd;
    }

    public Boolean getFysc_sffwtt() {
        return fysc_sffwtt;
    }

    public void setFysc_sffwtt(Boolean fysc_sffwtt) {
        this.fysc_sffwtt = fysc_sffwtt;
    }

    public Boolean getFysc_sfdyshwx() {
        return fysc_sfdyshwx;
    }

    public void setFysc_sfdyshwx(Boolean fysc_sfdyshwx) {
        this.fysc_sfdyshwx = fysc_sfdyshwx;
    }

    public Boolean getFysc_sfjbsnzjkzt() {
        return fysc_sfjbsnzjkzt;
    }

    public void setFysc_sfjbsnzjkzt(Boolean fysc_sfjbsnzjkzt) {
        this.fysc_sfjbsnzjkzt = fysc_sfjbsnzjkzt;
    }

    public Boolean getFysc_sfszk() {
        return fysc_sfszk;
    }

    public void setFysc_sfszk(Boolean fysc_sfszk) {
        this.fysc_sfszk = fysc_sfszk;
    }

    public Boolean getFysc_sfxcs() {
        return fysc_sfxcs;
    }

    public void setFysc_sfxcs(Boolean fysc_sfxcs) {
        this.fysc_sfxcs = fysc_sfxcs;
    }

    public Boolean getFysc_sfsszwj() {
        return fysc_sfsszwj;
    }

    public void setFysc_sfsszwj(Boolean fysc_sfsszwj) {
        this.fysc_sfsszwj = fysc_sfsszwj;
    }

    public Boolean getFysc_sfhfs() {
        return fysc_sfhfs;
    }

    public void setFysc_sfhfs(Boolean fysc_sfhfs) {
        this.fysc_sfhfs = fysc_sfhfs;
    }

    public Boolean getFysc_sfzjzsdzjwx() {
        return fysc_sfzjzsdzjwx;
    }

    public void setFysc_sfzjzsdzjwx(Boolean fysc_sfzjzsdzjwx) {
        this.fysc_sfzjzsdzjwx = fysc_sfzjzsdzjwx;
    }

    public Boolean getFysc_sfrs() {
        return fysc_sfrs;
    }

    public void setFysc_sfrs(Boolean fysc_sfrs) {
        this.fysc_sfrs = fysc_sfrs;
    }

    public Boolean getFysc_sfyszcz() {
        return fysc_sfyszcz;
    }

    public void setFysc_sfyszcz(Boolean fysc_sfyszcz) {
        this.fysc_sfyszcz = fysc_sfyszcz;
    }

    public String getXhdbz() {
        return xhdbz;
    }

    public void setXhdbz(String xhdbz) {
        this.xhdbz = xhdbz;
    }

    public String getSysjc() {
        return sysjc;
    }

    public void setSysjc(String sysjc) {
        this.sysjc = sysjc;
    }

    public String getFzjc() {
        return fzjc;
    }

    public void setFzjc(String fzjc) {
        this.fzjc = fzjc;
    }

    public String getHwhd() {
        return hwhd;
    }

    public void setHwhd(String hwhd) {
        this.hwhd = hwhd;
    }

    public Boolean getFypg_sftg() {
        return fypg_sftg;
    }

    public void setFypg_sftg(Boolean fypg_sftg) {
        this.fypg_sftg = fypg_sftg;
    }

    public Boolean getHbqk_sfhb() {
        return hbqk_sfhb;
    }

    public void setHbqk_sfhb(Boolean hbqk_sfhb) {
        this.hbqk_sfhb = hbqk_sfhb;
    }

    public String getHbqk_sfhbms() {
        return hbqk_sfhbms;
    }

    public void setHbqk_sfhbms(String hbqk_sfhbms) {
        this.hbqk_sfhbms = hbqk_sfhbms;
    }

    public String getJbzd() {
        return jbzd;
    }

    public void setJbzd(String jbzd) {
        this.jbzd = jbzd;
    }

    public Boolean getYyxjbgl_sfyyxjb() {
        return yyxjbgl_sfyyxjb;
    }

    public void setYyxjbgl_sfyyxjb(Boolean yyxjbgl_sfyyxjb) {
        this.yyxjbgl_sfyyxjb = yyxjbgl_sfyyxjb;
    }

    public Boolean getYyxjbgl_sfgwe() {
        return yyxjbgl_sfgwe;
    }

    public void setYyxjbgl_sfgwe(Boolean yyxjbgl_sfgwe) {
        this.yyxjbgl_sfgwe = yyxjbgl_sfgwe;
    }

    public Boolean getZz_sfzz() {
        return zz_sfzz;
    }

    public void setZz_sfzz(Boolean zz_sfzz) {
        this.zz_sfzz = zz_sfzz;
    }

    public String getZz_yy() {
        return zz_yy;
    }

    public void setZz_yy(String zz_yy) {
        this.zz_yy = zz_yy;
    }

    public String getZz_jgjks() {
        return zz_jgjks;
    }

    public void setZz_jgjks(String zz_jgjks) {
        this.zz_jgjks = zz_jgjks;
    }

    public String getZd_zd() {
        return zd_zd;
    }

    public void setZd_zd(String zd_zd) {
        this.zd_zd = zd_zd;
    }

    public String getZd_yzhjy() {
        return zd_yzhjy;
    }

    public void setZd_yzhjy(String zd_yzhjy) {
        this.zd_yzhjy = zd_yzhjy;
    }

    public String getZd_xcsfrq() {
        return zd_xcsfrq;
    }

    public void setZd_xcsfrq(String zd_xcsfrq) {
        this.zd_xcsfrq = zd_xcsfrq;
    }

    public String getZd_sfysqm() {
        return zd_sfysqm;
    }

    public void setZd_sfysqm(String zd_sfysqm) {
        this.zd_sfysqm = zd_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
