package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_DISABLED_PERSON.
 */
public class FollowUpDisabledPerson {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_zrys;
    private String grxx_sfrq;
    private String grxx_sffs;
    private String grxx_knqt;
    private String grxx_kfxq;
    private String cjnx_cjzbh;
    private String cjnx_zycj;
    private String cjnx_dccj;
    private String cjnx_cjrq;
    private String cjnx_cjcd;
    private String cjnx_cjyy;
    private String ybqk_zz;
    private String ybqk_tz;
    private String ybqk_xy;
    private String ybqk_xl;
    private String ybqk_qt;
    private String kffw_kfxm;
    private String kffw_kfmb;
    private String kffw_gnxl;
    private String kffw_xldz;
    private String kffw_xlpg;
    private String kffw_yy;
    private String kffw_zjqx;
    private Boolean shfszd_sfxy;
    private String shfszd_sfxyms;
    private Boolean shfszd_sfyj;
    private String shfszd_sfyjms;
    private Boolean shfszd_sfyd;
    private String shfszd_sfydms;
    private String shfszd_ydxm;
    private String shfszd_syqk;
    private String shfszd_xltz;
    private String shfszd_zyxw;
    private String shfszd_sfpg;
    private String shfszd_kfjy;
    private String shfszd_xcsfrq;
    private String shfszd_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpDisabledPerson() {
    }

    public FollowUpDisabledPerson(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpDisabledPerson(String followUpNo, String idcard, String grxx_zrys, String grxx_sfrq, String grxx_sffs, String grxx_knqt, String grxx_kfxq, String cjnx_cjzbh, String cjnx_zycj, String cjnx_dccj, String cjnx_cjrq, String cjnx_cjcd, String cjnx_cjyy, String ybqk_zz, String ybqk_tz, String ybqk_xy, String ybqk_xl, String ybqk_qt, String kffw_kfxm, String kffw_kfmb, String kffw_gnxl, String kffw_xldz, String kffw_xlpg, String kffw_yy, String kffw_zjqx, Boolean shfszd_sfxy, String shfszd_sfxyms, Boolean shfszd_sfyj, String shfszd_sfyjms, Boolean shfszd_sfyd, String shfszd_sfydms, String shfszd_ydxm, String shfszd_syqk, String shfszd_xltz, String shfszd_zyxw, String shfszd_sfpg, String shfszd_kfjy, String shfszd_xcsfrq, String shfszd_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_zrys = grxx_zrys;
        this.grxx_sfrq = grxx_sfrq;
        this.grxx_sffs = grxx_sffs;
        this.grxx_knqt = grxx_knqt;
        this.grxx_kfxq = grxx_kfxq;
        this.cjnx_cjzbh = cjnx_cjzbh;
        this.cjnx_zycj = cjnx_zycj;
        this.cjnx_dccj = cjnx_dccj;
        this.cjnx_cjrq = cjnx_cjrq;
        this.cjnx_cjcd = cjnx_cjcd;
        this.cjnx_cjyy = cjnx_cjyy;
        this.ybqk_zz = ybqk_zz;
        this.ybqk_tz = ybqk_tz;
        this.ybqk_xy = ybqk_xy;
        this.ybqk_xl = ybqk_xl;
        this.ybqk_qt = ybqk_qt;
        this.kffw_kfxm = kffw_kfxm;
        this.kffw_kfmb = kffw_kfmb;
        this.kffw_gnxl = kffw_gnxl;
        this.kffw_xldz = kffw_xldz;
        this.kffw_xlpg = kffw_xlpg;
        this.kffw_yy = kffw_yy;
        this.kffw_zjqx = kffw_zjqx;
        this.shfszd_sfxy = shfszd_sfxy;
        this.shfszd_sfxyms = shfszd_sfxyms;
        this.shfszd_sfyj = shfszd_sfyj;
        this.shfszd_sfyjms = shfszd_sfyjms;
        this.shfszd_sfyd = shfszd_sfyd;
        this.shfszd_sfydms = shfszd_sfydms;
        this.shfszd_ydxm = shfszd_ydxm;
        this.shfszd_syqk = shfszd_syqk;
        this.shfszd_xltz = shfszd_xltz;
        this.shfszd_zyxw = shfszd_zyxw;
        this.shfszd_sfpg = shfszd_sfpg;
        this.shfszd_kfjy = shfszd_kfjy;
        this.shfszd_xcsfrq = shfszd_xcsfrq;
        this.shfszd_sfysqm = shfszd_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getGrxx_sfrq() {
        return grxx_sfrq;
    }

    public void setGrxx_sfrq(String grxx_sfrq) {
        this.grxx_sfrq = grxx_sfrq;
    }

    public String getGrxx_sffs() {
        return grxx_sffs;
    }

    public void setGrxx_sffs(String grxx_sffs) {
        this.grxx_sffs = grxx_sffs;
    }

    public String getGrxx_knqt() {
        return grxx_knqt;
    }

    public void setGrxx_knqt(String grxx_knqt) {
        this.grxx_knqt = grxx_knqt;
    }

    public String getGrxx_kfxq() {
        return grxx_kfxq;
    }

    public void setGrxx_kfxq(String grxx_kfxq) {
        this.grxx_kfxq = grxx_kfxq;
    }

    public String getCjnx_cjzbh() {
        return cjnx_cjzbh;
    }

    public void setCjnx_cjzbh(String cjnx_cjzbh) {
        this.cjnx_cjzbh = cjnx_cjzbh;
    }

    public String getCjnx_zycj() {
        return cjnx_zycj;
    }

    public void setCjnx_zycj(String cjnx_zycj) {
        this.cjnx_zycj = cjnx_zycj;
    }

    public String getCjnx_dccj() {
        return cjnx_dccj;
    }

    public void setCjnx_dccj(String cjnx_dccj) {
        this.cjnx_dccj = cjnx_dccj;
    }

    public String getCjnx_cjrq() {
        return cjnx_cjrq;
    }

    public void setCjnx_cjrq(String cjnx_cjrq) {
        this.cjnx_cjrq = cjnx_cjrq;
    }

    public String getCjnx_cjcd() {
        return cjnx_cjcd;
    }

    public void setCjnx_cjcd(String cjnx_cjcd) {
        this.cjnx_cjcd = cjnx_cjcd;
    }

    public String getCjnx_cjyy() {
        return cjnx_cjyy;
    }

    public void setCjnx_cjyy(String cjnx_cjyy) {
        this.cjnx_cjyy = cjnx_cjyy;
    }

    public String getYbqk_zz() {
        return ybqk_zz;
    }

    public void setYbqk_zz(String ybqk_zz) {
        this.ybqk_zz = ybqk_zz;
    }

    public String getYbqk_tz() {
        return ybqk_tz;
    }

    public void setYbqk_tz(String ybqk_tz) {
        this.ybqk_tz = ybqk_tz;
    }

    public String getYbqk_xy() {
        return ybqk_xy;
    }

    public void setYbqk_xy(String ybqk_xy) {
        this.ybqk_xy = ybqk_xy;
    }

    public String getYbqk_xl() {
        return ybqk_xl;
    }

    public void setYbqk_xl(String ybqk_xl) {
        this.ybqk_xl = ybqk_xl;
    }

    public String getYbqk_qt() {
        return ybqk_qt;
    }

    public void setYbqk_qt(String ybqk_qt) {
        this.ybqk_qt = ybqk_qt;
    }

    public String getKffw_kfxm() {
        return kffw_kfxm;
    }

    public void setKffw_kfxm(String kffw_kfxm) {
        this.kffw_kfxm = kffw_kfxm;
    }

    public String getKffw_kfmb() {
        return kffw_kfmb;
    }

    public void setKffw_kfmb(String kffw_kfmb) {
        this.kffw_kfmb = kffw_kfmb;
    }

    public String getKffw_gnxl() {
        return kffw_gnxl;
    }

    public void setKffw_gnxl(String kffw_gnxl) {
        this.kffw_gnxl = kffw_gnxl;
    }

    public String getKffw_xldz() {
        return kffw_xldz;
    }

    public void setKffw_xldz(String kffw_xldz) {
        this.kffw_xldz = kffw_xldz;
    }

    public String getKffw_xlpg() {
        return kffw_xlpg;
    }

    public void setKffw_xlpg(String kffw_xlpg) {
        this.kffw_xlpg = kffw_xlpg;
    }

    public String getKffw_yy() {
        return kffw_yy;
    }

    public void setKffw_yy(String kffw_yy) {
        this.kffw_yy = kffw_yy;
    }

    public String getKffw_zjqx() {
        return kffw_zjqx;
    }

    public void setKffw_zjqx(String kffw_zjqx) {
        this.kffw_zjqx = kffw_zjqx;
    }

    public Boolean getShfszd_sfxy() {
        return shfszd_sfxy;
    }

    public void setShfszd_sfxy(Boolean shfszd_sfxy) {
        this.shfszd_sfxy = shfszd_sfxy;
    }

    public String getShfszd_sfxyms() {
        return shfszd_sfxyms;
    }

    public void setShfszd_sfxyms(String shfszd_sfxyms) {
        this.shfszd_sfxyms = shfszd_sfxyms;
    }

    public Boolean getShfszd_sfyj() {
        return shfszd_sfyj;
    }

    public void setShfszd_sfyj(Boolean shfszd_sfyj) {
        this.shfszd_sfyj = shfszd_sfyj;
    }

    public String getShfszd_sfyjms() {
        return shfszd_sfyjms;
    }

    public void setShfszd_sfyjms(String shfszd_sfyjms) {
        this.shfszd_sfyjms = shfszd_sfyjms;
    }

    public Boolean getShfszd_sfyd() {
        return shfszd_sfyd;
    }

    public void setShfszd_sfyd(Boolean shfszd_sfyd) {
        this.shfszd_sfyd = shfszd_sfyd;
    }

    public String getShfszd_sfydms() {
        return shfszd_sfydms;
    }

    public void setShfszd_sfydms(String shfszd_sfydms) {
        this.shfszd_sfydms = shfszd_sfydms;
    }

    public String getShfszd_ydxm() {
        return shfszd_ydxm;
    }

    public void setShfszd_ydxm(String shfszd_ydxm) {
        this.shfszd_ydxm = shfszd_ydxm;
    }

    public String getShfszd_syqk() {
        return shfszd_syqk;
    }

    public void setShfszd_syqk(String shfszd_syqk) {
        this.shfszd_syqk = shfszd_syqk;
    }

    public String getShfszd_xltz() {
        return shfszd_xltz;
    }

    public void setShfszd_xltz(String shfszd_xltz) {
        this.shfszd_xltz = shfszd_xltz;
    }

    public String getShfszd_zyxw() {
        return shfszd_zyxw;
    }

    public void setShfszd_zyxw(String shfszd_zyxw) {
        this.shfszd_zyxw = shfszd_zyxw;
    }

    public String getShfszd_sfpg() {
        return shfszd_sfpg;
    }

    public void setShfszd_sfpg(String shfszd_sfpg) {
        this.shfszd_sfpg = shfszd_sfpg;
    }

    public String getShfszd_kfjy() {
        return shfszd_kfjy;
    }

    public void setShfszd_kfjy(String shfszd_kfjy) {
        this.shfszd_kfjy = shfszd_kfjy;
    }

    public String getShfszd_xcsfrq() {
        return shfszd_xcsfrq;
    }

    public void setShfszd_xcsfrq(String shfszd_xcsfrq) {
        this.shfszd_xcsfrq = shfszd_xcsfrq;
    }

    public String getShfszd_sfysqm() {
        return shfszd_sfysqm;
    }

    public void setShfszd_sfysqm(String shfszd_sfysqm) {
        this.shfszd_sfysqm = shfszd_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
