package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_THREE_SIX_NEWBORN.
 */
public class FollowUpThreeSixNewborn {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_fsrq;
    private String grxx_nl;
    private String grxx_sjnl;
    private String grxx_zrys;
    private String tgjcqk_tz;
    private String tgjcqk_sc;
    private String tgjcqk_bmi;
    private String tgjcqk_tgfypj;
    private String tgjcqk_sl;
    private String tgjcqk_cyqcs;
    private String tgjcqk_cyqcsjl;
    private Boolean tgjcqk_sftlyc;
    private String tgjcqk_sftlycms;
    private Boolean tgjcqk_sfywgyc;
    private String tgjcqk_sfywgycms;
    private Boolean tgjcqk_sfebyc;
    private String tgjcqk_sfebycms;
    private Boolean tgjcqk_sfxftzyc;
    private String tgjcqk_sfxftzycms;
    private Boolean tgjcqk_sffbczyc;
    private String tgjcqk_sffbczycms;
    private Boolean tgjcqk_sfwszqyc;
    private String tgjcqk_sfwszqycms;
    private Boolean tgjcqk_sfggyctzyc;
    private String tgjcqk_sfggyctzycms;
    private String xhdbz;
    private String sysjc;
    private String fzjc;
    private String hbqk;
    private String hbqk_fy;
    private String hbqk_fx;
    private String hbqk_ws;
    private String hbqk_qt;
    private Boolean yyxjbgl_sfyyxjb;
    private String jbzd;
    private Boolean zz_sfzz;
    private String zz_yy;
    private String zz_jgjks;
    private String zd_zd;
    private String zd_yzhjy;
    private String zd_xcsfrq;
    private String zd_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpThreeSixNewborn() {
    }

    public FollowUpThreeSixNewborn(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    

    public FollowUpThreeSixNewborn(String followUpNo, String idcard,
			String grxx_fsrq, String grxx_nl, String grxx_sjnl,
			String grxx_zrys, String tgjcqk_tz, String tgjcqk_sc,
			String tgjcqk_bmi, String tgjcqk_tgfypj, String tgjcqk_sl,
			String tgjcqk_cyqcs, String tgjcqk_cyqcsjl, Boolean tgjcqk_sftlyc,
			String tgjcqk_sftlycms, Boolean tgjcqk_sfywgyc,
			String tgjcqk_sfywgycms, Boolean tgjcqk_sfebyc,
			String tgjcqk_sfebycms, Boolean tgjcqk_sfxftzyc,
			String tgjcqk_sfxftzycms, Boolean tgjcqk_sffbczyc,
			String tgjcqk_sffbczycms, Boolean tgjcqk_sfwszqyc,
			String tgjcqk_sfwszqycms, Boolean tgjcqk_sfggyctzyc,
			String tgjcqk_sfggyctzycms, String xhdbz, String sysjc,
			String fzjc, String hbqk, String hbqk_fy, String hbqk_fx,
			String hbqk_ws, String hbqk_qt, Boolean yyxjbgl_sfyyxjb,
			String jbzd, Boolean zz_sfzz, String zz_yy, String zz_jgjks,
			String zd_zd, String zd_yzhjy, String zd_xcsfrq, String zd_sfysqm,
			String createTime, String updateTime) {
		super();
		this.followUpNo = followUpNo;
		this.idcard = idcard;
		this.grxx_fsrq = grxx_fsrq;
		this.grxx_nl = grxx_nl;
		this.grxx_sjnl = grxx_sjnl;
		this.grxx_zrys = grxx_zrys;
		this.tgjcqk_tz = tgjcqk_tz;
		this.tgjcqk_sc = tgjcqk_sc;
		this.tgjcqk_bmi = tgjcqk_bmi;
		this.tgjcqk_tgfypj = tgjcqk_tgfypj;
		this.tgjcqk_sl = tgjcqk_sl;
		this.tgjcqk_cyqcs = tgjcqk_cyqcs;
		this.tgjcqk_cyqcsjl = tgjcqk_cyqcsjl;
		this.tgjcqk_sftlyc = tgjcqk_sftlyc;
		this.tgjcqk_sftlycms = tgjcqk_sftlycms;
		this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
		this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
		this.tgjcqk_sfebyc = tgjcqk_sfebyc;
		this.tgjcqk_sfebycms = tgjcqk_sfebycms;
		this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
		this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
		this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
		this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
		this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
		this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
		this.tgjcqk_sfggyctzyc = tgjcqk_sfggyctzyc;
		this.tgjcqk_sfggyctzycms = tgjcqk_sfggyctzycms;
		this.xhdbz = xhdbz;
		this.sysjc = sysjc;
		this.fzjc = fzjc;
		this.hbqk = hbqk;
		this.hbqk_fy = hbqk_fy;
		this.hbqk_fx = hbqk_fx;
		this.hbqk_ws = hbqk_ws;
		this.hbqk_qt = hbqk_qt;
		this.yyxjbgl_sfyyxjb = yyxjbgl_sfyyxjb;
		this.jbzd = jbzd;
		this.zz_sfzz = zz_sfzz;
		this.zz_yy = zz_yy;
		this.zz_jgjks = zz_jgjks;
		this.zd_zd = zd_zd;
		this.zd_yzhjy = zd_yzhjy;
		this.zd_xcsfrq = zd_xcsfrq;
		this.zd_sfysqm = zd_sfysqm;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	/** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_fsrq() {
        return grxx_fsrq;
    }

    public void setGrxx_fsrq(String grxx_fsrq) {
        this.grxx_fsrq = grxx_fsrq;
    }

    public String getGrxx_nl() {
        return grxx_nl;
    }

    public void setGrxx_nl(String grxx_nl) {
        this.grxx_nl = grxx_nl;
    }

    public String getGrxx_sjnl() {
        return grxx_sjnl;
    }

    public void setGrxx_sjnl(String grxx_sjnl) {
        this.grxx_sjnl = grxx_sjnl;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getTgjcqk_tz() {
        return tgjcqk_tz;
    }

    public void setTgjcqk_tz(String tgjcqk_tz) {
        this.tgjcqk_tz = tgjcqk_tz;
    }

    public String getTgjcqk_sc() {
        return tgjcqk_sc;
    }

    public void setTgjcqk_sc(String tgjcqk_sc) {
        this.tgjcqk_sc = tgjcqk_sc;
    }

    public String getTgjcqk_bmi() {
        return tgjcqk_bmi;
    }

    public void setTgjcqk_bmi(String tgjcqk_bmi) {
        this.tgjcqk_bmi = tgjcqk_bmi;
    }

    public String getTgjcqk_tgfypj() {
        return tgjcqk_tgfypj;
    }

    public void setTgjcqk_tgfypj(String tgjcqk_tgfypj) {
        this.tgjcqk_tgfypj = tgjcqk_tgfypj;
    }

    public String getTgjcqk_sl() {
        return tgjcqk_sl;
    }

    public void setTgjcqk_sl(String tgjcqk_sl) {
        this.tgjcqk_sl = tgjcqk_sl;
    }

    public String getTgjcqk_cyqcs() {
        return tgjcqk_cyqcs;
    }

    public void setTgjcqk_cyqcs(String tgjcqk_cyqcs) {
        this.tgjcqk_cyqcs = tgjcqk_cyqcs;
    }

    public String getTgjcqk_cyqcsjl() {
        return tgjcqk_cyqcsjl;
    }

    public void setTgjcqk_cyqcsjl(String tgjcqk_cyqcsjl) {
        this.tgjcqk_cyqcsjl = tgjcqk_cyqcsjl;
    }

    public Boolean getTgjcqk_sftlyc() {
        return tgjcqk_sftlyc;
    }

    public void setTgjcqk_sftlyc(Boolean tgjcqk_sftlyc) {
        this.tgjcqk_sftlyc = tgjcqk_sftlyc;
    }

    public String getTgjcqk_sftlycms() {
        return tgjcqk_sftlycms;
    }

    public void setTgjcqk_sftlycms(String tgjcqk_sftlycms) {
        this.tgjcqk_sftlycms = tgjcqk_sftlycms;
    }

    public Boolean getTgjcqk_sfywgyc() {
        return tgjcqk_sfywgyc;
    }

    public void setTgjcqk_sfywgyc(Boolean tgjcqk_sfywgyc) {
        this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
    }

    public String getTgjcqk_sfywgycms() {
        return tgjcqk_sfywgycms;
    }

    public void setTgjcqk_sfywgycms(String tgjcqk_sfywgycms) {
        this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
    }

    public Boolean getTgjcqk_sfebyc() {
        return tgjcqk_sfebyc;
    }

    public void setTgjcqk_sfebyc(Boolean tgjcqk_sfebyc) {
        this.tgjcqk_sfebyc = tgjcqk_sfebyc;
    }

    public String getTgjcqk_sfebycms() {
        return tgjcqk_sfebycms;
    }

    public void setTgjcqk_sfebycms(String tgjcqk_sfebycms) {
        this.tgjcqk_sfebycms = tgjcqk_sfebycms;
    }

    public Boolean getTgjcqk_sfxftzyc() {
        return tgjcqk_sfxftzyc;
    }

    public void setTgjcqk_sfxftzyc(Boolean tgjcqk_sfxftzyc) {
        this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
    }

    public String getTgjcqk_sfxftzycms() {
        return tgjcqk_sfxftzycms;
    }

    public void setTgjcqk_sfxftzycms(String tgjcqk_sfxftzycms) {
        this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
    }

    public Boolean getTgjcqk_sffbczyc() {
        return tgjcqk_sffbczyc;
    }

    public void setTgjcqk_sffbczyc(Boolean tgjcqk_sffbczyc) {
        this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
    }

    public String getTgjcqk_sffbczycms() {
        return tgjcqk_sffbczycms;
    }

    public void setTgjcqk_sffbczycms(String tgjcqk_sffbczycms) {
        this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
    }

    public Boolean getTgjcqk_sfwszqyc() {
        return tgjcqk_sfwszqyc;
    }

    public void setTgjcqk_sfwszqyc(Boolean tgjcqk_sfwszqyc) {
        this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
    }

    public String getTgjcqk_sfwszqycms() {
        return tgjcqk_sfwszqycms;
    }

    public void setTgjcqk_sfwszqycms(String tgjcqk_sfwszqycms) {
        this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
    }

    public Boolean getTgjcqk_sfggyctzyc() {
        return tgjcqk_sfggyctzyc;
    }

    public void setTgjcqk_sfggyctzyc(Boolean tgjcqk_sfggyctzyc) {
        this.tgjcqk_sfggyctzyc = tgjcqk_sfggyctzyc;
    }

    public String getTgjcqk_sfggyctzycms() {
        return tgjcqk_sfggyctzycms;
    }

    public void setTgjcqk_sfggyctzycms(String tgjcqk_sfggyctzycms) {
        this.tgjcqk_sfggyctzycms = tgjcqk_sfggyctzycms;
    }

    public String getXhdbz() {
        return xhdbz;
    }

    public void setXhdbz(String xhdbz) {
        this.xhdbz = xhdbz;
    }

    public String getSysjc() {
        return sysjc;
    }

    public void setSysjc(String sysjc) {
        this.sysjc = sysjc;
    }

    public String getFzjc() {
        return fzjc;
    }

    public void setFzjc(String fzjc) {
        this.fzjc = fzjc;
    }

    public String getHbqk() {
        return hbqk;
    }

    public void setHbqk(String hbqk) {
        this.hbqk = hbqk;
    }

    public String getHbqk_fy() {
		return hbqk_fy;
	}

	public void setHbqk_fy(String hbqk_fy) {
		this.hbqk_fy = hbqk_fy;
	}

	public String getHbqk_fx() {
		return hbqk_fx;
	}

	public void setHbqk_fx(String hbqk_fx) {
		this.hbqk_fx = hbqk_fx;
	}

	public String getHbqk_ws() {
		return hbqk_ws;
	}

	public void setHbqk_ws(String hbqk_ws) {
		this.hbqk_ws = hbqk_ws;
	}

	public String getHbqk_qt() {
		return hbqk_qt;
	}

	public void setHbqk_qt(String hbqk_qt) {
		this.hbqk_qt = hbqk_qt;
	}

	public Boolean getYyxjbgl_sfyyxjb() {
        return yyxjbgl_sfyyxjb;
    }

    public void setYyxjbgl_sfyyxjb(Boolean yyxjbgl_sfyyxjb) {
        this.yyxjbgl_sfyyxjb = yyxjbgl_sfyyxjb;
    }

    public String getJbzd() {
        return jbzd;
    }

    public void setJbzd(String jbzd) {
        this.jbzd = jbzd;
    }

    public Boolean getZz_sfzz() {
        return zz_sfzz;
    }

    public void setZz_sfzz(Boolean zz_sfzz) {
        this.zz_sfzz = zz_sfzz;
    }

    public String getZz_yy() {
        return zz_yy;
    }

    public void setZz_yy(String zz_yy) {
        this.zz_yy = zz_yy;
    }

    public String getZz_jgjks() {
        return zz_jgjks;
    }

    public void setZz_jgjks(String zz_jgjks) {
        this.zz_jgjks = zz_jgjks;
    }

    public String getZd_zd() {
        return zd_zd;
    }

    public void setZd_zd(String zd_zd) {
        this.zd_zd = zd_zd;
    }

    public String getZd_yzhjy() {
        return zd_yzhjy;
    }

    public void setZd_yzhjy(String zd_yzhjy) {
        this.zd_yzhjy = zd_yzhjy;
    }

    public String getZd_xcsfrq() {
        return zd_xcsfrq;
    }

    public void setZd_xcsfrq(String zd_xcsfrq) {
        this.zd_xcsfrq = zd_xcsfrq;
    }

    public String getZd_sfysqm() {
        return zd_sfysqm;
    }

    public void setZd_sfysqm(String zd_sfysqm) {
        this.zd_sfysqm = zd_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
