package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_FIRST_PREGNANCY.
 */
public class FollowUpFirstPregnancy {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_tbrq;
    private String grxx_yz;
    private String grxx_yc;
    private String grxx_ydfmcs;
    private String grxx_pgccs;
    private Boolean grxx_sfmcyj;
    private String grxx_sfmcyjms;
    private String grxx_ycq;
    private String poxx_zfxm;
    private String poxx_zfnl;
    private String poxx_zfdh;
    private String tz_sg;
    private String tz_tz;
    private String tz_tzzs;
    private String tz_xy;
    private String jws;
    private String jzslb;
    private String jzszl;
    private String grs;
    private Boolean fksss_sfygss;
    private String fksss_sfygssms;
    private String ycs_ycs;
    private Boolean tingz_sfxzyc;
    private String tingz_sfxzycms;
    private Boolean tingz_sffbyc;
    private String tingz_sffbycms;
    private Boolean fkjc_sfwyyc;
    private String tingz_sfwyycms;
    private Boolean fkjc_sfydyc;
    private String tingz_sfydycms;
    private Boolean fkjc_sfgjyc;
    private String tingz_sfgjycms;
    private Boolean fkjc_sfzgyc;
    private String tingz_sfzgycms;
    private Boolean fkjc_sffjyc;
    private String tingz_sffjycms;
    private String fzjc_xhdbz;
    private String fzjc_bxbjsz;
    private String fzjc_xxbjsz;
    private String fzjc_xcgqt;
    private String fzjc_ndb;
    private String fzjc_nt;
    private String fzjc_ntt;
    private String fzjc_nqx;
    private String fzjc_ncgqt;
    private String fzjc_xqgbzam;
    private String fzjc_bdb;
    private String fzjc_zdhs;
    private String fzjc_jhdhs;
    private Boolean fzjc_sfydfmwyc;
    private String fzjc_sfydfmwycms;
    private String fzjc_mdxqxsy;
    private String fzjc_HIVktjc;
    private Boolean ztpg_sfztpgyc;
    private String ztpg_sfztpgycms;
    private Boolean zz_sfygzz;
    private String zz_yy;
    private String zz_jgjks;
    private String zz_xcsfrq;
    private String ztpg_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpFirstPregnancy() {
    }

    public FollowUpFirstPregnancy(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpFirstPregnancy(String followUpNo, String idcard, String grxx_tbrq, String grxx_yz, String grxx_yc, String grxx_ydfmcs, String grxx_pgccs, Boolean grxx_sfmcyj, String grxx_sfmcyjms, String grxx_ycq, String poxx_zfxm, String poxx_zfnl, String poxx_zfdh, String tz_sg, String tz_tz, String tz_tzzs, String tz_xy, String jws, String jzslb, String jzszl, String grs, Boolean fksss_sfygss, String fksss_sfygssms, String ycs_ycs, Boolean tingz_sfxzyc, String tingz_sfxzycms, Boolean tingz_sffbyc, String tingz_sffbycms, Boolean fkjc_sfwyyc, String tingz_sfwyycms, Boolean fkjc_sfydyc, String tingz_sfydycms, Boolean fkjc_sfgjyc, String tingz_sfgjycms, Boolean fkjc_sfzgyc, String tingz_sfzgycms, Boolean fkjc_sffjyc, String tingz_sffjycms, String fzjc_xhdbz, String fzjc_bxbjsz, String fzjc_xxbjsz, String fzjc_xcgqt, String fzjc_ndb, String fzjc_nt, String fzjc_ntt, String fzjc_nqx, String fzjc_ncgqt, String fzjc_xqgbzam, String fzjc_bdb, String fzjc_zdhs, String fzjc_jhdhs, Boolean fzjc_sfydfmwyc, String fzjc_sfydfmwycms, String fzjc_mdxqxsy, String fzjc_HIVktjc, Boolean ztpg_sfztpgyc, String ztpg_sfztpgycms, Boolean zz_sfygzz, String zz_yy, String zz_jgjks, String zz_xcsfrq, String ztpg_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_tbrq = grxx_tbrq;
        this.grxx_yz = grxx_yz;
        this.grxx_yc = grxx_yc;
        this.grxx_ydfmcs = grxx_ydfmcs;
        this.grxx_pgccs = grxx_pgccs;
        this.grxx_sfmcyj = grxx_sfmcyj;
        this.grxx_sfmcyjms = grxx_sfmcyjms;
        this.grxx_ycq = grxx_ycq;
        this.poxx_zfxm = poxx_zfxm;
        this.poxx_zfnl = poxx_zfnl;
        this.poxx_zfdh = poxx_zfdh;
        this.tz_sg = tz_sg;
        this.tz_tz = tz_tz;
        this.tz_tzzs = tz_tzzs;
        this.tz_xy = tz_xy;
        this.jws = jws;
        this.jzslb = jzslb;
        this.jzszl = jzszl;
        this.grs = grs;
        this.fksss_sfygss = fksss_sfygss;
        this.fksss_sfygssms = fksss_sfygssms;
        this.ycs_ycs = ycs_ycs;
        this.tingz_sfxzyc = tingz_sfxzyc;
        this.tingz_sfxzycms = tingz_sfxzycms;
        this.tingz_sffbyc = tingz_sffbyc;
        this.tingz_sffbycms = tingz_sffbycms;
        this.fkjc_sfwyyc = fkjc_sfwyyc;
        this.tingz_sfwyycms = tingz_sfwyycms;
        this.fkjc_sfydyc = fkjc_sfydyc;
        this.tingz_sfydycms = tingz_sfydycms;
        this.fkjc_sfgjyc = fkjc_sfgjyc;
        this.tingz_sfgjycms = tingz_sfgjycms;
        this.fkjc_sfzgyc = fkjc_sfzgyc;
        this.tingz_sfzgycms = tingz_sfzgycms;
        this.fkjc_sffjyc = fkjc_sffjyc;
        this.tingz_sffjycms = tingz_sffjycms;
        this.fzjc_xhdbz = fzjc_xhdbz;
        this.fzjc_bxbjsz = fzjc_bxbjsz;
        this.fzjc_xxbjsz = fzjc_xxbjsz;
        this.fzjc_xcgqt = fzjc_xcgqt;
        this.fzjc_ndb = fzjc_ndb;
        this.fzjc_nt = fzjc_nt;
        this.fzjc_ntt = fzjc_ntt;
        this.fzjc_nqx = fzjc_nqx;
        this.fzjc_ncgqt = fzjc_ncgqt;
        this.fzjc_xqgbzam = fzjc_xqgbzam;
        this.fzjc_bdb = fzjc_bdb;
        this.fzjc_zdhs = fzjc_zdhs;
        this.fzjc_jhdhs = fzjc_jhdhs;
        this.fzjc_sfydfmwyc = fzjc_sfydfmwyc;
        this.fzjc_sfydfmwycms = fzjc_sfydfmwycms;
        this.fzjc_mdxqxsy = fzjc_mdxqxsy;
        this.fzjc_HIVktjc = fzjc_HIVktjc;
        this.ztpg_sfztpgyc = ztpg_sfztpgyc;
        this.ztpg_sfztpgycms = ztpg_sfztpgycms;
        this.zz_sfygzz = zz_sfygzz;
        this.zz_yy = zz_yy;
        this.zz_jgjks = zz_jgjks;
        this.zz_xcsfrq = zz_xcsfrq;
        this.ztpg_sfysqm = ztpg_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_tbrq() {
        return grxx_tbrq;
    }

    public void setGrxx_tbrq(String grxx_tbrq) {
        this.grxx_tbrq = grxx_tbrq;
    }

    public String getGrxx_yz() {
        return grxx_yz;
    }

    public void setGrxx_yz(String grxx_yz) {
        this.grxx_yz = grxx_yz;
    }

    public String getGrxx_yc() {
        return grxx_yc;
    }

    public void setGrxx_yc(String grxx_yc) {
        this.grxx_yc = grxx_yc;
    }

    public String getGrxx_ydfmcs() {
        return grxx_ydfmcs;
    }

    public void setGrxx_ydfmcs(String grxx_ydfmcs) {
        this.grxx_ydfmcs = grxx_ydfmcs;
    }

    public String getGrxx_pgccs() {
        return grxx_pgccs;
    }

    public void setGrxx_pgccs(String grxx_pgccs) {
        this.grxx_pgccs = grxx_pgccs;
    }

    public Boolean getGrxx_sfmcyj() {
        return grxx_sfmcyj;
    }

    public void setGrxx_sfmcyj(Boolean grxx_sfmcyj) {
        this.grxx_sfmcyj = grxx_sfmcyj;
    }

    public String getGrxx_sfmcyjms() {
        return grxx_sfmcyjms;
    }

    public void setGrxx_sfmcyjms(String grxx_sfmcyjms) {
        this.grxx_sfmcyjms = grxx_sfmcyjms;
    }

    public String getGrxx_ycq() {
        return grxx_ycq;
    }

    public void setGrxx_ycq(String grxx_ycq) {
        this.grxx_ycq = grxx_ycq;
    }

    public String getPoxx_zfxm() {
        return poxx_zfxm;
    }

    public void setPoxx_zfxm(String poxx_zfxm) {
        this.poxx_zfxm = poxx_zfxm;
    }

    public String getPoxx_zfnl() {
        return poxx_zfnl;
    }

    public void setPoxx_zfnl(String poxx_zfnl) {
        this.poxx_zfnl = poxx_zfnl;
    }

    public String getPoxx_zfdh() {
        return poxx_zfdh;
    }

    public void setPoxx_zfdh(String poxx_zfdh) {
        this.poxx_zfdh = poxx_zfdh;
    }

    public String getTz_sg() {
        return tz_sg;
    }

    public void setTz_sg(String tz_sg) {
        this.tz_sg = tz_sg;
    }

    public String getTz_tz() {
        return tz_tz;
    }

    public void setTz_tz(String tz_tz) {
        this.tz_tz = tz_tz;
    }

    public String getTz_tzzs() {
        return tz_tzzs;
    }

    public void setTz_tzzs(String tz_tzzs) {
        this.tz_tzzs = tz_tzzs;
    }

    public String getTz_xy() {
        return tz_xy;
    }

    public void setTz_xy(String tz_xy) {
        this.tz_xy = tz_xy;
    }

    public String getJws() {
        return jws;
    }

    public void setJws(String jws) {
        this.jws = jws;
    }

    public String getJzslb() {
        return jzslb;
    }

    public void setJzslb(String jzslb) {
        this.jzslb = jzslb;
    }

    public String getJzszl() {
        return jzszl;
    }

    public void setJzszl(String jzszl) {
        this.jzszl = jzszl;
    }

    public String getGrs() {
        return grs;
    }

    public void setGrs(String grs) {
        this.grs = grs;
    }

    public Boolean getFksss_sfygss() {
        return fksss_sfygss;
    }

    public void setFksss_sfygss(Boolean fksss_sfygss) {
        this.fksss_sfygss = fksss_sfygss;
    }

    public String getFksss_sfygssms() {
        return fksss_sfygssms;
    }

    public void setFksss_sfygssms(String fksss_sfygssms) {
        this.fksss_sfygssms = fksss_sfygssms;
    }

    public String getYcs_ycs() {
        return ycs_ycs;
    }

    public void setYcs_ycs(String ycs_ycs) {
        this.ycs_ycs = ycs_ycs;
    }

    public Boolean getTingz_sfxzyc() {
        return tingz_sfxzyc;
    }

    public void setTingz_sfxzyc(Boolean tingz_sfxzyc) {
        this.tingz_sfxzyc = tingz_sfxzyc;
    }

    public String getTingz_sfxzycms() {
        return tingz_sfxzycms;
    }

    public void setTingz_sfxzycms(String tingz_sfxzycms) {
        this.tingz_sfxzycms = tingz_sfxzycms;
    }

    public Boolean getTingz_sffbyc() {
        return tingz_sffbyc;
    }

    public void setTingz_sffbyc(Boolean tingz_sffbyc) {
        this.tingz_sffbyc = tingz_sffbyc;
    }

    public String getTingz_sffbycms() {
        return tingz_sffbycms;
    }

    public void setTingz_sffbycms(String tingz_sffbycms) {
        this.tingz_sffbycms = tingz_sffbycms;
    }

    public Boolean getFkjc_sfwyyc() {
        return fkjc_sfwyyc;
    }

    public void setFkjc_sfwyyc(Boolean fkjc_sfwyyc) {
        this.fkjc_sfwyyc = fkjc_sfwyyc;
    }

    public String getTingz_sfwyycms() {
        return tingz_sfwyycms;
    }

    public void setTingz_sfwyycms(String tingz_sfwyycms) {
        this.tingz_sfwyycms = tingz_sfwyycms;
    }

    public Boolean getFkjc_sfydyc() {
        return fkjc_sfydyc;
    }

    public void setFkjc_sfydyc(Boolean fkjc_sfydyc) {
        this.fkjc_sfydyc = fkjc_sfydyc;
    }

    public String getTingz_sfydycms() {
        return tingz_sfydycms;
    }

    public void setTingz_sfydycms(String tingz_sfydycms) {
        this.tingz_sfydycms = tingz_sfydycms;
    }

    public Boolean getFkjc_sfgjyc() {
        return fkjc_sfgjyc;
    }

    public void setFkjc_sfgjyc(Boolean fkjc_sfgjyc) {
        this.fkjc_sfgjyc = fkjc_sfgjyc;
    }

    public String getTingz_sfgjycms() {
        return tingz_sfgjycms;
    }

    public void setTingz_sfgjycms(String tingz_sfgjycms) {
        this.tingz_sfgjycms = tingz_sfgjycms;
    }

    public Boolean getFkjc_sfzgyc() {
        return fkjc_sfzgyc;
    }

    public void setFkjc_sfzgyc(Boolean fkjc_sfzgyc) {
        this.fkjc_sfzgyc = fkjc_sfzgyc;
    }

    public String getTingz_sfzgycms() {
        return tingz_sfzgycms;
    }

    public void setTingz_sfzgycms(String tingz_sfzgycms) {
        this.tingz_sfzgycms = tingz_sfzgycms;
    }

    public Boolean getFkjc_sffjyc() {
        return fkjc_sffjyc;
    }

    public void setFkjc_sffjyc(Boolean fkjc_sffjyc) {
        this.fkjc_sffjyc = fkjc_sffjyc;
    }

    public String getTingz_sffjycms() {
        return tingz_sffjycms;
    }

    public void setTingz_sffjycms(String tingz_sffjycms) {
        this.tingz_sffjycms = tingz_sffjycms;
    }

    public String getFzjc_xhdbz() {
        return fzjc_xhdbz;
    }

    public void setFzjc_xhdbz(String fzjc_xhdbz) {
        this.fzjc_xhdbz = fzjc_xhdbz;
    }

    public String getFzjc_bxbjsz() {
        return fzjc_bxbjsz;
    }

    public void setFzjc_bxbjsz(String fzjc_bxbjsz) {
        this.fzjc_bxbjsz = fzjc_bxbjsz;
    }

    public String getFzjc_xxbjsz() {
        return fzjc_xxbjsz;
    }

    public void setFzjc_xxbjsz(String fzjc_xxbjsz) {
        this.fzjc_xxbjsz = fzjc_xxbjsz;
    }

    public String getFzjc_xcgqt() {
        return fzjc_xcgqt;
    }

    public void setFzjc_xcgqt(String fzjc_xcgqt) {
        this.fzjc_xcgqt = fzjc_xcgqt;
    }

    public String getFzjc_ndb() {
        return fzjc_ndb;
    }

    public void setFzjc_ndb(String fzjc_ndb) {
        this.fzjc_ndb = fzjc_ndb;
    }

    public String getFzjc_nt() {
        return fzjc_nt;
    }

    public void setFzjc_nt(String fzjc_nt) {
        this.fzjc_nt = fzjc_nt;
    }

    public String getFzjc_ntt() {
        return fzjc_ntt;
    }

    public void setFzjc_ntt(String fzjc_ntt) {
        this.fzjc_ntt = fzjc_ntt;
    }

    public String getFzjc_nqx() {
        return fzjc_nqx;
    }

    public void setFzjc_nqx(String fzjc_nqx) {
        this.fzjc_nqx = fzjc_nqx;
    }

    public String getFzjc_ncgqt() {
        return fzjc_ncgqt;
    }

    public void setFzjc_ncgqt(String fzjc_ncgqt) {
        this.fzjc_ncgqt = fzjc_ncgqt;
    }

    public String getFzjc_xqgbzam() {
        return fzjc_xqgbzam;
    }

    public void setFzjc_xqgbzam(String fzjc_xqgbzam) {
        this.fzjc_xqgbzam = fzjc_xqgbzam;
    }

    public String getFzjc_bdb() {
        return fzjc_bdb;
    }

    public void setFzjc_bdb(String fzjc_bdb) {
        this.fzjc_bdb = fzjc_bdb;
    }

    public String getFzjc_zdhs() {
        return fzjc_zdhs;
    }

    public void setFzjc_zdhs(String fzjc_zdhs) {
        this.fzjc_zdhs = fzjc_zdhs;
    }

    public String getFzjc_jhdhs() {
        return fzjc_jhdhs;
    }

    public void setFzjc_jhdhs(String fzjc_jhdhs) {
        this.fzjc_jhdhs = fzjc_jhdhs;
    }

    public Boolean getFzjc_sfydfmwyc() {
        return fzjc_sfydfmwyc;
    }

    public void setFzjc_sfydfmwyc(Boolean fzjc_sfydfmwyc) {
        this.fzjc_sfydfmwyc = fzjc_sfydfmwyc;
    }

    public String getFzjc_sfydfmwycms() {
        return fzjc_sfydfmwycms;
    }

    public void setFzjc_sfydfmwycms(String fzjc_sfydfmwycms) {
        this.fzjc_sfydfmwycms = fzjc_sfydfmwycms;
    }

    public String getFzjc_mdxqxsy() {
        return fzjc_mdxqxsy;
    }

    public void setFzjc_mdxqxsy(String fzjc_mdxqxsy) {
        this.fzjc_mdxqxsy = fzjc_mdxqxsy;
    }

    public String getFzjc_HIVktjc() {
        return fzjc_HIVktjc;
    }

    public void setFzjc_HIVktjc(String fzjc_HIVktjc) {
        this.fzjc_HIVktjc = fzjc_HIVktjc;
    }

    public Boolean getZtpg_sfztpgyc() {
        return ztpg_sfztpgyc;
    }

    public void setZtpg_sfztpgyc(Boolean ztpg_sfztpgyc) {
        this.ztpg_sfztpgyc = ztpg_sfztpgyc;
    }

    public String getZtpg_sfztpgycms() {
        return ztpg_sfztpgycms;
    }

    public void setZtpg_sfztpgycms(String ztpg_sfztpgycms) {
        this.ztpg_sfztpgycms = ztpg_sfztpgycms;
    }

    public Boolean getZz_sfygzz() {
        return zz_sfygzz;
    }

    public void setZz_sfygzz(Boolean zz_sfygzz) {
        this.zz_sfygzz = zz_sfygzz;
    }

    public String getZz_yy() {
        return zz_yy;
    }

    public void setZz_yy(String zz_yy) {
        this.zz_yy = zz_yy;
    }

    public String getZz_jgjks() {
        return zz_jgjks;
    }

    public void setZz_jgjks(String zz_jgjks) {
        this.zz_jgjks = zz_jgjks;
    }

    public String getZz_xcsfrq() {
        return zz_xcsfrq;
    }

    public void setZz_xcsfrq(String zz_xcsfrq) {
        this.zz_xcsfrq = zz_xcsfrq;
    }

    public String getZtpg_sfysqm() {
        return ztpg_sfysqm;
    }

    public void setZtpg_sfysqm(String ztpg_sfysqm) {
        this.ztpg_sfysqm = ztpg_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
