package com.shbestwin.followupmanager.model.followup;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOLLOW_UP_NEWBORN.
 */
public class FollowUpNewborn {

    /** Not-null value. */
    private String followUpNo;
    /** Not-null value. */
    private String idcard;
    private String grxx_fsrq;
    private String grxx_fscs;
    private String grxx_csrl;
    private String grxx_zrys;
    private String wyqk_wyfs;
    private String wyqk_cnl;
    private String wyqk_cncs;
    private Boolean wyqk_sfot;
    private String jbstzk_dbxz;
    private String jbstzk_dbcs;
    private String jbstzk_dbys;
    private String jbstzk_smwt;
    private Boolean gwe_sfgwe;
    private String tgjcqk_mqtz;
    private String tgjcqk_tw;
    private String tgjcqk_sc;
    private String tgjcqk_hxpl;
    private String tgjcqk_ml;
    private String tgjcqk_ms;
    private String tgjcqk_hdbw;
    private String tgjcqk_qx;
    private String tgjcqk_qxjl;
    private Boolean tgjcqk_sfywgyc;
    private String tgjcqk_sfywgycms;
    private Boolean tgjcqk_sfewgyc;
    private String tgjcqk_sfewgycms;
    private Boolean tgjcqk_sfbyc;
    private String tgjcqk_sfbycms;
    private Boolean tgjcqk_sfkqyc;
    private String tgjcqk_sfkqycms;
    private Boolean tgjcqk_sfxftzyc;
    private String tgjcqk_sfxftzycms;
    private Boolean tgjcqk_sffbczyc;
    private String tgjcqk_sffbczycms;
    private Boolean tgjcqk_sfszhddyc;
    private String tgjcqk_sfszhddycms;
    private Boolean tgjcqk_sfjbbkyc;
    private String tgjcqk_sfjbbkycms;
    private String tgjcqk_pf;
    private Boolean tgjcqk_sfgmyc;
    private String tgjcqk_sfgmycms;
    private Boolean tgjcqk_sfwszqyc;
    private String tgjcqk_sfwszqycms;
    private Boolean tgjcqk_sfjzyc;
    private String tgjcqk_sfjzycms;
    private Boolean tgjcqk_sfqdyc;
    private String tgjcqk_sfqdycms;
    private Boolean zzjy_sfzz;
    private String zzjy_yy;
    private String zzjy_jgjks;
    private String zd_zdmc;
    private String zd_tsyzjcl;
    private String zd_xcsfrq;
    private String zd_xcfsdd;
    private String zd_sfysqm;
    private String createTime;
    private String updateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FollowUpNewborn() {
    }

    public FollowUpNewborn(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    public FollowUpNewborn(String followUpNo, String idcard, String grxx_fsrq, String grxx_fscs, String grxx_csrl, String grxx_zrys, String wyqk_wyfs, String wyqk_cnl, String wyqk_cncs, Boolean wyqk_sfot, String jbstzk_dbxz, String jbstzk_dbcs, String jbstzk_dbys, String jbstzk_smwt, Boolean gwe_sfgwe, String tgjcqk_mqtz, String tgjcqk_tw, String tgjcqk_sc, String tgjcqk_hxpl, String tgjcqk_ml, String tgjcqk_ms, String tgjcqk_hdbw, String tgjcqk_qx, String tgjcqk_qxjl, Boolean tgjcqk_sfywgyc, String tgjcqk_sfywgycms, Boolean tgjcqk_sfewgyc, String tgjcqk_sfewgycms, Boolean tgjcqk_sfbyc, String tgjcqk_sfbycms, Boolean tgjcqk_sfkqyc, String tgjcqk_sfkqycms, Boolean tgjcqk_sfxftzyc, String tgjcqk_sfxftzycms, Boolean tgjcqk_sffbczyc, String tgjcqk_sffbczycms, Boolean tgjcqk_sfszhddyc, String tgjcqk_sfszhddycms, Boolean tgjcqk_sfjbbkyc, String tgjcqk_sfjbbkycms, String tgjcqk_pf, Boolean tgjcqk_sfgmyc, String tgjcqk_sfgmycms, Boolean tgjcqk_sfwszqyc, String tgjcqk_sfwszqycms, Boolean tgjcqk_sfjzyc, String tgjcqk_sfjzycms, Boolean tgjcqk_sfqdyc, String tgjcqk_sfqdycms, Boolean zzjy_sfzz, String zzjy_yy, String zzjy_jgjks, String zd_zdmc, String zd_tsyzjcl, String zd_xcsfrq, String zd_xcfsdd, String zd_sfysqm, String createTime, String updateTime) {
        this.followUpNo = followUpNo;
        this.idcard = idcard;
        this.grxx_fsrq = grxx_fsrq;
        this.grxx_fscs = grxx_fscs;
        this.grxx_csrl = grxx_csrl;
        this.grxx_zrys = grxx_zrys;
        this.wyqk_wyfs = wyqk_wyfs;
        this.wyqk_cnl = wyqk_cnl;
        this.wyqk_cncs = wyqk_cncs;
        this.wyqk_sfot = wyqk_sfot;
        this.jbstzk_dbxz = jbstzk_dbxz;
        this.jbstzk_dbcs = jbstzk_dbcs;
        this.jbstzk_dbys = jbstzk_dbys;
        this.jbstzk_smwt = jbstzk_smwt;
        this.gwe_sfgwe = gwe_sfgwe;
        this.tgjcqk_mqtz = tgjcqk_mqtz;
        this.tgjcqk_tw = tgjcqk_tw;
        this.tgjcqk_sc = tgjcqk_sc;
        this.tgjcqk_hxpl = tgjcqk_hxpl;
        this.tgjcqk_ml = tgjcqk_ml;
        this.tgjcqk_ms = tgjcqk_ms;
        this.tgjcqk_hdbw = tgjcqk_hdbw;
        this.tgjcqk_qx = tgjcqk_qx;
        this.tgjcqk_qxjl = tgjcqk_qxjl;
        this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
        this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
        this.tgjcqk_sfewgyc = tgjcqk_sfewgyc;
        this.tgjcqk_sfewgycms = tgjcqk_sfewgycms;
        this.tgjcqk_sfbyc = tgjcqk_sfbyc;
        this.tgjcqk_sfbycms = tgjcqk_sfbycms;
        this.tgjcqk_sfkqyc = tgjcqk_sfkqyc;
        this.tgjcqk_sfkqycms = tgjcqk_sfkqycms;
        this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
        this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
        this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
        this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
        this.tgjcqk_sfszhddyc = tgjcqk_sfszhddyc;
        this.tgjcqk_sfszhddycms = tgjcqk_sfszhddycms;
        this.tgjcqk_sfjbbkyc = tgjcqk_sfjbbkyc;
        this.tgjcqk_sfjbbkycms = tgjcqk_sfjbbkycms;
        this.tgjcqk_pf = tgjcqk_pf;
        this.tgjcqk_sfgmyc = tgjcqk_sfgmyc;
        this.tgjcqk_sfgmycms = tgjcqk_sfgmycms;
        this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
        this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
        this.tgjcqk_sfjzyc = tgjcqk_sfjzyc;
        this.tgjcqk_sfjzycms = tgjcqk_sfjzycms;
        this.tgjcqk_sfqdyc = tgjcqk_sfqdyc;
        this.tgjcqk_sfqdycms = tgjcqk_sfqdycms;
        this.zzjy_sfzz = zzjy_sfzz;
        this.zzjy_yy = zzjy_yy;
        this.zzjy_jgjks = zzjy_jgjks;
        this.zd_zdmc = zd_zdmc;
        this.zd_tsyzjcl = zd_tsyzjcl;
        this.zd_xcsfrq = zd_xcsfrq;
        this.zd_xcfsdd = zd_xcfsdd;
        this.zd_sfysqm = zd_sfysqm;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /** Not-null value. */
    public String getFollowUpNo() {
        return followUpNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowUpNo(String followUpNo) {
        this.followUpNo = followUpNo;
    }

    /** Not-null value. */
    public String getIdcard() {
        return idcard;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getGrxx_fsrq() {
        return grxx_fsrq;
    }

    public void setGrxx_fsrq(String grxx_fsrq) {
        this.grxx_fsrq = grxx_fsrq;
    }

    public String getGrxx_fscs() {
        return grxx_fscs;
    }

    public void setGrxx_fscs(String grxx_fscs) {
        this.grxx_fscs = grxx_fscs;
    }

    public String getGrxx_csrl() {
        return grxx_csrl;
    }

    public void setGrxx_csrl(String grxx_csrl) {
        this.grxx_csrl = grxx_csrl;
    }

    public String getGrxx_zrys() {
        return grxx_zrys;
    }

    public void setGrxx_zrys(String grxx_zrys) {
        this.grxx_zrys = grxx_zrys;
    }

    public String getWyqk_wyfs() {
        return wyqk_wyfs;
    }

    public void setWyqk_wyfs(String wyqk_wyfs) {
        this.wyqk_wyfs = wyqk_wyfs;
    }

    public String getWyqk_cnl() {
        return wyqk_cnl;
    }

    public void setWyqk_cnl(String wyqk_cnl) {
        this.wyqk_cnl = wyqk_cnl;
    }

    public String getWyqk_cncs() {
        return wyqk_cncs;
    }

    public void setWyqk_cncs(String wyqk_cncs) {
        this.wyqk_cncs = wyqk_cncs;
    }

    public Boolean getWyqk_sfot() {
        return wyqk_sfot;
    }

    public void setWyqk_sfot(Boolean wyqk_sfot) {
        this.wyqk_sfot = wyqk_sfot;
    }

    public String getJbstzk_dbxz() {
        return jbstzk_dbxz;
    }

    public void setJbstzk_dbxz(String jbstzk_dbxz) {
        this.jbstzk_dbxz = jbstzk_dbxz;
    }

    public String getJbstzk_dbcs() {
        return jbstzk_dbcs;
    }

    public void setJbstzk_dbcs(String jbstzk_dbcs) {
        this.jbstzk_dbcs = jbstzk_dbcs;
    }

    public String getJbstzk_dbys() {
        return jbstzk_dbys;
    }

    public void setJbstzk_dbys(String jbstzk_dbys) {
        this.jbstzk_dbys = jbstzk_dbys;
    }

    public String getJbstzk_smwt() {
        return jbstzk_smwt;
    }

    public void setJbstzk_smwt(String jbstzk_smwt) {
        this.jbstzk_smwt = jbstzk_smwt;
    }

    public Boolean getGwe_sfgwe() {
        return gwe_sfgwe;
    }

    public void setGwe_sfgwe(Boolean gwe_sfgwe) {
        this.gwe_sfgwe = gwe_sfgwe;
    }

    public String getTgjcqk_mqtz() {
        return tgjcqk_mqtz;
    }

    public void setTgjcqk_mqtz(String tgjcqk_mqtz) {
        this.tgjcqk_mqtz = tgjcqk_mqtz;
    }

    public String getTgjcqk_tw() {
        return tgjcqk_tw;
    }

    public void setTgjcqk_tw(String tgjcqk_tw) {
        this.tgjcqk_tw = tgjcqk_tw;
    }

    public String getTgjcqk_sc() {
        return tgjcqk_sc;
    }

    public void setTgjcqk_sc(String tgjcqk_sc) {
        this.tgjcqk_sc = tgjcqk_sc;
    }

    public String getTgjcqk_hxpl() {
        return tgjcqk_hxpl;
    }

    public void setTgjcqk_hxpl(String tgjcqk_hxpl) {
        this.tgjcqk_hxpl = tgjcqk_hxpl;
    }

    public String getTgjcqk_ml() {
        return tgjcqk_ml;
    }

    public void setTgjcqk_ml(String tgjcqk_ml) {
        this.tgjcqk_ml = tgjcqk_ml;
    }

    public String getTgjcqk_ms() {
        return tgjcqk_ms;
    }

    public void setTgjcqk_ms(String tgjcqk_ms) {
        this.tgjcqk_ms = tgjcqk_ms;
    }

    public String getTgjcqk_hdbw() {
        return tgjcqk_hdbw;
    }

    public void setTgjcqk_hdbw(String tgjcqk_hdbw) {
        this.tgjcqk_hdbw = tgjcqk_hdbw;
    }

    public String getTgjcqk_qx() {
        return tgjcqk_qx;
    }

    public void setTgjcqk_qx(String tgjcqk_qx) {
        this.tgjcqk_qx = tgjcqk_qx;
    }

    public String getTgjcqk_qxjl() {
        return tgjcqk_qxjl;
    }

    public void setTgjcqk_qxjl(String tgjcqk_qxjl) {
        this.tgjcqk_qxjl = tgjcqk_qxjl;
    }

    public Boolean getTgjcqk_sfywgyc() {
        return tgjcqk_sfywgyc;
    }

    public void setTgjcqk_sfywgyc(Boolean tgjcqk_sfywgyc) {
        this.tgjcqk_sfywgyc = tgjcqk_sfywgyc;
    }

    public String getTgjcqk_sfywgycms() {
        return tgjcqk_sfywgycms;
    }

    public void setTgjcqk_sfywgycms(String tgjcqk_sfywgycms) {
        this.tgjcqk_sfywgycms = tgjcqk_sfywgycms;
    }

    public Boolean getTgjcqk_sfewgyc() {
        return tgjcqk_sfewgyc;
    }

    public void setTgjcqk_sfewgyc(Boolean tgjcqk_sfewgyc) {
        this.tgjcqk_sfewgyc = tgjcqk_sfewgyc;
    }

    public String getTgjcqk_sfewgycms() {
        return tgjcqk_sfewgycms;
    }

    public void setTgjcqk_sfewgycms(String tgjcqk_sfewgycms) {
        this.tgjcqk_sfewgycms = tgjcqk_sfewgycms;
    }

    public Boolean getTgjcqk_sfbyc() {
        return tgjcqk_sfbyc;
    }

    public void setTgjcqk_sfbyc(Boolean tgjcqk_sfbyc) {
        this.tgjcqk_sfbyc = tgjcqk_sfbyc;
    }

    public String getTgjcqk_sfbycms() {
        return tgjcqk_sfbycms;
    }

    public void setTgjcqk_sfbycms(String tgjcqk_sfbycms) {
        this.tgjcqk_sfbycms = tgjcqk_sfbycms;
    }

    public Boolean getTgjcqk_sfkqyc() {
        return tgjcqk_sfkqyc;
    }

    public void setTgjcqk_sfkqyc(Boolean tgjcqk_sfkqyc) {
        this.tgjcqk_sfkqyc = tgjcqk_sfkqyc;
    }

    public String getTgjcqk_sfkqycms() {
        return tgjcqk_sfkqycms;
    }

    public void setTgjcqk_sfkqycms(String tgjcqk_sfkqycms) {
        this.tgjcqk_sfkqycms = tgjcqk_sfkqycms;
    }

    public Boolean getTgjcqk_sfxftzyc() {
        return tgjcqk_sfxftzyc;
    }

    public void setTgjcqk_sfxftzyc(Boolean tgjcqk_sfxftzyc) {
        this.tgjcqk_sfxftzyc = tgjcqk_sfxftzyc;
    }

    public String getTgjcqk_sfxftzycms() {
        return tgjcqk_sfxftzycms;
    }

    public void setTgjcqk_sfxftzycms(String tgjcqk_sfxftzycms) {
        this.tgjcqk_sfxftzycms = tgjcqk_sfxftzycms;
    }

    public Boolean getTgjcqk_sffbczyc() {
        return tgjcqk_sffbczyc;
    }

    public void setTgjcqk_sffbczyc(Boolean tgjcqk_sffbczyc) {
        this.tgjcqk_sffbczyc = tgjcqk_sffbczyc;
    }

    public String getTgjcqk_sffbczycms() {
        return tgjcqk_sffbczycms;
    }

    public void setTgjcqk_sffbczycms(String tgjcqk_sffbczycms) {
        this.tgjcqk_sffbczycms = tgjcqk_sffbczycms;
    }

    public Boolean getTgjcqk_sfszhddyc() {
        return tgjcqk_sfszhddyc;
    }

    public void setTgjcqk_sfszhddyc(Boolean tgjcqk_sfszhddyc) {
        this.tgjcqk_sfszhddyc = tgjcqk_sfszhddyc;
    }

    public String getTgjcqk_sfszhddycms() {
        return tgjcqk_sfszhddycms;
    }

    public void setTgjcqk_sfszhddycms(String tgjcqk_sfszhddycms) {
        this.tgjcqk_sfszhddycms = tgjcqk_sfszhddycms;
    }

    public Boolean getTgjcqk_sfjbbkyc() {
        return tgjcqk_sfjbbkyc;
    }

    public void setTgjcqk_sfjbbkyc(Boolean tgjcqk_sfjbbkyc) {
        this.tgjcqk_sfjbbkyc = tgjcqk_sfjbbkyc;
    }

    public String getTgjcqk_sfjbbkycms() {
        return tgjcqk_sfjbbkycms;
    }

    public void setTgjcqk_sfjbbkycms(String tgjcqk_sfjbbkycms) {
        this.tgjcqk_sfjbbkycms = tgjcqk_sfjbbkycms;
    }

    public String getTgjcqk_pf() {
        return tgjcqk_pf;
    }

    public void setTgjcqk_pf(String tgjcqk_pf) {
        this.tgjcqk_pf = tgjcqk_pf;
    }

    public Boolean getTgjcqk_sfgmyc() {
        return tgjcqk_sfgmyc;
    }

    public void setTgjcqk_sfgmyc(Boolean tgjcqk_sfgmyc) {
        this.tgjcqk_sfgmyc = tgjcqk_sfgmyc;
    }

    public String getTgjcqk_sfgmycms() {
        return tgjcqk_sfgmycms;
    }

    public void setTgjcqk_sfgmycms(String tgjcqk_sfgmycms) {
        this.tgjcqk_sfgmycms = tgjcqk_sfgmycms;
    }

    public Boolean getTgjcqk_sfwszqyc() {
        return tgjcqk_sfwszqyc;
    }

    public void setTgjcqk_sfwszqyc(Boolean tgjcqk_sfwszqyc) {
        this.tgjcqk_sfwszqyc = tgjcqk_sfwszqyc;
    }

    public String getTgjcqk_sfwszqycms() {
        return tgjcqk_sfwszqycms;
    }

    public void setTgjcqk_sfwszqycms(String tgjcqk_sfwszqycms) {
        this.tgjcqk_sfwszqycms = tgjcqk_sfwszqycms;
    }

    public Boolean getTgjcqk_sfjzyc() {
        return tgjcqk_sfjzyc;
    }

    public void setTgjcqk_sfjzyc(Boolean tgjcqk_sfjzyc) {
        this.tgjcqk_sfjzyc = tgjcqk_sfjzyc;
    }

    public String getTgjcqk_sfjzycms() {
        return tgjcqk_sfjzycms;
    }

    public void setTgjcqk_sfjzycms(String tgjcqk_sfjzycms) {
        this.tgjcqk_sfjzycms = tgjcqk_sfjzycms;
    }

    public Boolean getTgjcqk_sfqdyc() {
        return tgjcqk_sfqdyc;
    }

    public void setTgjcqk_sfqdyc(Boolean tgjcqk_sfqdyc) {
        this.tgjcqk_sfqdyc = tgjcqk_sfqdyc;
    }

    public String getTgjcqk_sfqdycms() {
        return tgjcqk_sfqdycms;
    }

    public void setTgjcqk_sfqdycms(String tgjcqk_sfqdycms) {
        this.tgjcqk_sfqdycms = tgjcqk_sfqdycms;
    }

    public Boolean getZzjy_sfzz() {
        return zzjy_sfzz;
    }

    public void setZzjy_sfzz(Boolean zzjy_sfzz) {
        this.zzjy_sfzz = zzjy_sfzz;
    }

    public String getZzjy_yy() {
        return zzjy_yy;
    }

    public void setZzjy_yy(String zzjy_yy) {
        this.zzjy_yy = zzjy_yy;
    }

    public String getZzjy_jgjks() {
        return zzjy_jgjks;
    }

    public void setZzjy_jgjks(String zzjy_jgjks) {
        this.zzjy_jgjks = zzjy_jgjks;
    }

    public String getZd_zdmc() {
        return zd_zdmc;
    }

    public void setZd_zdmc(String zd_zdmc) {
        this.zd_zdmc = zd_zdmc;
    }

    public String getZd_tsyzjcl() {
        return zd_tsyzjcl;
    }

    public void setZd_tsyzjcl(String zd_tsyzjcl) {
        this.zd_tsyzjcl = zd_tsyzjcl;
    }

    public String getZd_xcsfrq() {
        return zd_xcsfrq;
    }

    public void setZd_xcsfrq(String zd_xcsfrq) {
        this.zd_xcsfrq = zd_xcsfrq;
    }

    public String getZd_xcfsdd() {
        return zd_xcfsdd;
    }

    public void setZd_xcfsdd(String zd_xcfsdd) {
        this.zd_xcfsdd = zd_xcfsdd;
    }

    public String getZd_sfysqm() {
        return zd_sfysqm;
    }

    public void setZd_sfysqm(String zd_sfysqm) {
        this.zd_sfysqm = zd_sfysqm;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
