package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpMentalDisease;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_MENTAL_DISEASE.
*/
public class FollowUpMentalDiseaseDao extends AbstractDao<FollowUpMentalDisease, String> {

    public static final String TABLENAME = "FOLLOW_UP_MENTAL_DISEASE";

    /**
     * Properties of entity FollowUpMentalDisease.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_zrys = new Property(2, String.class, "grxx_zrys", false, "GRXX_ZRYS");
        public final static Property Grxx_sfrq = new Property(3, String.class, "grxx_sfrq", false, "GRXX_SFRQ");
        public final static Property Wxx = new Property(4, String.class, "wxx", false, "WXX");
        public final static Property Zz_zzmc = new Property(5, String.class, "zz_zzmc", false, "ZZ_ZZMC");
        public final static Property Zz_zzl = new Property(6, String.class, "zz_zzl", false, "ZZ_ZZL");
        public final static Property Zz_smqk = new Property(7, String.class, "zz_smqk", false, "ZZ_SMQK");
        public final static Property Zz_ysqk = new Property(8, String.class, "zz_ysqk", false, "ZZ_YSQK");
        public final static Property Shgnqk_grshll = new Property(9, String.class, "shgnqk_grshll", false, "SHGNQK_GRSHLL");
        public final static Property Shgnqk_jwhd = new Property(10, String.class, "shgnqk_jwhd", false, "SHGNQK_JWHD");
        public final static Property Shgnqk_xxnl = new Property(11, String.class, "shgnqk_xxnl", false, "SHGNQK_XXNL");
        public final static Property Shgnqk_shldjgz = new Property(12, String.class, "shgnqk_shldjgz", false, "SHGNQK_SHLDJGZ");
        public final static Property Shgnqk_shrjjw = new Property(13, String.class, "shgnqk_shrjjw", false, "SHGNQK_SHRJJW");
        public final static Property Hzdjtshdyx_qdzs = new Property(14, String.class, "hzdjtshdyx_qdzs", false, "HZDJTSHDYX_QDZS");
        public final static Property Hzdjtshdyx_zhaos = new Property(15, String.class, "hzdjtshdyx_zhaos", false, "HZDJTSHDYX_ZHAOS");
        public final static Property Hzdjtshdyx_zs = new Property(16, String.class, "hzdjtshdyx_zs", false, "HZDJTSHDYX_ZS");
        public final static Property Hzdjtshdyx_zsws = new Property(17, String.class, "hzdjtshdyx_zsws", false, "HZDJTSHDYX_ZSWS");
        public final static Property Hzdjtshdyx_gsqk = new Property(18, String.class, "hzdjtshdyx_gsqk", false, "HZDJTSHDYX_GSQK");
        public final static Property Hzdjtshdyx_mccysj = new Property(19, String.class, "hzdjtshdyx_mccysj", false, "HZDJTSHDYX_MCCYSJ");
        public final static Property Hzdjtshdyx_zyqk = new Property(20, String.class, "hzdjtshdyx_zyqk", false, "HZDJTSHDYX_ZYQK");
        public final static Property Sysfzjc_jcx = new Property(21, String.class, "sysfzjc_jcx", false, "SYSFZJC_JCX");
        public final static Property Sysfzjc_fyycx = new Property(22, String.class, "sysfzjc_fyycx", false, "SYSFZJC_FYYCX");
        public final static Property Shxggb_sfywblfy = new Property(23, Boolean.class, "shxggb_sfywblfy", false, "SHXGGB_SFYWBLFY");
        public final static Property Shxggb_sfywblfyms = new Property(24, String.class, "shxggb_sfywblfyms", false, "SHXGGB_SFYWBLFYMS");
        public final static Property Shxggb_zlxg = new Property(25, String.class, "shxggb_zlxg", false, "SHXGGB_ZLXG");
        public final static Property Shxggb_sfzz = new Property(26, Boolean.class, "shxggb_sfzz", false, "SHXGGB_SFZZ");
        public final static Property Shxggb_sfzzms = new Property(27, String.class, "shxggb_sfzzms", false, "SHXGGB_SFZZMS");
        public final static Property Shxggb_jgqks = new Property(28, String.class, "shxggb_jgqks", false, "SHXGGB_JGQKS");
        public final static Property CreateTime = new Property(29, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(30, String.class, "updateTime", false, "UPDATE_TIME");
        public final static Property Yyqk = new Property(31, String.class, "yyqk", false, "YYQK");
        public final static Property Yyqk_kfcs = new Property(32, String.class, "yyqk_kfcs", false, "YYQK_KFCS");
        public final static Property Yyqk_bcsffl = new Property(33, String.class, "yyqk_bcsffl", false, "YYQK_BCSFFL");
        public final static Property Yyqk_xcsfrq = new Property(34, String.class, "yyqk_xcsfrq", false, "YYQK_XCSFRQ");
        public final static Property Yyqk_sfysqm = new Property(35, String.class, "yyqk_sfysqm", false, "YYQK_SFYSQM");
    };


    public FollowUpMentalDiseaseDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpMentalDiseaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_MENTAL_DISEASE' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_ZRYS' TEXT," + // 2: grxx_zrys
                "'GRXX_SFRQ' TEXT," + // 3: grxx_sfrq
                "'WXX' TEXT," + // 4: wxx
                "'ZZ_ZZMC' TEXT," + // 5: zz_zzmc
                "'ZZ_ZZL' TEXT," + // 6: zz_zzl
                "'ZZ_SMQK' TEXT," + // 7: zz_smqk
                "'ZZ_YSQK' TEXT," + // 8: zz_ysqk
                "'SHGNQK_GRSHLL' TEXT," + // 9: shgnqk_grshll
                "'SHGNQK_JWHD' TEXT," + // 10: shgnqk_jwhd
                "'SHGNQK_XXNL' TEXT," + // 11: shgnqk_xxnl
                "'SHGNQK_SHLDJGZ' TEXT," + // 12: shgnqk_shldjgz
                "'SHGNQK_SHRJJW' TEXT," + // 13: shgnqk_shrjjw
                "'HZDJTSHDYX_QDZS' TEXT," + // 14: hzdjtshdyx_qdzs
                "'HZDJTSHDYX_ZHAOS' TEXT," + // 15: hzdjtshdyx_zhaos
                "'HZDJTSHDYX_ZS' TEXT," + // 16: hzdjtshdyx_zs
                "'HZDJTSHDYX_ZSWS' TEXT," + // 17: hzdjtshdyx_zsws
                "'HZDJTSHDYX_GSQK' TEXT," + // 18: hzdjtshdyx_gsqk
                "'HZDJTSHDYX_MCCYSJ' TEXT," + // 19: hzdjtshdyx_mccysj
                "'HZDJTSHDYX_ZYQK' TEXT," + // 20: hzdjtshdyx_zyqk
                "'SYSFZJC_JCX' TEXT," + // 21: sysfzjc_jcx
                "'SYSFZJC_FYYCX' TEXT," + // 22: sysfzjc_fyycx
                "'SHXGGB_SFYWBLFY' INTEGER," + // 23: shxggb_sfywblfy
                "'SHXGGB_SFYWBLFYMS' TEXT," + // 24: shxggb_sfywblfyms
                "'SHXGGB_ZLXG' TEXT," + // 25: shxggb_zlxg
                "'SHXGGB_SFZZ' INTEGER," + // 26: shxggb_sfzz
                "'SHXGGB_SFZZMS' TEXT," + // 27: shxggb_sfzzms
                "'SHXGGB_JGQKS' TEXT," + // 28: shxggb_jgqks
                "'CREATE_TIME' TEXT," + // 29: createTime
                "'UPDATE_TIME' TEXT," + // 29: createTime
                "'YYQK' TEXT," + // 29: createTime
                "'YYQK_KFCS' TEXT," + // 29: createTime
                "'YYQK_BCSFFL' TEXT," + // 29: createTime
                "'YYQK_XCSFRQ' TEXT," + // 29: createTime
                "'YYQK_SFYSQM' TEXT);"); // 30: updateTime
    }

    
    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_MENTAL_DISEASE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpMentalDisease entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_zrys = entity.getGrxx_zrys();
        if (grxx_zrys != null) {
            stmt.bindString(3, grxx_zrys);
        }
 
        String grxx_sfrq = entity.getGrxx_sfrq();
        if (grxx_sfrq != null) {
            stmt.bindString(4, grxx_sfrq);
        }
 
        String wxx = entity.getWxx();
        if (wxx != null) {
            stmt.bindString(5, wxx);
        }
 
        String zz_zzmc = entity.getZz_zzmc();
        if (zz_zzmc != null) {
            stmt.bindString(6, zz_zzmc);
        }
 
        String zz_zzl = entity.getZz_zzl();
        if (zz_zzl != null) {
            stmt.bindString(7, zz_zzl);
        }
 
        String zz_smqk = entity.getZz_smqk();
        if (zz_smqk != null) {
            stmt.bindString(8, zz_smqk);
        }
 
        String zz_ysqk = entity.getZz_ysqk();
        if (zz_ysqk != null) {
            stmt.bindString(9, zz_ysqk);
        }
 
        String shgnqk_grshll = entity.getShgnqk_grshll();
        if (shgnqk_grshll != null) {
            stmt.bindString(10, shgnqk_grshll);
        }
 
        String shgnqk_jwhd = entity.getShgnqk_jwhd();
        if (shgnqk_jwhd != null) {
            stmt.bindString(11, shgnqk_jwhd);
        }
 
        String shgnqk_xxnl = entity.getShgnqk_xxnl();
        if (shgnqk_xxnl != null) {
            stmt.bindString(12, shgnqk_xxnl);
        }
 
        String shgnqk_shldjgz = entity.getShgnqk_shldjgz();
        if (shgnqk_shldjgz != null) {
            stmt.bindString(13, shgnqk_shldjgz);
        }
 
        String shgnqk_shrjjw = entity.getShgnqk_shrjjw();
        if (shgnqk_shrjjw != null) {
            stmt.bindString(14, shgnqk_shrjjw);
        }
 
        String hzdjtshdyx_qdzs = entity.getHzdjtshdyx_qdzs();
        if (hzdjtshdyx_qdzs != null) {
            stmt.bindString(15, hzdjtshdyx_qdzs);
        }
 
        String hzdjtshdyx_zhaos = entity.getHzdjtshdyx_zhaos();
        if (hzdjtshdyx_zhaos != null) {
            stmt.bindString(16, hzdjtshdyx_zhaos);
        }
 
        String hzdjtshdyx_zs = entity.getHzdjtshdyx_zs();
        if (hzdjtshdyx_zs != null) {
            stmt.bindString(17, hzdjtshdyx_zs);
        }
 
        String hzdjtshdyx_zsws = entity.getHzdjtshdyx_zsws();
        if (hzdjtshdyx_zsws != null) {
            stmt.bindString(18, hzdjtshdyx_zsws);
        }
 
        String hzdjtshdyx_gsqk = entity.getHzdjtshdyx_gsqk();
        if (hzdjtshdyx_gsqk != null) {
            stmt.bindString(19, hzdjtshdyx_gsqk);
        }
 
        String hzdjtshdyx_mccysj = entity.getHzdjtshdyx_mccysj();
        if (hzdjtshdyx_mccysj != null) {
            stmt.bindString(20, hzdjtshdyx_mccysj);
        }
 
        String hzdjtshdyx_zyqk = entity.getHzdjtshdyx_zyqk();
        if (hzdjtshdyx_zyqk != null) {
            stmt.bindString(21, hzdjtshdyx_zyqk);
        }
 
        String sysfzjc_jcx = entity.getSysfzjc_jcx();
        if (sysfzjc_jcx != null) {
            stmt.bindString(22, sysfzjc_jcx);
        }
 
        String sysfzjc_fyycx = entity.getSysfzjc_fyycx();
        if (sysfzjc_fyycx != null) {
            stmt.bindString(23, sysfzjc_fyycx);
        }
 
        Boolean shxggb_sfywblfy = entity.getShxggb_sfywblfy();
        if (shxggb_sfywblfy != null) {
            stmt.bindLong(24, shxggb_sfywblfy ? 1l: 0l);
        }
 
        String shxggb_sfywblfyms = entity.getShxggb_sfywblfyms();
        if (shxggb_sfywblfyms != null) {
            stmt.bindString(25, shxggb_sfywblfyms);
        }
 
        String shxggb_zlxg = entity.getShxggb_zlxg();
        if (shxggb_zlxg != null) {
            stmt.bindString(26, shxggb_zlxg);
        }
 
        Boolean shxggb_sfzz = entity.getShxggb_sfzz();
        if (shxggb_sfzz != null) {
            stmt.bindLong(27, shxggb_sfzz ? 1l: 0l);
        }
 
        String shxggb_sfzzms = entity.getShxggb_sfzzms();
        if (shxggb_sfzzms != null) {
            stmt.bindString(28, shxggb_sfzzms);
        }
 
        String shxggb_jgqks = entity.getShxggb_jgqks();
        if (shxggb_jgqks != null) {
            stmt.bindString(29, shxggb_jgqks);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(30, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(31, updateTime);
        }
        
        String yyqk = entity.getYyqk();
        if (yyqk != null) {
        	stmt.bindString(32, yyqk);
        }
        String yyqk_kfcs = entity.getYyqk_kfcs();
        if (yyqk_kfcs != null) {
        	stmt.bindString(33, yyqk_kfcs);
        }
        String yyqk_bcsffl = entity.getYyqk_bcsffl();
        if (yyqk_bcsffl != null) {
        	stmt.bindString(34, yyqk_bcsffl);
        }
        String yyqk_xcsfrq = entity.getYyqk_xcsfrq();
        if (yyqk_xcsfrq != null) {
        	stmt.bindString(35, yyqk_xcsfrq);
        }
        String yyqk_sfysqm = entity.getYyqk_sfysqm();
        if (yyqk_sfysqm != null) {
        	stmt.bindString(36, yyqk_sfysqm);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpMentalDisease readEntity(Cursor cursor, int offset) {
        FollowUpMentalDisease entity = new FollowUpMentalDisease( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_zrys
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grxx_sfrq
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // wxx
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // zz_zzmc
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // zz_zzl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // zz_smqk
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // zz_ysqk
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // shgnqk_grshll
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // shgnqk_jwhd
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // shgnqk_xxnl
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // shgnqk_shldjgz
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // shgnqk_shrjjw
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // hzdjtshdyx_qdzs
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // hzdjtshdyx_zhaos
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // hzdjtshdyx_zs
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // hzdjtshdyx_zsws
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // hzdjtshdyx_gsqk
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // hzdjtshdyx_mccysj
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // hzdjtshdyx_zyqk
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // sysfzjc_jcx
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // sysfzjc_fyycx
            cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0, // shxggb_sfywblfy
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // shxggb_sfywblfyms
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // shxggb_zlxg
            cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26) != 0, // shxggb_sfzz
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // shxggb_sfzzms
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // shxggb_jgqks
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // createTime
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // updateTime
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // updateTime
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // updateTime
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // updateTime
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // updateTime
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpMentalDisease entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_zrys(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrxx_sfrq(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWxx(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setZz_zzmc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setZz_zzl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setZz_smqk(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setZz_ysqk(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setShgnqk_grshll(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setShgnqk_jwhd(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setShgnqk_xxnl(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setShgnqk_shldjgz(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setShgnqk_shrjjw(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setHzdjtshdyx_qdzs(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setHzdjtshdyx_zhaos(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setHzdjtshdyx_zs(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setHzdjtshdyx_zsws(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setHzdjtshdyx_gsqk(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setHzdjtshdyx_mccysj(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setHzdjtshdyx_zyqk(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setSysfzjc_jcx(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setSysfzjc_fyycx(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setShxggb_sfywblfy(cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0);
        entity.setShxggb_sfywblfyms(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setShxggb_zlxg(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setShxggb_sfzz(cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26) != 0);
        entity.setShxggb_sfzzms(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setShxggb_jgqks(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setCreateTime(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setUpdateTime(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setYyqk(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setYyqk_kfcs(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setYyqk_bcsffl(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setYyqk_xcsfrq(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setYyqk_sfysqm(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpMentalDisease entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpMentalDisease entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
