package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpOneTwoNewborn;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_ONE_TWO_NEWBORN.
*/
public class FollowUpOneTwoNewbornDao extends AbstractDao<FollowUpOneTwoNewborn, String> {

    public static final String TABLENAME = "FOLLOW_UP_ONE_TWO_NEWBORN";

    /**
     * Properties of entity FollowUpOneTwoNewborn.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_fsrq = new Property(2, String.class, "grxx_fsrq", false, "GRXX_FSRQ");
        public final static Property Grxx_ynl = new Property(3, String.class, "grxx_ynl", false, "GRXX_YNL");
        public final static Property Grxx_csrl = new Property(4, String.class, "grxx_csrl", false, "GRXX_CSRL");
        public final static Property Grxx_zrys = new Property(5, String.class, "grxx_zrys", false, "GRXX_ZRYS");
        public final static Property Wyqk_sfmryy = new Property(6, Boolean.class, "wyqk_sfmryy", false, "WYQK_SFMRYY");
        public final static Property Wyqk_sfmryyms = new Property(7, String.class, "wyqk_sfmryyms", false, "WYQK_SFMRYYMS");
        public final static Property Wyqk_zccs = new Property(8, String.class, "wyqk_zccs", false, "WYQK_ZCCS");
        public final static Property Wyqk_nnnf = new Property(9, String.class, "wyqk_nnnf", false, "WYQK_NNNF");
        public final static Property Wyqk_d = new Property(10, String.class, "wyqk_d", false, "WYQK_D");
        public final static Property Wyqk_rlhyx = new Property(11, String.class, "wyqk_rlhyx", false, "WYQK_RLHYX");
        public final static Property Wyqk_sghsc = new Property(12, String.class, "wyqk_sghsc", false, "WYQK_SGHSC");
        public final static Property Wyqk_sy = new Property(13, String.class, "wyqk_sy", false, "WYQK_SY");
        public final static Property Wyqk_fywssd = new Property(14, String.class, "wyqk_fywssd", false, "WYQK_FYWSSD");
        public final static Property Tgjcqk_tz = new Property(15, String.class, "tgjcqk_tz", false, "TGJCQK_TZ");
        public final static Property Tgjcqk_sc = new Property(16, String.class, "tgjcqk_sc", false, "TGJCQK_SC");
        public final static Property Tgjcqk_bmi = new Property(17, String.class, "tgjcqk_bmi", false, "TGJCQK_BMI");
        public final static Property Tgjcqk_tw = new Property(18, String.class, "tgjcqk_tw", false, "TGJCQK_TW");
        public final static Property Tgjcqk_yypj = new Property(19, String.class, "tgjcqk_yypj", false, "TGJCQK_YYPJ");
        public final static Property Tgjcqk_ms = new Property(20, String.class, "tgjcqk_ms", false, "TGJCQK_MS");
        public final static Property Tgjcqk_sfqxbh = new Property(21, Boolean.class, "tgjcqk_sfqxbh", false, "TGJCQK_SFQXBH");
        public final static Property Tgjcqk_sfqxbhms = new Property(22, String.class, "tgjcqk_sfqxbhms", false, "TGJCQK_SFQXBHMS");
        public final static Property Tgjcqk_sfpfyc = new Property(23, Boolean.class, "tgjcqk_sfpfyc", false, "TGJCQK_SFPFYC");
        public final static Property Tgjcqk_sfpfycms = new Property(24, String.class, "tgjcqk_sfpfycms", false, "TGJCQK_SFPFYCMS");
        public final static Property Tgjcqk_sfywgyc = new Property(25, Boolean.class, "tgjcqk_sfywgyc", false, "TGJCQK_SFYWGYC");
        public final static Property Tgjcqk_sfywgycms = new Property(26, String.class, "tgjcqk_sfywgycms", false, "TGJCQK_SFYWGYCMS");
        public final static Property Tgjcqk_sfewgyc = new Property(27, Boolean.class, "tgjcqk_sfewgyc", false, "TGJCQK_SFEWGYC");
        public final static Property Tgjcqk_sfewgycms = new Property(28, String.class, "tgjcqk_sfewgycms", false, "TGJCQK_SFEWGYCMS");
        public final static Property Tgjcqk_sftlyc = new Property(29, Boolean.class, "tgjcqk_sftlyc", false, "TGJCQK_SFTLYC");
        public final static Property Tgjcqk_sftlycms = new Property(30, String.class, "tgjcqk_sftlycms", false, "TGJCQK_SFTLYCMS");
        public final static Property Tgjcqk_cyqcs = new Property(31, String.class, "tgjcqk_cyqcs", false, "TGJCQK_CYQCS");
        public final static Property Tgjcqk_cyqcsjl = new Property(32, String.class, "tgjcqk_cyqcsjl", false, "TGJCQK_CYQCSJL");
        public final static Property Tgjcqk_sfxftzyc = new Property(33, Boolean.class, "tgjcqk_sfxftzyc", false, "TGJCQK_SFXFTZYC");
        public final static Property Tgjcqk_sfxftzycms = new Property(34, String.class, "tgjcqk_sfxftzycms", false, "TGJCQK_SFXFTZYCMS");
        public final static Property Tgjcqk_sffbczyc = new Property(35, Boolean.class, "tgjcqk_sffbczyc", false, "TGJCQK_SFFBCZYC");
        public final static Property Tgjcqk_sffbczycms = new Property(36, String.class, "tgjcqk_sffbczycms", false, "TGJCQK_SFFBCZYCMS");
        public final static Property Tgjcqk_sfszhddyc = new Property(37, Boolean.class, "tgjcqk_sfszhddyc", false, "TGJCQK_SFSZHDDYC");
        public final static Property Tgjcqk_sfszhddycms = new Property(38, String.class, "tgjcqk_sfszhddycms", false, "TGJCQK_SFSZHDDYCMS");
        public final static Property Tgjcqk_sfwszqyc = new Property(39, Boolean.class, "tgjcqk_sfwszqyc", false, "TGJCQK_SFWSZQYC");
        public final static Property Tgjcqk_sfwszqycms = new Property(40, String.class, "tgjcqk_sfwszqycms", false, "TGJCQK_SFWSZQYCMS");
        public final static Property Tgjcqk_glbtz = new Property(41, String.class, "tgjcqk_glbtz", false, "TGJCQK_GLBTZ");
        public final static Property Fysc_hyysjbbmm = new Property(42, Boolean.class, "fysc_hyysjbbmm", false, "FYSC_HYYSJBBMM");
        public final static Property Fysc_hyszrdxhtp = new Property(43, Boolean.class, "fysc_hyszrdxhtp", false, "FYSC_HYSZRDXHTP");
        public final static Property Fysc_zjdzw = new Property(44, Boolean.class, "fysc_zjdzw", false, "FYSC_ZJDZW");
        public final static Property Fysc_hjwjfdbzhwl = new Property(45, Boolean.class, "fysc_hjwjfdbzhwl", false, "FYSC_HJWJFDBZHWL");
        public final static Property Fysc_nzjdxbzql = new Property(46, Boolean.class, "fysc_nzjdxbzql", false, "FYSC_NZJDXBZQL");
        public final static Property Fysc_hssgysddz = new Property(47, Boolean.class, "fysc_hssgysddz", false, "FYSC_HSSGYSDDZ");
        public final static Property Fysc_hzrzjwghstbw = new Property(48, Boolean.class, "fysc_hzrzjwghstbw", false, "FYSC_HZRZJWGHSTBW");
        public final static Property Fysc_nwcjdzlrbqfzs = new Property(49, Boolean.class, "fysc_nwcjdzlrbqfzs", false, "FYSC_NWCJDZLRBQFZS");
        public final static Property Fysc_hzjp = new Property(50, Boolean.class, "fysc_hzjp", false, "FYSC_HZJP");
        public final static Property Fysc_hdg37kjmhwj = new Property(51, Boolean.class, "fysc_hdg37kjmhwj", false, "FYSC_HDG37KJMHWJ");
        public final static Property Xhdbz = new Property(52, String.class, "xhdbz", false, "XHDBZ");
        public final static Property Sysjc = new Property(53, String.class, "sysjc", false, "SYSJC");
        public final static Property Fzjc = new Property(54, String.class, "fzjc", false, "FZJC");
        public final static Property Hwhd = new Property(55, String.class, "hwhd", false, "HWHD");
        public final static Property Fypg_sftg = new Property(56, Boolean.class, "fypg_sftg", false, "FYPG_SFTG");
        public final static Property Hbqk_sfhb = new Property(57, Boolean.class, "hbqk_sfhb", false, "HBQK_SFHB");
        public final static Property Hbqk_sfhbms = new Property(58, String.class, "hbqk_sfhbms", false, "HBQK_SFHBMS");
        public final static Property Jbzd = new Property(59, String.class, "jbzd", false, "JBZD");
        public final static Property Yyxjbgl_sfyyxjb = new Property(60, Boolean.class, "yyxjbgl_sfyyxjb", false, "YYXJBGL_SFYYXJB");
        public final static Property Yyxjbgl_sfgwe = new Property(61, Boolean.class, "yyxjbgl_sfgwe", false, "YYXJBGL_SFGWE");
        public final static Property Zz_sfzz = new Property(62, Boolean.class, "zz_sfzz", false, "ZZ_SFZZ");
        public final static Property Zz_yy = new Property(63, String.class, "zz_yy", false, "ZZ_YY");
        public final static Property Zz_jgjks = new Property(64, String.class, "zz_jgjks", false, "ZZ_JGJKS");
        public final static Property Zd_zd = new Property(65, String.class, "zd_zd", false, "ZD_ZD");
        public final static Property Zd_yzhjy = new Property(66, String.class, "zd_yzhjy", false, "ZD_YZHJY");
        public final static Property Zd_xcsfrq = new Property(67, String.class, "zd_xcsfrq", false, "ZD_XCSFRQ");
        public final static Property Zd_sfysqm = new Property(68, String.class, "zd_sfysqm", false, "ZD_SFYSQM");
        public final static Property CreateTime = new Property(69, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(70, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public FollowUpOneTwoNewbornDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpOneTwoNewbornDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_ONE_TWO_NEWBORN' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_FSRQ' TEXT," + // 2: grxx_fsrq
                "'GRXX_YNL' TEXT," + // 3: grxx_ynl
                "'GRXX_CSRL' TEXT," + // 4: grxx_csrl
                "'GRXX_ZRYS' TEXT," + // 5: grxx_zrys
                "'WYQK_SFMRYY' INTEGER," + // 6: wyqk_sfmryy
                "'WYQK_SFMRYYMS' TEXT," + // 7: wyqk_sfmryyms
                "'WYQK_ZCCS' TEXT," + // 8: wyqk_zccs
                "'WYQK_NNNF' TEXT," + // 9: wyqk_nnnf
                "'WYQK_D' TEXT," + // 10: wyqk_d
                "'WYQK_RLHYX' TEXT," + // 11: wyqk_rlhyx
                "'WYQK_SGHSC' TEXT," + // 12: wyqk_sghsc
                "'WYQK_SY' TEXT," + // 13: wyqk_sy
                "'WYQK_FYWSSD' TEXT," + // 14: wyqk_fywssd
                "'TGJCQK_TZ' TEXT," + // 15: tgjcqk_tz
                "'TGJCQK_SC' TEXT," + // 16: tgjcqk_sc
                "'TGJCQK_BMI' TEXT," + // 17: tgjcqk_bmi
                "'TGJCQK_TW' TEXT," + // 18: tgjcqk_tw
                "'TGJCQK_YYPJ' TEXT," + // 19: tgjcqk_yypj
                "'TGJCQK_MS' TEXT," + // 20: tgjcqk_ms
                "'TGJCQK_SFQXBH' INTEGER," + // 21: tgjcqk_sfqxbh
                "'TGJCQK_SFQXBHMS' TEXT," + // 22: tgjcqk_sfqxbhms
                "'TGJCQK_SFPFYC' INTEGER," + // 23: tgjcqk_sfpfyc
                "'TGJCQK_SFPFYCMS' TEXT," + // 24: tgjcqk_sfpfycms
                "'TGJCQK_SFYWGYC' INTEGER," + // 25: tgjcqk_sfywgyc
                "'TGJCQK_SFYWGYCMS' TEXT," + // 26: tgjcqk_sfywgycms
                "'TGJCQK_SFEWGYC' INTEGER," + // 27: tgjcqk_sfewgyc
                "'TGJCQK_SFEWGYCMS' TEXT," + // 28: tgjcqk_sfewgycms
                "'TGJCQK_SFTLYC' INTEGER," + // 29: tgjcqk_sftlyc
                "'TGJCQK_SFTLYCMS' TEXT," + // 30: tgjcqk_sftlycms
                "'TGJCQK_CYQCS' TEXT," + // 31: tgjcqk_cyqcs
                "'TGJCQK_CYQCSJL' TEXT," + // 32: tgjcqk_cyqcsjl
                "'TGJCQK_SFXFTZYC' INTEGER," + // 33: tgjcqk_sfxftzyc
                "'TGJCQK_SFXFTZYCMS' TEXT," + // 34: tgjcqk_sfxftzycms
                "'TGJCQK_SFFBCZYC' INTEGER," + // 35: tgjcqk_sffbczyc
                "'TGJCQK_SFFBCZYCMS' TEXT," + // 36: tgjcqk_sffbczycms
                "'TGJCQK_SFSZHDDYC' INTEGER," + // 37: tgjcqk_sfszhddyc
                "'TGJCQK_SFSZHDDYCMS' TEXT," + // 38: tgjcqk_sfszhddycms
                "'TGJCQK_SFWSZQYC' INTEGER," + // 39: tgjcqk_sfwszqyc
                "'TGJCQK_SFWSZQYCMS' TEXT," + // 40: tgjcqk_sfwszqycms
                "'TGJCQK_GLBTZ' TEXT," + // 41: tgjcqk_glbtz
                "'FYSC_HYYSJBBMM' INTEGER," + // 42: fysc_hyysjbbmm
                "'FYSC_HYSZRDXHTP' INTEGER," + // 43: fysc_hyszrdxhtp
                "'FYSC_ZJDZW' INTEGER," + // 44: fysc_zjdzw
                "'FYSC_HJWJFDBZHWL' INTEGER," + // 45: fysc_hjwjfdbzhwl
                "'FYSC_NZJDXBZQL' INTEGER," + // 46: fysc_nzjdxbzql
                "'FYSC_HSSGYSDDZ' INTEGER," + // 47: fysc_hssgysddz
                "'FYSC_HZRZJWGHSTBW' INTEGER," + // 48: fysc_hzrzjwghstbw
                "'FYSC_NWCJDZLRBQFZS' INTEGER," + // 49: fysc_nwcjdzlrbqfzs
                "'FYSC_HZJP' INTEGER," + // 50: fysc_hzjp
                "'FYSC_HDG37KJMHWJ' INTEGER," + // 51: fysc_hdg37kjmhwj
                "'XHDBZ' TEXT," + // 52: xhdbz
                "'SYSJC' TEXT," + // 53: sysjc
                "'FZJC' TEXT," + // 54: fzjc
                "'HWHD' TEXT," + // 55: hwhd
                "'FYPG_SFTG' INTEGER," + // 56: fypg_sftg
                "'HBQK_SFHB' INTEGER," + // 57: hbqk_sfhb
                "'HBQK_SFHBMS' TEXT," + // 58: hbqk_sfhbms
                "'JBZD' TEXT," + // 59: jbzd
                "'YYXJBGL_SFYYXJB' INTEGER," + // 60: yyxjbgl_sfyyxjb
                "'YYXJBGL_SFGWE' INTEGER," + // 61: yyxjbgl_sfgwe
                "'ZZ_SFZZ' INTEGER," + // 62: zz_sfzz
                "'ZZ_YY' TEXT," + // 63: zz_yy
                "'ZZ_JGJKS' TEXT," + // 64: zz_jgjks
                "'ZD_ZD' TEXT," + // 65: zd_zd
                "'ZD_YZHJY' TEXT," + // 66: zd_yzhjy
                "'ZD_XCSFRQ' TEXT," + // 67: zd_xcsfrq
                "'ZD_SFYSQM' TEXT," + // 68: zd_sfysqm
                "'CREATE_TIME' TEXT," + // 69: createTime
                "'UPDATE_TIME' TEXT);"); // 70: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_ONE_TWO_NEWBORN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpOneTwoNewborn entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_fsrq = entity.getGrxx_fsrq();
        if (grxx_fsrq != null) {
            stmt.bindString(3, grxx_fsrq);
        }
 
        String grxx_ynl = entity.getGrxx_ynl();
        if (grxx_ynl != null) {
            stmt.bindString(4, grxx_ynl);
        }
 
        String grxx_csrl = entity.getGrxx_csrl();
        if (grxx_csrl != null) {
            stmt.bindString(5, grxx_csrl);
        }
 
        String grxx_zrys = entity.getGrxx_zrys();
        if (grxx_zrys != null) {
            stmt.bindString(6, grxx_zrys);
        }
 
        Boolean wyqk_sfmryy = entity.getWyqk_sfmryy();
        if (wyqk_sfmryy != null) {
            stmt.bindLong(7, wyqk_sfmryy ? 1l: 0l);
        }
 
        String wyqk_sfmryyms = entity.getWyqk_sfmryyms();
        if (wyqk_sfmryyms != null) {
            stmt.bindString(8, wyqk_sfmryyms);
        }
 
        String wyqk_zccs = entity.getWyqk_zccs();
        if (wyqk_zccs != null) {
            stmt.bindString(9, wyqk_zccs);
        }
 
        String wyqk_nnnf = entity.getWyqk_nnnf();
        if (wyqk_nnnf != null) {
            stmt.bindString(10, wyqk_nnnf);
        }
 
        String wyqk_d = entity.getWyqk_d();
        if (wyqk_d != null) {
            stmt.bindString(11, wyqk_d);
        }
 
        String wyqk_rlhyx = entity.getWyqk_rlhyx();
        if (wyqk_rlhyx != null) {
            stmt.bindString(12, wyqk_rlhyx);
        }
 
        String wyqk_sghsc = entity.getWyqk_sghsc();
        if (wyqk_sghsc != null) {
            stmt.bindString(13, wyqk_sghsc);
        }
 
        String wyqk_sy = entity.getWyqk_sy();
        if (wyqk_sy != null) {
            stmt.bindString(14, wyqk_sy);
        }
 
        String wyqk_fywssd = entity.getWyqk_fywssd();
        if (wyqk_fywssd != null) {
            stmt.bindString(15, wyqk_fywssd);
        }
 
        String tgjcqk_tz = entity.getTgjcqk_tz();
        if (tgjcqk_tz != null) {
            stmt.bindString(16, tgjcqk_tz);
        }
 
        String tgjcqk_sc = entity.getTgjcqk_sc();
        if (tgjcqk_sc != null) {
            stmt.bindString(17, tgjcqk_sc);
        }
 
        String tgjcqk_bmi = entity.getTgjcqk_bmi();
        if (tgjcqk_bmi != null) {
            stmt.bindString(18, tgjcqk_bmi);
        }
 
        String tgjcqk_tw = entity.getTgjcqk_tw();
        if (tgjcqk_tw != null) {
            stmt.bindString(19, tgjcqk_tw);
        }
 
        String tgjcqk_yypj = entity.getTgjcqk_yypj();
        if (tgjcqk_yypj != null) {
            stmt.bindString(20, tgjcqk_yypj);
        }
 
        String tgjcqk_ms = entity.getTgjcqk_ms();
        if (tgjcqk_ms != null) {
            stmt.bindString(21, tgjcqk_ms);
        }
 
        Boolean tgjcqk_sfqxbh = entity.getTgjcqk_sfqxbh();
        if (tgjcqk_sfqxbh != null) {
            stmt.bindLong(22, tgjcqk_sfqxbh ? 1l: 0l);
        }
 
        String tgjcqk_sfqxbhms = entity.getTgjcqk_sfqxbhms();
        if (tgjcqk_sfqxbhms != null) {
            stmt.bindString(23, tgjcqk_sfqxbhms);
        }
 
        Boolean tgjcqk_sfpfyc = entity.getTgjcqk_sfpfyc();
        if (tgjcqk_sfpfyc != null) {
            stmt.bindLong(24, tgjcqk_sfpfyc ? 1l: 0l);
        }
 
        String tgjcqk_sfpfycms = entity.getTgjcqk_sfpfycms();
        if (tgjcqk_sfpfycms != null) {
            stmt.bindString(25, tgjcqk_sfpfycms);
        }
 
        Boolean tgjcqk_sfywgyc = entity.getTgjcqk_sfywgyc();
        if (tgjcqk_sfywgyc != null) {
            stmt.bindLong(26, tgjcqk_sfywgyc ? 1l: 0l);
        }
 
        String tgjcqk_sfywgycms = entity.getTgjcqk_sfywgycms();
        if (tgjcqk_sfywgycms != null) {
            stmt.bindString(27, tgjcqk_sfywgycms);
        }
 
        Boolean tgjcqk_sfewgyc = entity.getTgjcqk_sfewgyc();
        if (tgjcqk_sfewgyc != null) {
            stmt.bindLong(28, tgjcqk_sfewgyc ? 1l: 0l);
        }
 
        String tgjcqk_sfewgycms = entity.getTgjcqk_sfewgycms();
        if (tgjcqk_sfewgycms != null) {
            stmt.bindString(29, tgjcqk_sfewgycms);
        }
 
        Boolean tgjcqk_sftlyc = entity.getTgjcqk_sftlyc();
        if (tgjcqk_sftlyc != null) {
            stmt.bindLong(30, tgjcqk_sftlyc ? 1l: 0l);
        }
 
        String tgjcqk_sftlycms = entity.getTgjcqk_sftlycms();
        if (tgjcqk_sftlycms != null) {
            stmt.bindString(31, tgjcqk_sftlycms);
        }
 
        String tgjcqk_cyqcs = entity.getTgjcqk_cyqcs();
        if (tgjcqk_cyqcs != null) {
            stmt.bindString(32, tgjcqk_cyqcs);
        }
 
        String tgjcqk_cyqcsjl = entity.getTgjcqk_cyqcsjl();
        if (tgjcqk_cyqcsjl != null) {
            stmt.bindString(33, tgjcqk_cyqcsjl);
        }
 
        Boolean tgjcqk_sfxftzyc = entity.getTgjcqk_sfxftzyc();
        if (tgjcqk_sfxftzyc != null) {
            stmt.bindLong(34, tgjcqk_sfxftzyc ? 1l: 0l);
        }
 
        String tgjcqk_sfxftzycms = entity.getTgjcqk_sfxftzycms();
        if (tgjcqk_sfxftzycms != null) {
            stmt.bindString(35, tgjcqk_sfxftzycms);
        }
 
        Boolean tgjcqk_sffbczyc = entity.getTgjcqk_sffbczyc();
        if (tgjcqk_sffbczyc != null) {
            stmt.bindLong(36, tgjcqk_sffbczyc ? 1l: 0l);
        }
 
        String tgjcqk_sffbczycms = entity.getTgjcqk_sffbczycms();
        if (tgjcqk_sffbczycms != null) {
            stmt.bindString(37, tgjcqk_sffbczycms);
        }
 
        Boolean tgjcqk_sfszhddyc = entity.getTgjcqk_sfszhddyc();
        if (tgjcqk_sfszhddyc != null) {
            stmt.bindLong(38, tgjcqk_sfszhddyc ? 1l: 0l);
        }
 
        String tgjcqk_sfszhddycms = entity.getTgjcqk_sfszhddycms();
        if (tgjcqk_sfszhddycms != null) {
            stmt.bindString(39, tgjcqk_sfszhddycms);
        }
 
        Boolean tgjcqk_sfwszqyc = entity.getTgjcqk_sfwszqyc();
        if (tgjcqk_sfwszqyc != null) {
            stmt.bindLong(40, tgjcqk_sfwszqyc ? 1l: 0l);
        }
 
        String tgjcqk_sfwszqycms = entity.getTgjcqk_sfwszqycms();
        if (tgjcqk_sfwszqycms != null) {
            stmt.bindString(41, tgjcqk_sfwszqycms);
        }
 
        String tgjcqk_glbtz = entity.getTgjcqk_glbtz();
        if (tgjcqk_glbtz != null) {
            stmt.bindString(42, tgjcqk_glbtz);
        }
 
        Boolean fysc_hyysjbbmm = entity.getFysc_hyysjbbmm();
        if (fysc_hyysjbbmm != null) {
            stmt.bindLong(43, fysc_hyysjbbmm ? 1l: 0l);
        }
 
        Boolean fysc_hyszrdxhtp = entity.getFysc_hyszrdxhtp();
        if (fysc_hyszrdxhtp != null) {
            stmt.bindLong(44, fysc_hyszrdxhtp ? 1l: 0l);
        }
 
        Boolean fysc_zjdzw = entity.getFysc_zjdzw();
        if (fysc_zjdzw != null) {
            stmt.bindLong(45, fysc_zjdzw ? 1l: 0l);
        }
 
        Boolean fysc_hjwjfdbzhwl = entity.getFysc_hjwjfdbzhwl();
        if (fysc_hjwjfdbzhwl != null) {
            stmt.bindLong(46, fysc_hjwjfdbzhwl ? 1l: 0l);
        }
 
        Boolean fysc_nzjdxbzql = entity.getFysc_nzjdxbzql();
        if (fysc_nzjdxbzql != null) {
            stmt.bindLong(47, fysc_nzjdxbzql ? 1l: 0l);
        }
 
        Boolean fysc_hssgysddz = entity.getFysc_hssgysddz();
        if (fysc_hssgysddz != null) {
            stmt.bindLong(48, fysc_hssgysddz ? 1l: 0l);
        }
 
        Boolean fysc_hzrzjwghstbw = entity.getFysc_hzrzjwghstbw();
        if (fysc_hzrzjwghstbw != null) {
            stmt.bindLong(49, fysc_hzrzjwghstbw ? 1l: 0l);
        }
 
        Boolean fysc_nwcjdzlrbqfzs = entity.getFysc_nwcjdzlrbqfzs();
        if (fysc_nwcjdzlrbqfzs != null) {
            stmt.bindLong(50, fysc_nwcjdzlrbqfzs ? 1l: 0l);
        }
 
        Boolean fysc_hzjp = entity.getFysc_hzjp();
        if (fysc_hzjp != null) {
            stmt.bindLong(51, fysc_hzjp ? 1l: 0l);
        }
 
        Boolean fysc_hdg37kjmhwj = entity.getFysc_hdg37kjmhwj();
        if (fysc_hdg37kjmhwj != null) {
            stmt.bindLong(52, fysc_hdg37kjmhwj ? 1l: 0l);
        }
 
        String xhdbz = entity.getXhdbz();
        if (xhdbz != null) {
            stmt.bindString(53, xhdbz);
        }
 
        String sysjc = entity.getSysjc();
        if (sysjc != null) {
            stmt.bindString(54, sysjc);
        }
 
        String fzjc = entity.getFzjc();
        if (fzjc != null) {
            stmt.bindString(55, fzjc);
        }
 
        String hwhd = entity.getHwhd();
        if (hwhd != null) {
            stmt.bindString(56, hwhd);
        }
 
        Boolean fypg_sftg = entity.getFypg_sftg();
        if (fypg_sftg != null) {
            stmt.bindLong(57, fypg_sftg ? 1l: 0l);
        }
 
        Boolean hbqk_sfhb = entity.getHbqk_sfhb();
        if (hbqk_sfhb != null) {
            stmt.bindLong(58, hbqk_sfhb ? 1l: 0l);
        }
 
        String hbqk_sfhbms = entity.getHbqk_sfhbms();
        if (hbqk_sfhbms != null) {
            stmt.bindString(59, hbqk_sfhbms);
        }
 
        String jbzd = entity.getJbzd();
        if (jbzd != null) {
            stmt.bindString(60, jbzd);
        }
 
        Boolean yyxjbgl_sfyyxjb = entity.getYyxjbgl_sfyyxjb();
        if (yyxjbgl_sfyyxjb != null) {
            stmt.bindLong(61, yyxjbgl_sfyyxjb ? 1l: 0l);
        }
 
        Boolean yyxjbgl_sfgwe = entity.getYyxjbgl_sfgwe();
        if (yyxjbgl_sfgwe != null) {
            stmt.bindLong(62, yyxjbgl_sfgwe ? 1l: 0l);
        }
 
        Boolean zz_sfzz = entity.getZz_sfzz();
        if (zz_sfzz != null) {
            stmt.bindLong(63, zz_sfzz ? 1l: 0l);
        }
 
        String zz_yy = entity.getZz_yy();
        if (zz_yy != null) {
            stmt.bindString(64, zz_yy);
        }
 
        String zz_jgjks = entity.getZz_jgjks();
        if (zz_jgjks != null) {
            stmt.bindString(65, zz_jgjks);
        }
 
        String zd_zd = entity.getZd_zd();
        if (zd_zd != null) {
            stmt.bindString(66, zd_zd);
        }
 
        String zd_yzhjy = entity.getZd_yzhjy();
        if (zd_yzhjy != null) {
            stmt.bindString(67, zd_yzhjy);
        }
 
        String zd_xcsfrq = entity.getZd_xcsfrq();
        if (zd_xcsfrq != null) {
            stmt.bindString(68, zd_xcsfrq);
        }
 
        String zd_sfysqm = entity.getZd_sfysqm();
        if (zd_sfysqm != null) {
            stmt.bindString(69, zd_sfysqm);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(70, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(71, updateTime);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpOneTwoNewborn readEntity(Cursor cursor, int offset) {
        FollowUpOneTwoNewborn entity = new FollowUpOneTwoNewborn( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_fsrq
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grxx_ynl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grxx_csrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // grxx_zrys
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // wyqk_sfmryy
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // wyqk_sfmryyms
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // wyqk_zccs
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // wyqk_nnnf
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // wyqk_d
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // wyqk_rlhyx
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // wyqk_sghsc
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // wyqk_sy
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // wyqk_fywssd
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // tgjcqk_tz
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tgjcqk_sc
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // tgjcqk_bmi
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // tgjcqk_tw
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // tgjcqk_yypj
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // tgjcqk_ms
            cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0, // tgjcqk_sfqxbh
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // tgjcqk_sfqxbhms
            cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0, // tgjcqk_sfpfyc
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // tgjcqk_sfpfycms
            cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0, // tgjcqk_sfywgyc
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // tgjcqk_sfywgycms
            cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0, // tgjcqk_sfewgyc
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // tgjcqk_sfewgycms
            cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0, // tgjcqk_sftlyc
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // tgjcqk_sftlycms
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // tgjcqk_cyqcs
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // tgjcqk_cyqcsjl
            cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33) != 0, // tgjcqk_sfxftzyc
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // tgjcqk_sfxftzycms
            cursor.isNull(offset + 35) ? null : cursor.getShort(offset + 35) != 0, // tgjcqk_sffbczyc
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // tgjcqk_sffbczycms
            cursor.isNull(offset + 37) ? null : cursor.getShort(offset + 37) != 0, // tgjcqk_sfszhddyc
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // tgjcqk_sfszhddycms
            cursor.isNull(offset + 39) ? null : cursor.getShort(offset + 39) != 0, // tgjcqk_sfwszqyc
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // tgjcqk_sfwszqycms
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // tgjcqk_glbtz
            cursor.isNull(offset + 42) ? null : cursor.getShort(offset + 42) != 0, // fysc_hyysjbbmm
            cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43) != 0, // fysc_hyszrdxhtp
            cursor.isNull(offset + 44) ? null : cursor.getShort(offset + 44) != 0, // fysc_zjdzw
            cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45) != 0, // fysc_hjwjfdbzhwl
            cursor.isNull(offset + 46) ? null : cursor.getShort(offset + 46) != 0, // fysc_nzjdxbzql
            cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0, // fysc_hssgysddz
            cursor.isNull(offset + 48) ? null : cursor.getShort(offset + 48) != 0, // fysc_hzrzjwghstbw
            cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49) != 0, // fysc_nwcjdzlrbqfzs
            cursor.isNull(offset + 50) ? null : cursor.getShort(offset + 50) != 0, // fysc_hzjp
            cursor.isNull(offset + 51) ? null : cursor.getShort(offset + 51) != 0, // fysc_hdg37kjmhwj
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // xhdbz
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // sysjc
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // fzjc
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // hwhd
            cursor.isNull(offset + 56) ? null : cursor.getShort(offset + 56) != 0, // fypg_sftg
            cursor.isNull(offset + 57) ? null : cursor.getShort(offset + 57) != 0, // hbqk_sfhb
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // hbqk_sfhbms
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // jbzd
            cursor.isNull(offset + 60) ? null : cursor.getShort(offset + 60) != 0, // yyxjbgl_sfyyxjb
            cursor.isNull(offset + 61) ? null : cursor.getShort(offset + 61) != 0, // yyxjbgl_sfgwe
            cursor.isNull(offset + 62) ? null : cursor.getShort(offset + 62) != 0, // zz_sfzz
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // zz_yy
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // zz_jgjks
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // zd_zd
            cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66), // zd_yzhjy
            cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67), // zd_xcsfrq
            cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68), // zd_sfysqm
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // createTime
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpOneTwoNewborn entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_fsrq(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrxx_ynl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrxx_csrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGrxx_zrys(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWyqk_sfmryy(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setWyqk_sfmryyms(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWyqk_zccs(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWyqk_nnnf(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWyqk_d(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWyqk_rlhyx(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setWyqk_sghsc(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setWyqk_sy(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setWyqk_fywssd(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTgjcqk_tz(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTgjcqk_sc(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTgjcqk_bmi(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTgjcqk_tw(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTgjcqk_yypj(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTgjcqk_ms(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTgjcqk_sfqxbh(cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0);
        entity.setTgjcqk_sfqxbhms(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTgjcqk_sfpfyc(cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0);
        entity.setTgjcqk_sfpfycms(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setTgjcqk_sfywgyc(cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0);
        entity.setTgjcqk_sfywgycms(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setTgjcqk_sfewgyc(cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0);
        entity.setTgjcqk_sfewgycms(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTgjcqk_sftlyc(cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0);
        entity.setTgjcqk_sftlycms(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTgjcqk_cyqcs(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTgjcqk_cyqcsjl(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTgjcqk_sfxftzyc(cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33) != 0);
        entity.setTgjcqk_sfxftzycms(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setTgjcqk_sffbczyc(cursor.isNull(offset + 35) ? null : cursor.getShort(offset + 35) != 0);
        entity.setTgjcqk_sffbczycms(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setTgjcqk_sfszhddyc(cursor.isNull(offset + 37) ? null : cursor.getShort(offset + 37) != 0);
        entity.setTgjcqk_sfszhddycms(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setTgjcqk_sfwszqyc(cursor.isNull(offset + 39) ? null : cursor.getShort(offset + 39) != 0);
        entity.setTgjcqk_sfwszqycms(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setTgjcqk_glbtz(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setFysc_hyysjbbmm(cursor.isNull(offset + 42) ? null : cursor.getShort(offset + 42) != 0);
        entity.setFysc_hyszrdxhtp(cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43) != 0);
        entity.setFysc_zjdzw(cursor.isNull(offset + 44) ? null : cursor.getShort(offset + 44) != 0);
        entity.setFysc_hjwjfdbzhwl(cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45) != 0);
        entity.setFysc_nzjdxbzql(cursor.isNull(offset + 46) ? null : cursor.getShort(offset + 46) != 0);
        entity.setFysc_hssgysddz(cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0);
        entity.setFysc_hzrzjwghstbw(cursor.isNull(offset + 48) ? null : cursor.getShort(offset + 48) != 0);
        entity.setFysc_nwcjdzlrbqfzs(cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49) != 0);
        entity.setFysc_hzjp(cursor.isNull(offset + 50) ? null : cursor.getShort(offset + 50) != 0);
        entity.setFysc_hdg37kjmhwj(cursor.isNull(offset + 51) ? null : cursor.getShort(offset + 51) != 0);
        entity.setXhdbz(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setSysjc(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setFzjc(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setHwhd(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setFypg_sftg(cursor.isNull(offset + 56) ? null : cursor.getShort(offset + 56) != 0);
        entity.setHbqk_sfhb(cursor.isNull(offset + 57) ? null : cursor.getShort(offset + 57) != 0);
        entity.setHbqk_sfhbms(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setJbzd(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setYyxjbgl_sfyyxjb(cursor.isNull(offset + 60) ? null : cursor.getShort(offset + 60) != 0);
        entity.setYyxjbgl_sfgwe(cursor.isNull(offset + 61) ? null : cursor.getShort(offset + 61) != 0);
        entity.setZz_sfzz(cursor.isNull(offset + 62) ? null : cursor.getShort(offset + 62) != 0);
        entity.setZz_yy(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setZz_jgjks(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setZd_zd(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setZd_yzhjy(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
        entity.setZd_xcsfrq(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setZd_sfysqm(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setCreateTime(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setUpdateTime(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpOneTwoNewborn entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpOneTwoNewborn entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
