package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpPostpartum;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_POSTPARTUM.
*/
public class FollowUpPostpartumDao extends AbstractDao<FollowUpPostpartum, String> {

    public static final String TABLENAME = "FOLLOW_UP_POSTPARTUM";

    /**
     * Properties of entity FollowUpPostpartum.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_fsrq = new Property(2, String.class, "grxx_fsrq", false, "GRXX_FSRQ");
        public final static Property Jbjc_tw = new Property(3, String.class, "jbjc_tw", false, "JBJC_TW");
        public final static Property Jbjc_xy = new Property(4, String.class, "jbjc_xy", false, "JBJC_XY");
        public final static Property Jbjc_mb = new Property(5, String.class, "jbjc_mb", false, "JBJC_MB");
        public final static Property Xljkzk_xlzk = new Property(6, String.class, "xljkzk_xlzk", false, "XLJKZK_XLZK");
        public final static Property Xljkzk_smzk = new Property(7, String.class, "xljkzk_smzk", false, "XLJKZK_SMZK");
        public final static Property Xljkzk_jkzk = new Property(8, String.class, "xljkzk_jkzk", false, "XLJKZK_JKZK");
        public final static Property Rfjc_zcrx = new Property(9, String.class, "rfjc_zcrx", false, "RFJC_ZCRX");
        public final static Property Rfjc_ycrx = new Property(10, String.class, "rfjc_ycrx", false, "RFJC_YCRX");
        public final static Property Chjc_sfelyc = new Property(11, Boolean.class, "chjc_sfelyc", false, "CHJC_SFELYC");
        public final static Property Chjc_sfelycms = new Property(12, String.class, "chjc_sfelycms", false, "CHJC_SFELYCMS");
        public final static Property Chjc_sfzgyc = new Property(13, Boolean.class, "chjc_sfzgyc", false, "CHJC_SFZGYC");
        public final static Property Chjc_sfzgycms = new Property(14, String.class, "chjc_sfzgycms", false, "CHJC_SFZGYCMS");
        public final static Property Chjc_sfskyc = new Property(15, Boolean.class, "chjc_sfskyc", false, "CHJC_SFSKYC");
        public final static Property Chjc_sfskycms = new Property(16, String.class, "chjc_sfskycms", false, "CHJC_SFSKYCMS");
        public final static Property Chjc_skyhzk = new Property(17, String.class, "chjc_skyhzk", false, "CHJC_SKYHZK");
        public final static Property Chjc_qt = new Property(18, String.class, "chjc_qt", false, "CHJC_QT");
        public final static Property Zd_name = new Property(19, String.class, "zd_name", false, "ZD_NAME");
        public final static Property Zz_sfygzz = new Property(20, Boolean.class, "zz_sfygzz", false, "ZZ_SFYGZZ");
        public final static Property Zz_yy = new Property(21, String.class, "zz_yy", false, "ZZ_YY");
        public final static Property Zz_jgjks = new Property(22, String.class, "zz_jgjks", false, "ZZ_JGJKS");
        public final static Property Zz_xcsfrq = new Property(23, String.class, "zz_xcsfrq", false, "ZZ_XCSFRQ");
        public final static Property Ztpg_sfysqm = new Property(24, String.class, "ztpg_sfysqm", false, "ZTPG_SFYSQM");
        public final static Property CreateTime = new Property(25, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(26, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public FollowUpPostpartumDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpPostpartumDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_POSTPARTUM' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_FSRQ' TEXT," + // 2: grxx_fsrq
                "'JBJC_TW' TEXT," + // 3: jbjc_tw
                "'JBJC_XY' TEXT," + // 4: jbjc_xy
                "'JBJC_MB' TEXT," + // 5: jbjc_mb
                "'XLJKZK_XLZK' TEXT," + // 6: xljkzk_xlzk
                "'XLJKZK_SMZK' TEXT," + // 7: xljkzk_smzk
                "'XLJKZK_JKZK' TEXT," + // 8: xljkzk_jkzk
                "'RFJC_ZCRX' TEXT," + // 9: rfjc_zcrx
                "'RFJC_YCRX' TEXT," + // 10: rfjc_ycrx
                "'CHJC_SFELYC' INTEGER," + // 11: chjc_sfelyc
                "'CHJC_SFELYCMS' TEXT," + // 12: chjc_sfelycms
                "'CHJC_SFZGYC' INTEGER," + // 13: chjc_sfzgyc
                "'CHJC_SFZGYCMS' TEXT," + // 14: chjc_sfzgycms
                "'CHJC_SFSKYC' INTEGER," + // 15: chjc_sfskyc
                "'CHJC_SFSKYCMS' TEXT," + // 16: chjc_sfskycms
                "'CHJC_SKYHZK' TEXT," + // 17: chjc_skyhzk
                "'CHJC_QT' TEXT," + // 18: chjc_qt
                "'ZD_NAME' TEXT," + // 19: zd_name
                "'ZZ_SFYGZZ' INTEGER," + // 20: zz_sfygzz
                "'ZZ_YY' TEXT," + // 21: zz_yy
                "'ZZ_JGJKS' TEXT," + // 22: zz_jgjks
                "'ZZ_XCSFRQ' TEXT," + // 23: zz_xcsfrq
                "'ZTPG_SFYSQM' TEXT," + // 24: ztpg_sfysqm
                "'CREATE_TIME' TEXT," + // 25: createTime
                "'UPDATE_TIME' TEXT);"); // 26: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_POSTPARTUM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpPostpartum entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_fsrq = entity.getGrxx_fsrq();
        if (grxx_fsrq != null) {
            stmt.bindString(3, grxx_fsrq);
        }
 
        String jbjc_tw = entity.getJbjc_tw();
        if (jbjc_tw != null) {
            stmt.bindString(4, jbjc_tw);
        }
 
        String jbjc_xy = entity.getJbjc_xy();
        if (jbjc_xy != null) {
            stmt.bindString(5, jbjc_xy);
        }
 
        String jbjc_mb = entity.getJbjc_mb();
        if (jbjc_mb != null) {
            stmt.bindString(6, jbjc_mb);
        }
 
        String xljkzk_xlzk = entity.getXljkzk_xlzk();
        if (xljkzk_xlzk != null) {
            stmt.bindString(7, xljkzk_xlzk);
        }
 
        String xljkzk_smzk = entity.getXljkzk_smzk();
        if (xljkzk_smzk != null) {
            stmt.bindString(8, xljkzk_smzk);
        }
 
        String xljkzk_jkzk = entity.getXljkzk_jkzk();
        if (xljkzk_jkzk != null) {
            stmt.bindString(9, xljkzk_jkzk);
        }
 
        String rfjc_zcrx = entity.getRfjc_zcrx();
        if (rfjc_zcrx != null) {
            stmt.bindString(10, rfjc_zcrx);
        }
 
        String rfjc_ycrx = entity.getRfjc_ycrx();
        if (rfjc_ycrx != null) {
            stmt.bindString(11, rfjc_ycrx);
        }
 
        Boolean chjc_sfelyc = entity.getChjc_sfelyc();
        if (chjc_sfelyc != null) {
            stmt.bindLong(12, chjc_sfelyc ? 1l: 0l);
        }
 
        String chjc_sfelycms = entity.getChjc_sfelycms();
        if (chjc_sfelycms != null) {
            stmt.bindString(13, chjc_sfelycms);
        }
 
        Boolean chjc_sfzgyc = entity.getChjc_sfzgyc();
        if (chjc_sfzgyc != null) {
            stmt.bindLong(14, chjc_sfzgyc ? 1l: 0l);
        }
 
        String chjc_sfzgycms = entity.getChjc_sfzgycms();
        if (chjc_sfzgycms != null) {
            stmt.bindString(15, chjc_sfzgycms);
        }
 
        Boolean chjc_sfskyc = entity.getChjc_sfskyc();
        if (chjc_sfskyc != null) {
            stmt.bindLong(16, chjc_sfskyc ? 1l: 0l);
        }
 
        String chjc_sfskycms = entity.getChjc_sfskycms();
        if (chjc_sfskycms != null) {
            stmt.bindString(17, chjc_sfskycms);
        }
 
        String chjc_skyhzk = entity.getChjc_skyhzk();
        if (chjc_skyhzk != null) {
            stmt.bindString(18, chjc_skyhzk);
        }
 
        String chjc_qt = entity.getChjc_qt();
        if (chjc_qt != null) {
            stmt.bindString(19, chjc_qt);
        }
 
        String zd_name = entity.getZd_name();
        if (zd_name != null) {
            stmt.bindString(20, zd_name);
        }
 
        Boolean zz_sfygzz = entity.getZz_sfygzz();
        if (zz_sfygzz != null) {
            stmt.bindLong(21, zz_sfygzz ? 1l: 0l);
        }
 
        String zz_yy = entity.getZz_yy();
        if (zz_yy != null) {
            stmt.bindString(22, zz_yy);
        }
 
        String zz_jgjks = entity.getZz_jgjks();
        if (zz_jgjks != null) {
            stmt.bindString(23, zz_jgjks);
        }
 
        String zz_xcsfrq = entity.getZz_xcsfrq();
        if (zz_xcsfrq != null) {
            stmt.bindString(24, zz_xcsfrq);
        }
 
        String ztpg_sfysqm = entity.getZtpg_sfysqm();
        if (ztpg_sfysqm != null) {
            stmt.bindString(25, ztpg_sfysqm);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(26, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(27, updateTime);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpPostpartum readEntity(Cursor cursor, int offset) {
        FollowUpPostpartum entity = new FollowUpPostpartum( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_fsrq
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // jbjc_tw
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jbjc_xy
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jbjc_mb
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // xljkzk_xlzk
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // xljkzk_smzk
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // xljkzk_jkzk
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // rfjc_zcrx
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // rfjc_ycrx
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // chjc_sfelyc
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // chjc_sfelycms
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // chjc_sfzgyc
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // chjc_sfzgycms
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // chjc_sfskyc
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // chjc_sfskycms
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // chjc_skyhzk
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // chjc_qt
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // zd_name
            cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0, // zz_sfygzz
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // zz_yy
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // zz_jgjks
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // zz_xcsfrq
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // ztpg_sfysqm
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // createTime
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpPostpartum entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_fsrq(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setJbjc_tw(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJbjc_xy(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJbjc_mb(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setXljkzk_xlzk(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setXljkzk_smzk(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setXljkzk_jkzk(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRfjc_zcrx(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRfjc_ycrx(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setChjc_sfelyc(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setChjc_sfelycms(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setChjc_sfzgyc(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setChjc_sfzgycms(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setChjc_sfskyc(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setChjc_sfskycms(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setChjc_skyhzk(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setChjc_qt(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setZd_name(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setZz_sfygzz(cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0);
        entity.setZz_yy(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setZz_jgjks(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setZz_xcsfrq(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setZtpg_sfysqm(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setCreateTime(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setUpdateTime(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpPostpartum entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpPostpartum entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
