package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpNewborn;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_NEWBORN.
*/
public class FollowUpNewbornDao extends AbstractDao<FollowUpNewborn, String> {

    public static final String TABLENAME = "FOLLOW_UP_NEWBORN";

    /**
     * Properties of entity FollowUpNewborn.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_fsrq = new Property(2, String.class, "grxx_fsrq", false, "GRXX_FSRQ");
        public final static Property Grxx_fscs = new Property(3, String.class, "grxx_fscs", false, "GRXX_FSCS");
        public final static Property Grxx_csrl = new Property(4, String.class, "grxx_csrl", false, "GRXX_CSRL");
        public final static Property Grxx_zrys = new Property(5, String.class, "grxx_zrys", false, "GRXX_ZRYS");
        public final static Property Wyqk_wyfs = new Property(6, String.class, "wyqk_wyfs", false, "WYQK_WYFS");
        public final static Property Wyqk_cnl = new Property(7, String.class, "wyqk_cnl", false, "WYQK_CNL");
        public final static Property Wyqk_cncs = new Property(8, String.class, "wyqk_cncs", false, "WYQK_CNCS");
        public final static Property Wyqk_sfot = new Property(9, Boolean.class, "wyqk_sfot", false, "WYQK_SFOT");
        public final static Property Jbstzk_dbxz = new Property(10, String.class, "jbstzk_dbxz", false, "JBSTZK_DBXZ");
        public final static Property Jbstzk_dbcs = new Property(11, String.class, "jbstzk_dbcs", false, "JBSTZK_DBCS");
        public final static Property Jbstzk_dbys = new Property(12, String.class, "jbstzk_dbys", false, "JBSTZK_DBYS");
        public final static Property Jbstzk_smwt = new Property(13, String.class, "jbstzk_smwt", false, "JBSTZK_SMWT");
        public final static Property Gwe_sfgwe = new Property(14, Boolean.class, "gwe_sfgwe", false, "GWE_SFGWE");
        public final static Property Tgjcqk_mqtz = new Property(15, String.class, "tgjcqk_mqtz", false, "TGJCQK_MQTZ");
        public final static Property Tgjcqk_tw = new Property(16, String.class, "tgjcqk_tw", false, "TGJCQK_TW");
        public final static Property Tgjcqk_sc = new Property(17, String.class, "tgjcqk_sc", false, "TGJCQK_SC");
        public final static Property Tgjcqk_hxpl = new Property(18, String.class, "tgjcqk_hxpl", false, "TGJCQK_HXPL");
        public final static Property Tgjcqk_ml = new Property(19, String.class, "tgjcqk_ml", false, "TGJCQK_ML");
        public final static Property Tgjcqk_ms = new Property(20, String.class, "tgjcqk_ms", false, "TGJCQK_MS");
        public final static Property Tgjcqk_hdbw = new Property(21, String.class, "tgjcqk_hdbw", false, "TGJCQK_HDBW");
        public final static Property Tgjcqk_qx = new Property(22, String.class, "tgjcqk_qx", false, "TGJCQK_QX");
        public final static Property Tgjcqk_qxjl = new Property(23, String.class, "tgjcqk_qxjl", false, "TGJCQK_QXJL");
        public final static Property Tgjcqk_sfywgyc = new Property(24, Boolean.class, "tgjcqk_sfywgyc", false, "TGJCQK_SFYWGYC");
        public final static Property Tgjcqk_sfywgycms = new Property(25, String.class, "tgjcqk_sfywgycms", false, "TGJCQK_SFYWGYCMS");
        public final static Property Tgjcqk_sfewgyc = new Property(26, Boolean.class, "tgjcqk_sfewgyc", false, "TGJCQK_SFEWGYC");
        public final static Property Tgjcqk_sfewgycms = new Property(27, String.class, "tgjcqk_sfewgycms", false, "TGJCQK_SFEWGYCMS");
        public final static Property Tgjcqk_sfbyc = new Property(28, Boolean.class, "tgjcqk_sfbyc", false, "TGJCQK_SFBYC");
        public final static Property Tgjcqk_sfbycms = new Property(29, String.class, "tgjcqk_sfbycms", false, "TGJCQK_SFBYCMS");
        public final static Property Tgjcqk_sfkqyc = new Property(30, Boolean.class, "tgjcqk_sfkqyc", false, "TGJCQK_SFKQYC");
        public final static Property Tgjcqk_sfkqycms = new Property(31, String.class, "tgjcqk_sfkqycms", false, "TGJCQK_SFKQYCMS");
        public final static Property Tgjcqk_sfxftzyc = new Property(32, Boolean.class, "tgjcqk_sfxftzyc", false, "TGJCQK_SFXFTZYC");
        public final static Property Tgjcqk_sfxftzycms = new Property(33, String.class, "tgjcqk_sfxftzycms", false, "TGJCQK_SFXFTZYCMS");
        public final static Property Tgjcqk_sffbczyc = new Property(34, Boolean.class, "tgjcqk_sffbczyc", false, "TGJCQK_SFFBCZYC");
        public final static Property Tgjcqk_sffbczycms = new Property(35, String.class, "tgjcqk_sffbczycms", false, "TGJCQK_SFFBCZYCMS");
        public final static Property Tgjcqk_sfszhddyc = new Property(36, Boolean.class, "tgjcqk_sfszhddyc", false, "TGJCQK_SFSZHDDYC");
        public final static Property Tgjcqk_sfszhddycms = new Property(37, String.class, "tgjcqk_sfszhddycms", false, "TGJCQK_SFSZHDDYCMS");
        public final static Property Tgjcqk_sfjbbkyc = new Property(38, Boolean.class, "tgjcqk_sfjbbkyc", false, "TGJCQK_SFJBBKYC");
        public final static Property Tgjcqk_sfjbbkycms = new Property(39, String.class, "tgjcqk_sfjbbkycms", false, "TGJCQK_SFJBBKYCMS");
        public final static Property Tgjcqk_pf = new Property(40, String.class, "tgjcqk_pf", false, "TGJCQK_PF");
        public final static Property Tgjcqk_sfgmyc = new Property(41, Boolean.class, "tgjcqk_sfgmyc", false, "TGJCQK_SFGMYC");
        public final static Property Tgjcqk_sfgmycms = new Property(42, String.class, "tgjcqk_sfgmycms", false, "TGJCQK_SFGMYCMS");
        public final static Property Tgjcqk_sfwszqyc = new Property(43, Boolean.class, "tgjcqk_sfwszqyc", false, "TGJCQK_SFWSZQYC");
        public final static Property Tgjcqk_sfwszqycms = new Property(44, String.class, "tgjcqk_sfwszqycms", false, "TGJCQK_SFWSZQYCMS");
        public final static Property Tgjcqk_sfjzyc = new Property(45, Boolean.class, "tgjcqk_sfjzyc", false, "TGJCQK_SFJZYC");
        public final static Property Tgjcqk_sfjzycms = new Property(46, String.class, "tgjcqk_sfjzycms", false, "TGJCQK_SFJZYCMS");
        public final static Property Tgjcqk_sfqdyc = new Property(47, Boolean.class, "tgjcqk_sfqdyc", false, "TGJCQK_SFQDYC");
        public final static Property Tgjcqk_sfqdycms = new Property(48, String.class, "tgjcqk_sfqdycms", false, "TGJCQK_SFQDYCMS");
        public final static Property Zzjy_sfzz = new Property(49, Boolean.class, "zzjy_sfzz", false, "ZZJY_SFZZ");
        public final static Property Zzjy_yy = new Property(50, String.class, "zzjy_yy", false, "ZZJY_YY");
        public final static Property Zzjy_jgjks = new Property(51, String.class, "zzjy_jgjks", false, "ZZJY_JGJKS");
        public final static Property Zd_zdmc = new Property(52, String.class, "zd_zdmc", false, "ZD_ZDMC");
        public final static Property Zd_tsyzjcl = new Property(53, String.class, "zd_tsyzjcl", false, "ZD_TSYZJCL");
        public final static Property Zd_xcsfrq = new Property(54, String.class, "zd_xcsfrq", false, "ZD_XCSFRQ");
        public final static Property Zd_xcfsdd = new Property(55, String.class, "zd_xcfsdd", false, "ZD_XCFSDD");
        public final static Property Zd_sfysqm = new Property(56, String.class, "zd_sfysqm", false, "ZD_SFYSQM");
        public final static Property CreateTime = new Property(57, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(58, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public FollowUpNewbornDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpNewbornDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_NEWBORN' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_FSRQ' TEXT," + // 2: grxx_fsrq
                "'GRXX_FSCS' TEXT," + // 3: grxx_fscs
                "'GRXX_CSRL' TEXT," + // 4: grxx_csrl
                "'GRXX_ZRYS' TEXT," + // 5: grxx_zrys
                "'WYQK_WYFS' TEXT," + // 6: wyqk_wyfs
                "'WYQK_CNL' TEXT," + // 7: wyqk_cnl
                "'WYQK_CNCS' TEXT," + // 8: wyqk_cncs
                "'WYQK_SFOT' INTEGER," + // 9: wyqk_sfot
                "'JBSTZK_DBXZ' TEXT," + // 10: jbstzk_dbxz
                "'JBSTZK_DBCS' TEXT," + // 11: jbstzk_dbcs
                "'JBSTZK_DBYS' TEXT," + // 12: jbstzk_dbys
                "'JBSTZK_SMWT' TEXT," + // 13: jbstzk_smwt
                "'GWE_SFGWE' INTEGER," + // 14: gwe_sfgwe
                "'TGJCQK_MQTZ' TEXT," + // 15: tgjcqk_mqtz
                "'TGJCQK_TW' TEXT," + // 16: tgjcqk_tw
                "'TGJCQK_SC' TEXT," + // 17: tgjcqk_sc
                "'TGJCQK_HXPL' TEXT," + // 18: tgjcqk_hxpl
                "'TGJCQK_ML' TEXT," + // 19: tgjcqk_ml
                "'TGJCQK_MS' TEXT," + // 20: tgjcqk_ms
                "'TGJCQK_HDBW' TEXT," + // 21: tgjcqk_hdbw
                "'TGJCQK_QX' TEXT," + // 22: tgjcqk_qx
                "'TGJCQK_QXJL' TEXT," + // 23: tgjcqk_qxjl
                "'TGJCQK_SFYWGYC' INTEGER," + // 24: tgjcqk_sfywgyc
                "'TGJCQK_SFYWGYCMS' TEXT," + // 25: tgjcqk_sfywgycms
                "'TGJCQK_SFEWGYC' INTEGER," + // 26: tgjcqk_sfewgyc
                "'TGJCQK_SFEWGYCMS' TEXT," + // 27: tgjcqk_sfewgycms
                "'TGJCQK_SFBYC' INTEGER," + // 28: tgjcqk_sfbyc
                "'TGJCQK_SFBYCMS' TEXT," + // 29: tgjcqk_sfbycms
                "'TGJCQK_SFKQYC' INTEGER," + // 30: tgjcqk_sfkqyc
                "'TGJCQK_SFKQYCMS' TEXT," + // 31: tgjcqk_sfkqycms
                "'TGJCQK_SFXFTZYC' INTEGER," + // 32: tgjcqk_sfxftzyc
                "'TGJCQK_SFXFTZYCMS' TEXT," + // 33: tgjcqk_sfxftzycms
                "'TGJCQK_SFFBCZYC' INTEGER," + // 34: tgjcqk_sffbczyc
                "'TGJCQK_SFFBCZYCMS' TEXT," + // 35: tgjcqk_sffbczycms
                "'TGJCQK_SFSZHDDYC' INTEGER," + // 36: tgjcqk_sfszhddyc
                "'TGJCQK_SFSZHDDYCMS' TEXT," + // 37: tgjcqk_sfszhddycms
                "'TGJCQK_SFJBBKYC' INTEGER," + // 38: tgjcqk_sfjbbkyc
                "'TGJCQK_SFJBBKYCMS' TEXT," + // 39: tgjcqk_sfjbbkycms
                "'TGJCQK_PF' TEXT," + // 40: tgjcqk_pf
                "'TGJCQK_SFGMYC' INTEGER," + // 41: tgjcqk_sfgmyc
                "'TGJCQK_SFGMYCMS' TEXT," + // 42: tgjcqk_sfgmycms
                "'TGJCQK_SFWSZQYC' INTEGER," + // 43: tgjcqk_sfwszqyc
                "'TGJCQK_SFWSZQYCMS' TEXT," + // 44: tgjcqk_sfwszqycms
                "'TGJCQK_SFJZYC' INTEGER," + // 45: tgjcqk_sfjzyc
                "'TGJCQK_SFJZYCMS' TEXT," + // 46: tgjcqk_sfjzycms
                "'TGJCQK_SFQDYC' INTEGER," + // 47: tgjcqk_sfqdyc
                "'TGJCQK_SFQDYCMS' TEXT," + // 48: tgjcqk_sfqdycms
                "'ZZJY_SFZZ' INTEGER," + // 49: zzjy_sfzz
                "'ZZJY_YY' TEXT," + // 50: zzjy_yy
                "'ZZJY_JGJKS' TEXT," + // 51: zzjy_jgjks
                "'ZD_ZDMC' TEXT," + // 52: zd_zdmc
                "'ZD_TSYZJCL' TEXT," + // 53: zd_tsyzjcl
                "'ZD_XCSFRQ' TEXT," + // 54: zd_xcsfrq
                "'ZD_XCFSDD' TEXT," + // 55: zd_xcfsdd
                "'ZD_SFYSQM' TEXT," + // 56: zd_sfysqm
                "'CREATE_TIME' TEXT," + // 57: createTime
                "'UPDATE_TIME' TEXT);"); // 58: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_NEWBORN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpNewborn entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_fsrq = entity.getGrxx_fsrq();
        if (grxx_fsrq != null) {
            stmt.bindString(3, grxx_fsrq);
        }
 
        String grxx_fscs = entity.getGrxx_fscs();
        if (grxx_fscs != null) {
            stmt.bindString(4, grxx_fscs);
        }
 
        String grxx_csrl = entity.getGrxx_csrl();
        if (grxx_csrl != null) {
            stmt.bindString(5, grxx_csrl);
        }
 
        String grxx_zrys = entity.getGrxx_zrys();
        if (grxx_zrys != null) {
            stmt.bindString(6, grxx_zrys);
        }
 
        String wyqk_wyfs = entity.getWyqk_wyfs();
        if (wyqk_wyfs != null) {
            stmt.bindString(7, wyqk_wyfs);
        }
 
        String wyqk_cnl = entity.getWyqk_cnl();
        if (wyqk_cnl != null) {
            stmt.bindString(8, wyqk_cnl);
        }
 
        String wyqk_cncs = entity.getWyqk_cncs();
        if (wyqk_cncs != null) {
            stmt.bindString(9, wyqk_cncs);
        }
 
        Boolean wyqk_sfot = entity.getWyqk_sfot();
        if (wyqk_sfot != null) {
            stmt.bindLong(10, wyqk_sfot ? 1l: 0l);
        }
 
        String jbstzk_dbxz = entity.getJbstzk_dbxz();
        if (jbstzk_dbxz != null) {
            stmt.bindString(11, jbstzk_dbxz);
        }
 
        String jbstzk_dbcs = entity.getJbstzk_dbcs();
        if (jbstzk_dbcs != null) {
            stmt.bindString(12, jbstzk_dbcs);
        }
 
        String jbstzk_dbys = entity.getJbstzk_dbys();
        if (jbstzk_dbys != null) {
            stmt.bindString(13, jbstzk_dbys);
        }
 
        String jbstzk_smwt = entity.getJbstzk_smwt();
        if (jbstzk_smwt != null) {
            stmt.bindString(14, jbstzk_smwt);
        }
 
        Boolean gwe_sfgwe = entity.getGwe_sfgwe();
        if (gwe_sfgwe != null) {
            stmt.bindLong(15, gwe_sfgwe ? 1l: 0l);
        }
 
        String tgjcqk_mqtz = entity.getTgjcqk_mqtz();
        if (tgjcqk_mqtz != null) {
            stmt.bindString(16, tgjcqk_mqtz);
        }
 
        String tgjcqk_tw = entity.getTgjcqk_tw();
        if (tgjcqk_tw != null) {
            stmt.bindString(17, tgjcqk_tw);
        }
 
        String tgjcqk_sc = entity.getTgjcqk_sc();
        if (tgjcqk_sc != null) {
            stmt.bindString(18, tgjcqk_sc);
        }
 
        String tgjcqk_hxpl = entity.getTgjcqk_hxpl();
        if (tgjcqk_hxpl != null) {
            stmt.bindString(19, tgjcqk_hxpl);
        }
 
        String tgjcqk_ml = entity.getTgjcqk_ml();
        if (tgjcqk_ml != null) {
            stmt.bindString(20, tgjcqk_ml);
        }
 
        String tgjcqk_ms = entity.getTgjcqk_ms();
        if (tgjcqk_ms != null) {
            stmt.bindString(21, tgjcqk_ms);
        }
 
        String tgjcqk_hdbw = entity.getTgjcqk_hdbw();
        if (tgjcqk_hdbw != null) {
            stmt.bindString(22, tgjcqk_hdbw);
        }
 
        String tgjcqk_qx = entity.getTgjcqk_qx();
        if (tgjcqk_qx != null) {
            stmt.bindString(23, tgjcqk_qx);
        }
 
        String tgjcqk_qxjl = entity.getTgjcqk_qxjl();
        if (tgjcqk_qxjl != null) {
            stmt.bindString(24, tgjcqk_qxjl);
        }
 
        Boolean tgjcqk_sfywgyc = entity.getTgjcqk_sfywgyc();
        if (tgjcqk_sfywgyc != null) {
            stmt.bindLong(25, tgjcqk_sfywgyc ? 1l: 0l);
        }
 
        String tgjcqk_sfywgycms = entity.getTgjcqk_sfywgycms();
        if (tgjcqk_sfywgycms != null) {
            stmt.bindString(26, tgjcqk_sfywgycms);
        }
 
        Boolean tgjcqk_sfewgyc = entity.getTgjcqk_sfewgyc();
        if (tgjcqk_sfewgyc != null) {
            stmt.bindLong(27, tgjcqk_sfewgyc ? 1l: 0l);
        }
 
        String tgjcqk_sfewgycms = entity.getTgjcqk_sfewgycms();
        if (tgjcqk_sfewgycms != null) {
            stmt.bindString(28, tgjcqk_sfewgycms);
        }
 
        Boolean tgjcqk_sfbyc = entity.getTgjcqk_sfbyc();
        if (tgjcqk_sfbyc != null) {
            stmt.bindLong(29, tgjcqk_sfbyc ? 1l: 0l);
        }
 
        String tgjcqk_sfbycms = entity.getTgjcqk_sfbycms();
        if (tgjcqk_sfbycms != null) {
            stmt.bindString(30, tgjcqk_sfbycms);
        }
 
        Boolean tgjcqk_sfkqyc = entity.getTgjcqk_sfkqyc();
        if (tgjcqk_sfkqyc != null) {
            stmt.bindLong(31, tgjcqk_sfkqyc ? 1l: 0l);
        }
 
        String tgjcqk_sfkqycms = entity.getTgjcqk_sfkqycms();
        if (tgjcqk_sfkqycms != null) {
            stmt.bindString(32, tgjcqk_sfkqycms);
        }
 
        Boolean tgjcqk_sfxftzyc = entity.getTgjcqk_sfxftzyc();
        if (tgjcqk_sfxftzyc != null) {
            stmt.bindLong(33, tgjcqk_sfxftzyc ? 1l: 0l);
        }
 
        String tgjcqk_sfxftzycms = entity.getTgjcqk_sfxftzycms();
        if (tgjcqk_sfxftzycms != null) {
            stmt.bindString(34, tgjcqk_sfxftzycms);
        }
 
        Boolean tgjcqk_sffbczyc = entity.getTgjcqk_sffbczyc();
        if (tgjcqk_sffbczyc != null) {
            stmt.bindLong(35, tgjcqk_sffbczyc ? 1l: 0l);
        }
 
        String tgjcqk_sffbczycms = entity.getTgjcqk_sffbczycms();
        if (tgjcqk_sffbczycms != null) {
            stmt.bindString(36, tgjcqk_sffbczycms);
        }
 
        Boolean tgjcqk_sfszhddyc = entity.getTgjcqk_sfszhddyc();
        if (tgjcqk_sfszhddyc != null) {
            stmt.bindLong(37, tgjcqk_sfszhddyc ? 1l: 0l);
        }
 
        String tgjcqk_sfszhddycms = entity.getTgjcqk_sfszhddycms();
        if (tgjcqk_sfszhddycms != null) {
            stmt.bindString(38, tgjcqk_sfszhddycms);
        }
 
        Boolean tgjcqk_sfjbbkyc = entity.getTgjcqk_sfjbbkyc();
        if (tgjcqk_sfjbbkyc != null) {
            stmt.bindLong(39, tgjcqk_sfjbbkyc ? 1l: 0l);
        }
 
        String tgjcqk_sfjbbkycms = entity.getTgjcqk_sfjbbkycms();
        if (tgjcqk_sfjbbkycms != null) {
            stmt.bindString(40, tgjcqk_sfjbbkycms);
        }
 
        String tgjcqk_pf = entity.getTgjcqk_pf();
        if (tgjcqk_pf != null) {
            stmt.bindString(41, tgjcqk_pf);
        }
 
        Boolean tgjcqk_sfgmyc = entity.getTgjcqk_sfgmyc();
        if (tgjcqk_sfgmyc != null) {
            stmt.bindLong(42, tgjcqk_sfgmyc ? 1l: 0l);
        }
 
        String tgjcqk_sfgmycms = entity.getTgjcqk_sfgmycms();
        if (tgjcqk_sfgmycms != null) {
            stmt.bindString(43, tgjcqk_sfgmycms);
        }
 
        Boolean tgjcqk_sfwszqyc = entity.getTgjcqk_sfwszqyc();
        if (tgjcqk_sfwszqyc != null) {
            stmt.bindLong(44, tgjcqk_sfwszqyc ? 1l: 0l);
        }
 
        String tgjcqk_sfwszqycms = entity.getTgjcqk_sfwszqycms();
        if (tgjcqk_sfwszqycms != null) {
            stmt.bindString(45, tgjcqk_sfwszqycms);
        }
 
        Boolean tgjcqk_sfjzyc = entity.getTgjcqk_sfjzyc();
        if (tgjcqk_sfjzyc != null) {
            stmt.bindLong(46, tgjcqk_sfjzyc ? 1l: 0l);
        }
 
        String tgjcqk_sfjzycms = entity.getTgjcqk_sfjzycms();
        if (tgjcqk_sfjzycms != null) {
            stmt.bindString(47, tgjcqk_sfjzycms);
        }
 
        Boolean tgjcqk_sfqdyc = entity.getTgjcqk_sfqdyc();
        if (tgjcqk_sfqdyc != null) {
            stmt.bindLong(48, tgjcqk_sfqdyc ? 1l: 0l);
        }
 
        String tgjcqk_sfqdycms = entity.getTgjcqk_sfqdycms();
        if (tgjcqk_sfqdycms != null) {
            stmt.bindString(49, tgjcqk_sfqdycms);
        }
 
        Boolean zzjy_sfzz = entity.getZzjy_sfzz();
        if (zzjy_sfzz != null) {
            stmt.bindLong(50, zzjy_sfzz ? 1l: 0l);
        }
 
        String zzjy_yy = entity.getZzjy_yy();
        if (zzjy_yy != null) {
            stmt.bindString(51, zzjy_yy);
        }
 
        String zzjy_jgjks = entity.getZzjy_jgjks();
        if (zzjy_jgjks != null) {
            stmt.bindString(52, zzjy_jgjks);
        }
 
        String zd_zdmc = entity.getZd_zdmc();
        if (zd_zdmc != null) {
            stmt.bindString(53, zd_zdmc);
        }
 
        String zd_tsyzjcl = entity.getZd_tsyzjcl();
        if (zd_tsyzjcl != null) {
            stmt.bindString(54, zd_tsyzjcl);
        }
 
        String zd_xcsfrq = entity.getZd_xcsfrq();
        if (zd_xcsfrq != null) {
            stmt.bindString(55, zd_xcsfrq);
        }
 
        String zd_xcfsdd = entity.getZd_xcfsdd();
        if (zd_xcfsdd != null) {
            stmt.bindString(56, zd_xcfsdd);
        }
 
        String zd_sfysqm = entity.getZd_sfysqm();
        if (zd_sfysqm != null) {
            stmt.bindString(57, zd_sfysqm);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(58, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(59, updateTime);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpNewborn readEntity(Cursor cursor, int offset) {
        FollowUpNewborn entity = new FollowUpNewborn( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_fsrq
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grxx_fscs
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grxx_csrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // grxx_zrys
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // wyqk_wyfs
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // wyqk_cnl
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // wyqk_cncs
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // wyqk_sfot
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // jbstzk_dbxz
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // jbstzk_dbcs
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // jbstzk_dbys
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // jbstzk_smwt
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0, // gwe_sfgwe
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // tgjcqk_mqtz
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tgjcqk_tw
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // tgjcqk_sc
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // tgjcqk_hxpl
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // tgjcqk_ml
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // tgjcqk_ms
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // tgjcqk_hdbw
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // tgjcqk_qx
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // tgjcqk_qxjl
            cursor.isNull(offset + 24) ? null : cursor.getShort(offset + 24) != 0, // tgjcqk_sfywgyc
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // tgjcqk_sfywgycms
            cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26) != 0, // tgjcqk_sfewgyc
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // tgjcqk_sfewgycms
            cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0, // tgjcqk_sfbyc
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // tgjcqk_sfbycms
            cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30) != 0, // tgjcqk_sfkqyc
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // tgjcqk_sfkqycms
            cursor.isNull(offset + 32) ? null : cursor.getShort(offset + 32) != 0, // tgjcqk_sfxftzyc
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // tgjcqk_sfxftzycms
            cursor.isNull(offset + 34) ? null : cursor.getShort(offset + 34) != 0, // tgjcqk_sffbczyc
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // tgjcqk_sffbczycms
            cursor.isNull(offset + 36) ? null : cursor.getShort(offset + 36) != 0, // tgjcqk_sfszhddyc
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // tgjcqk_sfszhddycms
            cursor.isNull(offset + 38) ? null : cursor.getShort(offset + 38) != 0, // tgjcqk_sfjbbkyc
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // tgjcqk_sfjbbkycms
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // tgjcqk_pf
            cursor.isNull(offset + 41) ? null : cursor.getShort(offset + 41) != 0, // tgjcqk_sfgmyc
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // tgjcqk_sfgmycms
            cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43) != 0, // tgjcqk_sfwszqyc
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // tgjcqk_sfwszqycms
            cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45) != 0, // tgjcqk_sfjzyc
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // tgjcqk_sfjzycms
            cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0, // tgjcqk_sfqdyc
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // tgjcqk_sfqdycms
            cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49) != 0, // zzjy_sfzz
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // zzjy_yy
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // zzjy_jgjks
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // zd_zdmc
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // zd_tsyzjcl
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // zd_xcsfrq
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // zd_xcfsdd
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // zd_sfysqm
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // createTime
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpNewborn entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_fsrq(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrxx_fscs(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrxx_csrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGrxx_zrys(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWyqk_wyfs(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWyqk_cnl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWyqk_cncs(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWyqk_sfot(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setJbstzk_dbxz(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setJbstzk_dbcs(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setJbstzk_dbys(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setJbstzk_smwt(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setGwe_sfgwe(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0);
        entity.setTgjcqk_mqtz(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTgjcqk_tw(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTgjcqk_sc(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTgjcqk_hxpl(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTgjcqk_ml(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTgjcqk_ms(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTgjcqk_hdbw(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTgjcqk_qx(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTgjcqk_qxjl(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTgjcqk_sfywgyc(cursor.isNull(offset + 24) ? null : cursor.getShort(offset + 24) != 0);
        entity.setTgjcqk_sfywgycms(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setTgjcqk_sfewgyc(cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26) != 0);
        entity.setTgjcqk_sfewgycms(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTgjcqk_sfbyc(cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0);
        entity.setTgjcqk_sfbycms(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setTgjcqk_sfkqyc(cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30) != 0);
        entity.setTgjcqk_sfkqycms(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTgjcqk_sfxftzyc(cursor.isNull(offset + 32) ? null : cursor.getShort(offset + 32) != 0);
        entity.setTgjcqk_sfxftzycms(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setTgjcqk_sffbczyc(cursor.isNull(offset + 34) ? null : cursor.getShort(offset + 34) != 0);
        entity.setTgjcqk_sffbczycms(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setTgjcqk_sfszhddyc(cursor.isNull(offset + 36) ? null : cursor.getShort(offset + 36) != 0);
        entity.setTgjcqk_sfszhddycms(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setTgjcqk_sfjbbkyc(cursor.isNull(offset + 38) ? null : cursor.getShort(offset + 38) != 0);
        entity.setTgjcqk_sfjbbkycms(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setTgjcqk_pf(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setTgjcqk_sfgmyc(cursor.isNull(offset + 41) ? null : cursor.getShort(offset + 41) != 0);
        entity.setTgjcqk_sfgmycms(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setTgjcqk_sfwszqyc(cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43) != 0);
        entity.setTgjcqk_sfwszqycms(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setTgjcqk_sfjzyc(cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45) != 0);
        entity.setTgjcqk_sfjzycms(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setTgjcqk_sfqdyc(cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0);
        entity.setTgjcqk_sfqdycms(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setZzjy_sfzz(cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49) != 0);
        entity.setZzjy_yy(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setZzjy_jgjks(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setZd_zdmc(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setZd_tsyzjcl(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setZd_xcsfrq(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setZd_xcfsdd(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setZd_sfysqm(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setCreateTime(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setUpdateTime(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpNewborn entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpNewborn entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
