package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpDiabetesMellitus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_DIABETES_MELLITUS.
*/
public class FollowUpDiabetesMellitusDao extends AbstractDao<FollowUpDiabetesMellitus, String> {

    public static final String TABLENAME = "FOLLOW_UP_DIABETES_MELLITUS";

    /**
     * Properties of entity FollowUpDiabetesMellitus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_zrys = new Property(2, String.class, "grxx_zrys", false, "GRXX_ZRYS");
        public final static Property Grxx_sfrq = new Property(3, String.class, "grxx_sfrq", false, "GRXX_SFRQ");
        public final static Property Grxx_sffs = new Property(4, String.class, "grxx_sffs", false, "GRXX_SFFS");
        public final static Property Zz = new Property(5, String.class, "zz", false, "ZZ");
        public final static Property Tz_xy = new Property(6, String.class, "tz_xy", false, "TZ_XY");
        public final static Property Tz_xl = new Property(7, String.class, "tz_xl", false, "TZ_XL");
        public final static Property Tz_tz = new Property(8, String.class, "tz_tz", false, "TZ_TZ");
        public final static Property Tz_sg = new Property(9, String.class, "tz_sg", false, "TZ_SG");
        public final static Property Tz_tzzs = new Property(10, String.class, "tz_tzzs", false, "TZ_TZZS");
        public final static Property Tz_zbdmbd = new Property(11, String.class, "tz_zbdmbd", false, "TZ_ZBDMBD");
        public final static Property Tz_yw = new Property(12, String.class, "tz_yw", false, "TZ_YW");
        public final static Property Tz_qt = new Property(13, String.class, "tz_qt", false, "TZ_QT");
        public final static Property Shzdfs_rxyl = new Property(14, String.class, "shzdfs_rxyl", false, "SHZDFS_RXYL");
        public final static Property Shzdfs_ryjl = new Property(15, String.class, "shzdfs_ryjl", false, "SHZDFS_RYJL");
        public final static Property Shzdfs_ydl = new Property(16, String.class, "shzdfs_ydl", false, "SHZDFS_YDL");
        public final static Property Shzdfs_zs = new Property(17, String.class, "shzdfs_zs", false, "SHZDFS_ZS");
        public final static Property Shzdfs_xltz = new Property(18, String.class, "shzdfs_xltz", false, "SHZDFS_XLTZ");
        public final static Property Shzdfs_zyxw = new Property(19, String.class, "shzdfs_zyxw", false, "SHZDFS_ZYXW");
        public final static Property Yyqk = new Property(20, String.class, "yyqk", false, "YYQK");
        public final static Property Yds = new Property(21, String.class, "yds", false, "YDS");
        public final static Property Fzjc = new Property(22, String.class, "fzjc", false, "FZJC");
        public final static Property Fyycx = new Property(23, String.class, "fyycx", false, "FYYCX");
        public final static Property Ywblfy_sfywblfy = new Property(24, Boolean.class, "ywblfy_sfywblfy", false, "YWBLFY_SFYWBLFY");
        public final static Property Jkwt_ywblfyms = new Property(25, String.class, "jkwt_ywblfyms", false, "JKWT_YWBLFYMS");
        public final static Property Dxtfy = new Property(26, String.class, "dxtfy", false, "DXTFY");
        public final static Property Ccsffl = new Property(27, String.class, "ccsffl", false, "CCSFFL");
        public final static Property Zz_sfzz = new Property(28, Boolean.class, "zz_sfzz", false, "ZZ_SFZZ");
        public final static Property Zz_sfzzms = new Property(29, String.class, "zz_sfzzms", false, "ZZ_SFZZMS");
        public final static Property Zz_jgjks = new Property(30, String.class, "zz_jgjks", false, "ZZ_JGJKS");
        public final static Property Zzhf_rq = new Property(31, String.class, "zzhf_rq", false, "ZZHF_RQ");
        public final static Property Zzhf_bqgsh = new Property(32, String.class, "zzhf_bqgsh", false, "ZZHF_BQGSH");
        public final static Property Zzhf_hbz = new Property(33, String.class, "zzhf_hbz", false, "ZZHF_HBZ");
        public final static Property Zzhf_qtjb = new Property(34, String.class, "zzhf_qtjb", false, "ZZHF_QTJB");
        public final static Property Zzhf_xcsfrq = new Property(35, String.class, "zzhf_xcsfrq", false, "ZZHF_XCSFRQ");
        public final static Property Zzhf_sfysqm = new Property(36, String.class, "zzhf_sfysqm", false, "ZZHF_SFYSQM");
        public final static Property CreateTime = new Property(37, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(38, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public FollowUpDiabetesMellitusDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpDiabetesMellitusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_DIABETES_MELLITUS' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_ZRYS' TEXT," + // 2: grxx_zrys
                "'GRXX_SFRQ' TEXT," + // 3: grxx_sfrq
                "'GRXX_SFFS' TEXT," + // 4: grxx_sffs
                "'ZZ' TEXT," + // 5: zz
                "'TZ_XY' TEXT," + // 6: tz_xy
                "'TZ_XL' TEXT," + // 7: tz_xl
                "'TZ_TZ' TEXT," + // 8: tz_tz
                "'TZ_SG' TEXT," + // 9: tz_sg
                "'TZ_TZZS' TEXT," + // 10: tz_tzzs
                "'TZ_ZBDMBD' TEXT," + // 11: tz_zbdmbd
                "'TZ_YW' TEXT," + // 12: tz_yw
                "'TZ_QT' TEXT," + // 13: tz_qt
                "'SHZDFS_RXYL' TEXT," + // 14: shzdfs_rxyl
                "'SHZDFS_RYJL' TEXT," + // 15: shzdfs_ryjl
                "'SHZDFS_YDL' TEXT," + // 16: shzdfs_ydl
                "'SHZDFS_ZS' TEXT," + // 17: shzdfs_zs
                "'SHZDFS_XLTZ' TEXT," + // 18: shzdfs_xltz
                "'SHZDFS_ZYXW' TEXT," + // 19: shzdfs_zyxw
                "'YYQK' TEXT," + // 20: yyqk
                "'YDS' TEXT," + // 21: yds
                "'FZJC' TEXT," + // 22: fzjc
                "'FYYCX' TEXT," + // 23: fyycx
                "'YWBLFY_SFYWBLFY' INTEGER," + // 24: ywblfy_sfywblfy
                "'JKWT_YWBLFYMS' TEXT," + // 25: jkwt_ywblfyms
                "'DXTFY' TEXT," + // 26: dxtfy
                "'CCSFFL' TEXT," + // 27: ccsffl
                "'ZZ_SFZZ' INTEGER," + // 28: zz_sfzz
                "'ZZ_SFZZMS' TEXT," + // 29: zz_sfzzms
                "'ZZ_JGJKS' TEXT," + // 30: zz_jgjks
                "'ZZHF_RQ' TEXT," + // 31: zzhf_rq
                "'ZZHF_BQGSH' TEXT," + // 32: zzhf_bqgsh
                "'ZZHF_HBZ' TEXT," + // 33: zzhf_hbz
                "'ZZHF_QTJB' TEXT," + // 34: zzhf_qtjb
                "'ZZHF_XCSFRQ' TEXT," + // 35: zzhf_xcsfrq
                "'ZZHF_SFYSQM' TEXT," + // 36: zzhf_sfysqm
                "'CREATE_TIME' TEXT," + // 37: createTime
                "'UPDATE_TIME' TEXT);"); // 38: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_DIABETES_MELLITUS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpDiabetesMellitus entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_zrys = entity.getGrxx_zrys();
        if (grxx_zrys != null) {
            stmt.bindString(3, grxx_zrys);
        }
 
        String grxx_sfrq = entity.getGrxx_sfrq();
        if (grxx_sfrq != null) {
            stmt.bindString(4, grxx_sfrq);
        }
 
        String grxx_sffs = entity.getGrxx_sffs();
        if (grxx_sffs != null) {
            stmt.bindString(5, grxx_sffs);
        }
 
        String zz = entity.getZz();
        if (zz != null) {
            stmt.bindString(6, zz);
        }
 
        String tz_xy = entity.getTz_xy();
        if (tz_xy != null) {
            stmt.bindString(7, tz_xy);
        }
 
        String tz_xl = entity.getTz_xl();
        if (tz_xl != null) {
            stmt.bindString(8, tz_xl);
        }
 
        String tz_tz = entity.getTz_tz();
        if (tz_tz != null) {
            stmt.bindString(9, tz_tz);
        }
 
        String tz_sg = entity.getTz_sg();
        if (tz_sg != null) {
            stmt.bindString(10, tz_sg);
        }
 
        String tz_tzzs = entity.getTz_tzzs();
        if (tz_tzzs != null) {
            stmt.bindString(11, tz_tzzs);
        }
 
        String tz_zbdmbd = entity.getTz_zbdmbd();
        if (tz_zbdmbd != null) {
            stmt.bindString(12, tz_zbdmbd);
        }
 
        String tz_yw = entity.getTz_yw();
        if (tz_yw != null) {
            stmt.bindString(13, tz_yw);
        }
 
        String tz_qt = entity.getTz_qt();
        if (tz_qt != null) {
            stmt.bindString(14, tz_qt);
        }
 
        String shzdfs_rxyl = entity.getShzdfs_rxyl();
        if (shzdfs_rxyl != null) {
            stmt.bindString(15, shzdfs_rxyl);
        }
 
        String shzdfs_ryjl = entity.getShzdfs_ryjl();
        if (shzdfs_ryjl != null) {
            stmt.bindString(16, shzdfs_ryjl);
        }
 
        String shzdfs_ydl = entity.getShzdfs_ydl();
        if (shzdfs_ydl != null) {
            stmt.bindString(17, shzdfs_ydl);
        }
 
        String shzdfs_zs = entity.getShzdfs_zs();
        if (shzdfs_zs != null) {
            stmt.bindString(18, shzdfs_zs);
        }
 
        String shzdfs_xltz = entity.getShzdfs_xltz();
        if (shzdfs_xltz != null) {
            stmt.bindString(19, shzdfs_xltz);
        }
 
        String shzdfs_zyxw = entity.getShzdfs_zyxw();
        if (shzdfs_zyxw != null) {
            stmt.bindString(20, shzdfs_zyxw);
        }
 
        String yyqk = entity.getYyqk();
        if (yyqk != null) {
            stmt.bindString(21, yyqk);
        }
 
        String yds = entity.getYds();
        if (yds != null) {
            stmt.bindString(22, yds);
        }
 
        String fzjc = entity.getFzjc();
        if (fzjc != null) {
            stmt.bindString(23, fzjc);
        }
 
        String fyycx = entity.getFyycx();
        if (fyycx != null) {
            stmt.bindString(24, fyycx);
        }
 
        Boolean ywblfy_sfywblfy = entity.getYwblfy_sfywblfy();
        if (ywblfy_sfywblfy != null) {
            stmt.bindLong(25, ywblfy_sfywblfy ? 1l: 0l);
        }
 
        String jkwt_ywblfyms = entity.getJkwt_ywblfyms();
        if (jkwt_ywblfyms != null) {
            stmt.bindString(26, jkwt_ywblfyms);
        }
 
        String dxtfy = entity.getDxtfy();
        if (dxtfy != null) {
            stmt.bindString(27, dxtfy);
        }
 
        String ccsffl = entity.getCcsffl();
        if (ccsffl != null) {
            stmt.bindString(28, ccsffl);
        }
 
        Boolean zz_sfzz = entity.getZz_sfzz();
        if (zz_sfzz != null) {
            stmt.bindLong(29, zz_sfzz ? 1l: 0l);
        }
 
        String zz_sfzzms = entity.getZz_sfzzms();
        if (zz_sfzzms != null) {
            stmt.bindString(30, zz_sfzzms);
        }
 
        String zz_jgjks = entity.getZz_jgjks();
        if (zz_jgjks != null) {
            stmt.bindString(31, zz_jgjks);
        }
 
        String zzhf_rq = entity.getZzhf_rq();
        if (zzhf_rq != null) {
            stmt.bindString(32, zzhf_rq);
        }
 
        String zzhf_bqgsh = entity.getZzhf_bqgsh();
        if (zzhf_bqgsh != null) {
            stmt.bindString(33, zzhf_bqgsh);
        }
 
        String zzhf_hbz = entity.getZzhf_hbz();
        if (zzhf_hbz != null) {
            stmt.bindString(34, zzhf_hbz);
        }
 
        String zzhf_qtjb = entity.getZzhf_qtjb();
        if (zzhf_qtjb != null) {
            stmt.bindString(35, zzhf_qtjb);
        }
 
        String zzhf_xcsfrq = entity.getZzhf_xcsfrq();
        if (zzhf_xcsfrq != null) {
            stmt.bindString(36, zzhf_xcsfrq);
        }
 
        String zzhf_sfysqm = entity.getZzhf_sfysqm();
        if (zzhf_sfysqm != null) {
            stmt.bindString(37, zzhf_sfysqm);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(38, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(39, updateTime);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpDiabetesMellitus readEntity(Cursor cursor, int offset) {
        FollowUpDiabetesMellitus entity = new FollowUpDiabetesMellitus( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_zrys
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grxx_sfrq
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grxx_sffs
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // zz
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tz_xy
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tz_xl
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // tz_tz
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // tz_sg
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tz_tzzs
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // tz_zbdmbd
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // tz_yw
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // tz_qt
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // shzdfs_rxyl
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // shzdfs_ryjl
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // shzdfs_ydl
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // shzdfs_zs
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // shzdfs_xltz
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // shzdfs_zyxw
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // yyqk
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // yds
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // fzjc
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // fyycx
            cursor.isNull(offset + 24) ? null : cursor.getShort(offset + 24) != 0, // ywblfy_sfywblfy
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // jkwt_ywblfyms
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // dxtfy
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // ccsffl
            cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0, // zz_sfzz
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // zz_sfzzms
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // zz_jgjks
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // zzhf_rq
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // zzhf_bqgsh
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // zzhf_hbz
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // zzhf_qtjb
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // zzhf_xcsfrq
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // zzhf_sfysqm
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // createTime
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpDiabetesMellitus entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_zrys(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrxx_sfrq(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrxx_sffs(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setZz(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTz_xy(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTz_xl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTz_tz(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTz_sg(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTz_tzzs(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTz_zbdmbd(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTz_yw(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTz_qt(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setShzdfs_rxyl(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setShzdfs_ryjl(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setShzdfs_ydl(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setShzdfs_zs(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setShzdfs_xltz(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setShzdfs_zyxw(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setYyqk(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setYds(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setFzjc(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setFyycx(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setYwblfy_sfywblfy(cursor.isNull(offset + 24) ? null : cursor.getShort(offset + 24) != 0);
        entity.setJkwt_ywblfyms(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setDxtfy(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setCcsffl(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setZz_sfzz(cursor.isNull(offset + 28) ? null : cursor.getShort(offset + 28) != 0);
        entity.setZz_sfzzms(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setZz_jgjks(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setZzhf_rq(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setZzhf_bqgsh(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setZzhf_hbz(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setZzhf_qtjb(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setZzhf_xcsfrq(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setZzhf_sfysqm(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setCreateTime(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setUpdateTime(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpDiabetesMellitus entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpDiabetesMellitus entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
