package com.shbestwin.followupmanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shbestwin.followupmanager.model.followup.FollowUpThreeSixNewborn;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_UP_THREE_SIX_NEWBORN.
*/
public class FollowUpThreeSixNewbornDao extends AbstractDao<FollowUpThreeSixNewborn, String> {

    public static final String TABLENAME = "FOLLOW_UP_THREE_SIX_NEWBORN";

    /**
     * Properties of entity FollowUpThreeSixNewborn.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FollowUpNo = new Property(0, String.class, "followUpNo", true, "FOLLOW_UP_NO");
        public final static Property Idcard = new Property(1, String.class, "idcard", false, "IDCARD");
        public final static Property Grxx_fsrq = new Property(2, String.class, "grxx_fsrq", false, "GRXX_FSRQ");
        public final static Property Grxx_nl = new Property(3, String.class, "grxx_nl", false, "GRXX_NL");
        public final static Property Grxx_sjnl = new Property(4, String.class, "grxx_sjnl", false, "GRXX_SJNL");
        public final static Property Grxx_zrys = new Property(5, String.class, "grxx_zrys", false, "GRXX_ZRYS");
        public final static Property Tgjcqk_tz = new Property(6, String.class, "tgjcqk_tz", false, "TGJCQK_TZ");
        public final static Property Tgjcqk_sc = new Property(7, String.class, "tgjcqk_sc", false, "TGJCQK_SC");
        public final static Property Tgjcqk_bmi = new Property(8, String.class, "tgjcqk_bmi", false, "TGJCQK_BMI");
        public final static Property Tgjcqk_tgfypj = new Property(9, String.class, "tgjcqk_tgfypj", false, "TGJCQK_TGFYPJ");
        public final static Property Tgjcqk_sl = new Property(10, String.class, "tgjcqk_sl", false, "TGJCQK_SL");
        public final static Property Tgjcqk_cyqcs = new Property(11, String.class, "tgjcqk_cyqcs", false, "TGJCQK_CYQCS");
        public final static Property Tgjcqk_cyqcsjl = new Property(12, String.class, "tgjcqk_cyqcsjl", false, "TGJCQK_CYQCSJL");
        public final static Property Tgjcqk_sftlyc = new Property(13, Boolean.class, "tgjcqk_sftlyc", false, "TGJCQK_SFTLYC");
        public final static Property Tgjcqk_sftlycms = new Property(14, String.class, "tgjcqk_sftlycms", false, "TGJCQK_SFTLYCMS");
        public final static Property Tgjcqk_sfywgyc = new Property(15, Boolean.class, "tgjcqk_sfywgyc", false, "TGJCQK_SFYWGYC");
        public final static Property Tgjcqk_sfywgycms = new Property(16, String.class, "tgjcqk_sfywgycms", false, "TGJCQK_SFYWGYCMS");
        public final static Property Tgjcqk_sfebyc = new Property(17, Boolean.class, "tgjcqk_sfebyc", false, "TGJCQK_SFEBYC");
        public final static Property Tgjcqk_sfebycms = new Property(18, String.class, "tgjcqk_sfebycms", false, "TGJCQK_SFEBYCMS");
        public final static Property Tgjcqk_sfxftzyc = new Property(19, Boolean.class, "tgjcqk_sfxftzyc", false, "TGJCQK_SFXFTZYC");
        public final static Property Tgjcqk_sfxftzycms = new Property(20, String.class, "tgjcqk_sfxftzycms", false, "TGJCQK_SFXFTZYCMS");
        public final static Property Tgjcqk_sffbczyc = new Property(21, Boolean.class, "tgjcqk_sffbczyc", false, "TGJCQK_SFFBCZYC");
        public final static Property Tgjcqk_sffbczycms = new Property(22, String.class, "tgjcqk_sffbczycms", false, "TGJCQK_SFFBCZYCMS");
        public final static Property Tgjcqk_sfwszqyc = new Property(23, Boolean.class, "tgjcqk_sfwszqyc", false, "TGJCQK_SFWSZQYC");
        public final static Property Tgjcqk_sfwszqycms = new Property(24, String.class, "tgjcqk_sfwszqycms", false, "TGJCQK_SFWSZQYCMS");
        public final static Property Tgjcqk_sfggyctzyc = new Property(25, Boolean.class, "tgjcqk_sfggyctzyc", false, "TGJCQK_SFGGYCTZYC");
        public final static Property Tgjcqk_sfggyctzycms = new Property(26, String.class, "tgjcqk_sfggyctzycms", false, "TGJCQK_SFGGYCTZYCMS");
        public final static Property Xhdbz = new Property(27, String.class, "xhdbz", false, "XHDBZ");
        public final static Property Sysjc = new Property(28, String.class, "sysjc", false, "SYSJC");
        public final static Property Fzjc = new Property(29, String.class, "fzjc", false, "FZJC");
        public final static Property Hbqk = new Property(30, String.class, "hbqk", false, "HBQK");
        public final static Property Yyxjbgl_sfyyxjb = new Property(31, Boolean.class, "yyxjbgl_sfyyxjb", false, "YYXJBGL_SFYYXJB");
        public final static Property Jbzd = new Property(32, String.class, "jbzd", false, "JBZD");
        public final static Property Zz_sfzz = new Property(33, Boolean.class, "zz_sfzz", false, "ZZ_SFZZ");
        public final static Property Zz_yy = new Property(34, String.class, "zz_yy", false, "ZZ_YY");
        public final static Property Zz_jgjks = new Property(35, String.class, "zz_jgjks", false, "ZZ_JGJKS");
        public final static Property Zd_zd = new Property(36, String.class, "zd_zd", false, "ZD_ZD");
        public final static Property Zd_yzhjy = new Property(37, String.class, "zd_yzhjy", false, "ZD_YZHJY");
        public final static Property Zd_xcsfrq = new Property(38, String.class, "zd_xcsfrq", false, "ZD_XCSFRQ");
        public final static Property Zd_sfysqm = new Property(39, String.class, "zd_sfysqm", false, "ZD_SFYSQM");
        public final static Property CreateTime = new Property(40, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(41, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public FollowUpThreeSixNewbornDao(DaoConfig config) {
        super(config);
    }
    
    public FollowUpThreeSixNewbornDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_UP_THREE_SIX_NEWBORN' (" + //
                "'FOLLOW_UP_NO' TEXT PRIMARY KEY NOT NULL ," + // 0: followUpNo
                "'IDCARD' TEXT NOT NULL ," + // 1: idcard
                "'GRXX_FSRQ' TEXT," + // 2: grxx_fsrq
                "'GRXX_NL' TEXT," + // 3: grxx_nl
                "'GRXX_SJNL' TEXT," + // 4: grxx_sjnl
                "'GRXX_ZRYS' TEXT," + // 5: grxx_zrys
                "'TGJCQK_TZ' TEXT," + // 6: tgjcqk_tz
                "'TGJCQK_SC' TEXT," + // 7: tgjcqk_sc
                "'TGJCQK_BMI' TEXT," + // 8: tgjcqk_bmi
                "'TGJCQK_TGFYPJ' TEXT," + // 9: tgjcqk_tgfypj
                "'TGJCQK_SL' TEXT," + // 10: tgjcqk_sl
                "'TGJCQK_CYQCS' TEXT," + // 11: tgjcqk_cyqcs
                "'TGJCQK_CYQCSJL' TEXT," + // 12: tgjcqk_cyqcsjl
                "'TGJCQK_SFTLYC' INTEGER," + // 13: tgjcqk_sftlyc
                "'TGJCQK_SFTLYCMS' TEXT," + // 14: tgjcqk_sftlycms
                "'TGJCQK_SFYWGYC' INTEGER," + // 15: tgjcqk_sfywgyc
                "'TGJCQK_SFYWGYCMS' TEXT," + // 16: tgjcqk_sfywgycms
                "'TGJCQK_SFEBYC' INTEGER," + // 17: tgjcqk_sfebyc
                "'TGJCQK_SFEBYCMS' TEXT," + // 18: tgjcqk_sfebycms
                "'TGJCQK_SFXFTZYC' INTEGER," + // 19: tgjcqk_sfxftzyc
                "'TGJCQK_SFXFTZYCMS' TEXT," + // 20: tgjcqk_sfxftzycms
                "'TGJCQK_SFFBCZYC' INTEGER," + // 21: tgjcqk_sffbczyc
                "'TGJCQK_SFFBCZYCMS' TEXT," + // 22: tgjcqk_sffbczycms
                "'TGJCQK_SFWSZQYC' INTEGER," + // 23: tgjcqk_sfwszqyc
                "'TGJCQK_SFWSZQYCMS' TEXT," + // 24: tgjcqk_sfwszqycms
                "'TGJCQK_SFGGYCTZYC' INTEGER," + // 25: tgjcqk_sfggyctzyc
                "'TGJCQK_SFGGYCTZYCMS' TEXT," + // 26: tgjcqk_sfggyctzycms
                "'XHDBZ' TEXT," + // 27: xhdbz
                "'SYSJC' TEXT," + // 28: sysjc
                "'FZJC' TEXT," + // 29: fzjc
                "'HBQK' TEXT," + // 30: hbqk
                "'YYXJBGL_SFYYXJB' INTEGER," + // 31: yyxjbgl_sfyyxjb
                "'JBZD' TEXT," + // 32: jbzd
                "'ZZ_SFZZ' INTEGER," + // 33: zz_sfzz
                "'ZZ_YY' TEXT," + // 34: zz_yy
                "'ZZ_JGJKS' TEXT," + // 35: zz_jgjks
                "'ZD_ZD' TEXT," + // 36: zd_zd
                "'ZD_YZHJY' TEXT," + // 37: zd_yzhjy
                "'ZD_XCSFRQ' TEXT," + // 38: zd_xcsfrq
                "'ZD_SFYSQM' TEXT," + // 39: zd_sfysqm
                "'CREATE_TIME' TEXT," + // 40: createTime
                "'UPDATE_TIME' TEXT);"); // 41: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_UP_THREE_SIX_NEWBORN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowUpThreeSixNewborn entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFollowUpNo());
        stmt.bindString(2, entity.getIdcard());
 
        String grxx_fsrq = entity.getGrxx_fsrq();
        if (grxx_fsrq != null) {
            stmt.bindString(3, grxx_fsrq);
        }
 
        String grxx_nl = entity.getGrxx_nl();
        if (grxx_nl != null) {
            stmt.bindString(4, grxx_nl);
        }
 
        String grxx_sjnl = entity.getGrxx_sjnl();
        if (grxx_sjnl != null) {
            stmt.bindString(5, grxx_sjnl);
        }
 
        String grxx_zrys = entity.getGrxx_zrys();
        if (grxx_zrys != null) {
            stmt.bindString(6, grxx_zrys);
        }
 
        String tgjcqk_tz = entity.getTgjcqk_tz();
        if (tgjcqk_tz != null) {
            stmt.bindString(7, tgjcqk_tz);
        }
 
        String tgjcqk_sc = entity.getTgjcqk_sc();
        if (tgjcqk_sc != null) {
            stmt.bindString(8, tgjcqk_sc);
        }
 
        String tgjcqk_bmi = entity.getTgjcqk_bmi();
        if (tgjcqk_bmi != null) {
            stmt.bindString(9, tgjcqk_bmi);
        }
 
        String tgjcqk_tgfypj = entity.getTgjcqk_tgfypj();
        if (tgjcqk_tgfypj != null) {
            stmt.bindString(10, tgjcqk_tgfypj);
        }
 
        String tgjcqk_sl = entity.getTgjcqk_sl();
        if (tgjcqk_sl != null) {
            stmt.bindString(11, tgjcqk_sl);
        }
 
        String tgjcqk_cyqcs = entity.getTgjcqk_cyqcs();
        if (tgjcqk_cyqcs != null) {
            stmt.bindString(12, tgjcqk_cyqcs);
        }
 
        String tgjcqk_cyqcsjl = entity.getTgjcqk_cyqcsjl();
        if (tgjcqk_cyqcsjl != null) {
            stmt.bindString(13, tgjcqk_cyqcsjl);
        }
 
        Boolean tgjcqk_sftlyc = entity.getTgjcqk_sftlyc();
        if (tgjcqk_sftlyc != null) {
            stmt.bindLong(14, tgjcqk_sftlyc ? 1l: 0l);
        }
 
        String tgjcqk_sftlycms = entity.getTgjcqk_sftlycms();
        if (tgjcqk_sftlycms != null) {
            stmt.bindString(15, tgjcqk_sftlycms);
        }
 
        Boolean tgjcqk_sfywgyc = entity.getTgjcqk_sfywgyc();
        if (tgjcqk_sfywgyc != null) {
            stmt.bindLong(16, tgjcqk_sfywgyc ? 1l: 0l);
        }
 
        String tgjcqk_sfywgycms = entity.getTgjcqk_sfywgycms();
        if (tgjcqk_sfywgycms != null) {
            stmt.bindString(17, tgjcqk_sfywgycms);
        }
 
        Boolean tgjcqk_sfebyc = entity.getTgjcqk_sfebyc();
        if (tgjcqk_sfebyc != null) {
            stmt.bindLong(18, tgjcqk_sfebyc ? 1l: 0l);
        }
 
        String tgjcqk_sfebycms = entity.getTgjcqk_sfebycms();
        if (tgjcqk_sfebycms != null) {
            stmt.bindString(19, tgjcqk_sfebycms);
        }
 
        Boolean tgjcqk_sfxftzyc = entity.getTgjcqk_sfxftzyc();
        if (tgjcqk_sfxftzyc != null) {
            stmt.bindLong(20, tgjcqk_sfxftzyc ? 1l: 0l);
        }
 
        String tgjcqk_sfxftzycms = entity.getTgjcqk_sfxftzycms();
        if (tgjcqk_sfxftzycms != null) {
            stmt.bindString(21, tgjcqk_sfxftzycms);
        }
 
        Boolean tgjcqk_sffbczyc = entity.getTgjcqk_sffbczyc();
        if (tgjcqk_sffbczyc != null) {
            stmt.bindLong(22, tgjcqk_sffbczyc ? 1l: 0l);
        }
 
        String tgjcqk_sffbczycms = entity.getTgjcqk_sffbczycms();
        if (tgjcqk_sffbczycms != null) {
            stmt.bindString(23, tgjcqk_sffbczycms);
        }
 
        Boolean tgjcqk_sfwszqyc = entity.getTgjcqk_sfwszqyc();
        if (tgjcqk_sfwszqyc != null) {
            stmt.bindLong(24, tgjcqk_sfwszqyc ? 1l: 0l);
        }
 
        String tgjcqk_sfwszqycms = entity.getTgjcqk_sfwszqycms();
        if (tgjcqk_sfwszqycms != null) {
            stmt.bindString(25, tgjcqk_sfwszqycms);
        }
 
        Boolean tgjcqk_sfggyctzyc = entity.getTgjcqk_sfggyctzyc();
        if (tgjcqk_sfggyctzyc != null) {
            stmt.bindLong(26, tgjcqk_sfggyctzyc ? 1l: 0l);
        }
 
        String tgjcqk_sfggyctzycms = entity.getTgjcqk_sfggyctzycms();
        if (tgjcqk_sfggyctzycms != null) {
            stmt.bindString(27, tgjcqk_sfggyctzycms);
        }
 
        String xhdbz = entity.getXhdbz();
        if (xhdbz != null) {
            stmt.bindString(28, xhdbz);
        }
 
        String sysjc = entity.getSysjc();
        if (sysjc != null) {
            stmt.bindString(29, sysjc);
        }
 
        String fzjc = entity.getFzjc();
        if (fzjc != null) {
            stmt.bindString(30, fzjc);
        }
 
        String hbqk = entity.getHbqk();
        if (hbqk != null) {
            stmt.bindString(31, hbqk);
        }
 
        Boolean yyxjbgl_sfyyxjb = entity.getYyxjbgl_sfyyxjb();
        if (yyxjbgl_sfyyxjb != null) {
            stmt.bindLong(32, yyxjbgl_sfyyxjb ? 1l: 0l);
        }
 
        String jbzd = entity.getJbzd();
        if (jbzd != null) {
            stmt.bindString(33, jbzd);
        }
 
        Boolean zz_sfzz = entity.getZz_sfzz();
        if (zz_sfzz != null) {
            stmt.bindLong(34, zz_sfzz ? 1l: 0l);
        }
 
        String zz_yy = entity.getZz_yy();
        if (zz_yy != null) {
            stmt.bindString(35, zz_yy);
        }
 
        String zz_jgjks = entity.getZz_jgjks();
        if (zz_jgjks != null) {
            stmt.bindString(36, zz_jgjks);
        }
 
        String zd_zd = entity.getZd_zd();
        if (zd_zd != null) {
            stmt.bindString(37, zd_zd);
        }
 
        String zd_yzhjy = entity.getZd_yzhjy();
        if (zd_yzhjy != null) {
            stmt.bindString(38, zd_yzhjy);
        }
 
        String zd_xcsfrq = entity.getZd_xcsfrq();
        if (zd_xcsfrq != null) {
            stmt.bindString(39, zd_xcsfrq);
        }
 
        String zd_sfysqm = entity.getZd_sfysqm();
        if (zd_sfysqm != null) {
            stmt.bindString(40, zd_sfysqm);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(41, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(42, updateTime);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowUpThreeSixNewborn readEntity(Cursor cursor, int offset) {
        FollowUpThreeSixNewborn entity = new FollowUpThreeSixNewborn( //
            cursor.getString(offset + 0), // followUpNo
            cursor.getString(offset + 1), // idcard
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // grxx_fsrq
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grxx_nl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grxx_sjnl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // grxx_zrys
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tgjcqk_tz
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tgjcqk_sc
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // tgjcqk_bmi
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // tgjcqk_tgfypj
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tgjcqk_sl
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // tgjcqk_cyqcs
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // tgjcqk_cyqcsjl
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // tgjcqk_sftlyc
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // tgjcqk_sftlycms
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // tgjcqk_sfywgyc
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tgjcqk_sfywgycms
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0, // tgjcqk_sfebyc
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // tgjcqk_sfebycms
            cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0, // tgjcqk_sfxftzyc
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // tgjcqk_sfxftzycms
            cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0, // tgjcqk_sffbczyc
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // tgjcqk_sffbczycms
            cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0, // tgjcqk_sfwszqyc
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // tgjcqk_sfwszqycms
            cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0, // tgjcqk_sfggyctzyc
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // tgjcqk_sfggyctzycms
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // xhdbz
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // sysjc
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // fzjc
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // hbqk
            cursor.isNull(offset + 31) ? null : cursor.getShort(offset + 31) != 0, // yyxjbgl_sfyyxjb
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // jbzd
            cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33) != 0, // zz_sfzz
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // zz_yy
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // zz_jgjks
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // zd_zd
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // zd_yzhjy
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // zd_xcsfrq
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // zd_sfysqm
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // createTime
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41) // updateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowUpThreeSixNewborn entity, int offset) {
        entity.setFollowUpNo(cursor.getString(offset + 0));
        entity.setIdcard(cursor.getString(offset + 1));
        entity.setGrxx_fsrq(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrxx_nl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrxx_sjnl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGrxx_zrys(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTgjcqk_tz(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTgjcqk_sc(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTgjcqk_bmi(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTgjcqk_tgfypj(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTgjcqk_sl(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTgjcqk_cyqcs(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTgjcqk_cyqcsjl(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTgjcqk_sftlyc(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setTgjcqk_sftlycms(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTgjcqk_sfywgyc(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setTgjcqk_sfywgycms(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTgjcqk_sfebyc(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
        entity.setTgjcqk_sfebycms(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTgjcqk_sfxftzyc(cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0);
        entity.setTgjcqk_sfxftzycms(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTgjcqk_sffbczyc(cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0);
        entity.setTgjcqk_sffbczycms(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTgjcqk_sfwszqyc(cursor.isNull(offset + 23) ? null : cursor.getShort(offset + 23) != 0);
        entity.setTgjcqk_sfwszqycms(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setTgjcqk_sfggyctzyc(cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0);
        entity.setTgjcqk_sfggyctzycms(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setXhdbz(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSysjc(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setFzjc(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setHbqk(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setYyxjbgl_sfyyxjb(cursor.isNull(offset + 31) ? null : cursor.getShort(offset + 31) != 0);
        entity.setJbzd(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setZz_sfzz(cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33) != 0);
        entity.setZz_yy(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setZz_jgjks(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setZd_zd(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setZd_yzhjy(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setZd_xcsfrq(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setZd_sfysqm(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setCreateTime(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setUpdateTime(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FollowUpThreeSixNewborn entity, long rowId) {
        return entity.getFollowUpNo();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FollowUpThreeSixNewborn entity) {
        if(entity != null) {
            return entity.getFollowUpNo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
